### ISSUE TITLE
BUG: which-key hides too soon

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#10]
which-key sometimes hides the buffer while I'm reading it (e.g. slow user)

**Comment by justbur** [comment]
Is it the close timer? Try increasing the delay for that. 

The nice thing in the minibuffer case is that it automatically closes on the next key press but stays open otherwise. That seems like the best behavior to me maybe with a longer delay on the force close.

**Comment by bmag** [comment]
Yes, it is the close timer. I didn't know the delay is useful for the minibuffer case.
Could you see if merging #13 lets you drop the close timer without losing functionality? I think that PR makes the timer redundant.

**Comment by justbur** [comment]
Removed the timer for now, see #13

**Comment by justbur** [comment]
Seems fine for me now without the close timer
