### ISSUE TITLE
which-key--reload-key-sequence is useful outside of which-key

### ISSUE THREAD

**Issue by jmcarthur** [justbur/emacs-which-key#103]
I have a keymap that I want to generate lazily when I type a prefix. I am able to do this by binding a function that generates the keymap, rebinds to the keymap, and then calls which-key--reload-key-sequence. It would be really nice for this function or something equivalent to be officially supported.

**Comment by justbur** [comment]
I'm not sure what you mean. In a separate package?

**Comment by jmcarthur** [comment]
I just mean to stop treating it as an internal-only function and renaming it to which-key-reload-key-sequence to indicate this.

**Comment by justbur** [comment]
Ah ok. Sure np
