### ISSUE TITLE
Evil-Surround commands are not seen in Which-Key

### ISSUE THREAD

**Issue by a13ph** [justbur/emacs-which-key#105]
Even if you add (setq which-key-allow-evil-operators t),
Evil-Surround is not showing which-key popup.

For brief example, on Vs there is no popup, 
as there is none on any other selection I've tried.

Most probably due to its implementation,
it being different than other operators.

I'll give all info you need if anyone fails to repro it.

https://github.com/syl20bnr/spacemacs/issues/5430#issuecomment-194526830

**Comment by justbur** [comment]
`which-key-allow-evil-operators` being true essentially allows for the popup to show when completing in `evil-inner-text-objects-map` or `evil-outer-text-objects-map`. This is after entering `di` or `da` for example.

`which-key-show-operator-state-maps` shows the following maps when evil goes into the operator state and `evil-this-operator` is non-nil. This seems to cover most cases.
`evil-operator-shortcut-map`
`evil-operator-state-map`
`evil-motion-state-map`

From a few quick tests, `evil-surround` does not use operator state, which explains why neither of the above have an effect. 

BTW, which-key is made to popup in the middle of incomplete key sequences. This is not how evil finds the command for something like `diw` (`d` is a complete command, while `di` is not for example) so it's not simple to cover all evil cases.
