### ISSUE TITLE
Make which-key compatible with key-chord-mode

### ISSUE THREAD

**Issue by ranulf** [justbur/emacs-which-key#108]
Hello,

it would be very nice if which-key would support to show prefixes triggered by a key-chord (available via elpa).

Assumed the following code example
```
(defvar wk-test-keymap (make-sparse-keymap))
(define-key wk-test-keymap (kbd "d") 'dired)
(define-key wk-test-keymap (kbd "i") 'ibuffer)
(key-chord-define-global ".." wk-test-keymap)
```

Leads to the following minibuffer when pressing the key chord "..".

![minibuffer_which-key](https://cloud.githubusercontent.com/assets/1084737/14077641/fca9e55e-f4ed-11e5-9c74-77fadd024c85.png)

Emacs version in use is 25.0.92.1, which-key is in version 20160321.1905.

**Comment by justbur** [comment]
I don't know anything about key-chord. What are you expecting to see in that example? Just d and i?

**Comment by ranulf** [comment]
Yes, sure, "d" and "i" should be showed, just like with a regular prefix key shows its descendants.

**Comment by justbur** [comment]
You can try advising `this-single-command-keys` similar to how it's done [here](https://github.com/kai2nenobu/guide-key/blob/master/guide-key.el#L578).

**Comment by ranulf** [comment]
The function to be advised is not available in which-key, so I suppose that won't work.

**Comment by justbur** [comment]
@ranulf I realized there's no need for the advice that guide-key uses (which I was never going to add anyway). It should work for you now.

**Comment by ranulf** [comment]
@justbur works as expected. thank you so much!
