### ISSUE TITLE
Declaring prefixes for modes messes up titles

### ISSUE THREAD

**Issue by lunaryorn** [justbur/emacs-which-key#109]
I'd like to setup prefixes for markdown mode bindings:

```elisp
  (which-key-declare-prefixes-for-mode 'markdown-mode
    "C-c TAB" "markdown/images"
    "C-c C-a" "markdown/links"
    "C-c C-c" "markdown/process"
    "C-c C-s" "markdown/style"
    "C-c C-t" "markdown/header"
    "C-c C-x" "markdown/structure"
    "C-c m" "markdown/personal")
```

However, now all declared prefixes have the **same** title, namely `markdown/images`.  It looks as if `-declare-prefixes-for-mode` uses only the first prefix title and applies it to **all** other bindings, ignoring their names.

Did I misunderstand the documentation?

**Comment by justbur** [comment]
> Did I misunderstand the documentation?

No, you did it correctly. Just a bug when using multiple titles in the same declaration. Should be fixed now. Thanks.

**Comment by lunaryorn** [comment]
@justbur Thank you, I'll try again once the current MELPA build has finished.

**Comment by lunaryorn** [comment]
@justbur Thank you for fixing this issue. Works perfectly now.
