### ISSUE TITLE
void-function variable-name-history

### ISSUE THREAD

**Issue by igorepst** [justbur/emacs-which-key#110]
Hi,
When trying to use `which-key-show-keymap`, I get `(void-function variable-name-history)`. As I understand, this is defined in [help-fns+.el](https://www.emacswiki.org/emacs/help-fns%2b.el), but this library is not required by `which-key`

**Comment by justbur** [comment]
I'm pretty sure that function is not used in which-key. Can you provide a
backtrace?

**Comment by justbur** [comment]
Never mind. I see the problem. Thanks for the report. Let me know if you still have trouble.

**Comment by igorepst** [comment]
OK, will check this. Thank you for the fast response

**Comment by igorepst** [comment]
Nope, it doesn't work.
[which-key-trace.txt](https://github.com/justbur/emacs-which-key/files/222849/which-key-trace.txt)

**Comment by justbur** [comment]
Hm, that's odd. I don't see why it's calling that variable as a function. I don't use helm. Can you try with helm-mode disabled to rule out a helm specific problem? 

Let me try explicitly initializing the variable. I'm not seeing the same issue by the way. Even without loading help-fns+.

**Comment by igorepst** [comment]
Seems, this is indeed has something to do with helm. I'll try investigate it more tomorrow

**Comment by justbur** [comment]
I think it should work with the latest commits. V1.1.6 now

**Comment by igorepst** [comment]
Works good. Thank you :+1:
