### ISSUE TITLE
Issue with C-h while which-key is active

### ISSUE THREAD

**Issue by sooheon** [justbur/emacs-which-key#111]
Previously, I used to be able to press `C-h n` while which-key was active to page through the bindings. Recently, `C-h` immediately takes me to `counsel-descbinds`. Looking in the spacemacs config for which-key, there are a bunch of obsolete settings. I have no personal config related to this. How can I go about debugging this? '

BTW, which-key-use-C-h-commands and which-key-use-C-h-for-paging are both true for me, and I still don't get the paging.

**Comment by justbur** [comment]
It's controlled by the value of `prefix-help-command` which should be `which-key-C-h-dispatch` for paging to work. Maybe something in spacemacs is overriding this setting after which-key is loaded. Paging works fine for me outside of spacemacs. There haven't been any recent changes on the which-key side related to this.

**Comment by sooheon** [comment]
Ah thanks, found the issue in the spacemacs-ivy layer. Thanks!

**Comment by Mihara** [comment]
This recently started happening for me, even though I'm not using spacemacs at all. Pretty much nothing I do helps -- the value of `prefix-help-command` is correct. When `counsel-mode-override-describe-bindings` is `nil`, I'm getting the default Emacs help. When it is `t`, I'm getting `counsel-descbinds`.

Did something change? Perhaps in counsel itself?

**Comment by justbur** [comment]
@Mihara Not that I'm aware of. I don't have any apparent issues on my side, so I'll need reproduction steps to look into it.
