### ISSUE TITLE
Truncated on right side in terminal

### ISSUE THREAD

**Issue by hinrik** [justbur/emacs-which-key#113]
Hi, I've been using `guide-key` and was interest in `which-key`, but I have an issue with the text being truncated when the key list is displayed on the right side. See:

![right-which-key](https://cloud.githubusercontent.com/assets/43533/14787543/2142d5ca-0b04-11e6-8a92-1fb15fb16c39.png)

This is not a problem when using `guide-key`:

![right-guide-key](https://cloud.githubusercontent.com/assets/43533/14787555/2f1e1948-0b04-11e6-999c-5936da60a53a.png)

Both cases above are using an empty emacs config (aside from melpa configuration to install the two packages), on emacs 24.4.1. I started emacs, split the window horiontally, (`C-x 2`), loaded and enabled `which-key`, called `(which-key-setup-side-window-right)`, and pressed `C-h`.

**Comment by justbur** [comment]
It's happening because in the font you are using the arrow is wider than the ascii characters which throws off the calculation. If you don't want to change fonts you can use an ascii character for the separator with something like
```elisp
(setq which-key-separator ":")
```
or try increasing `which-key-unicode-correction`.

**Comment by justbur** [comment]
Oh there's also some default truncation of the names built-in which you can adjust using `which-key-max-description-length`
