### ISSUE TITLE
C-u blocked

### ISSUE THREAD

**Issue by mambolevis** [justbur/emacs-which-key#114]
Hi,

I'm using the following configuration:
- Windows 10:
- Tests in emacs 24.5 and 25.
```
(use-package which-key
  :ensure t
  :config
  (which-key-mode))
```
Some prefix-combinations like (C-x ..) and (C-c ..) and (m-f ..), worked without problem. Nonetheless, the package blocked at least the following key-binding (C-u ..).

Is there something that I need to configure? 

Thanks,

Levis

**Comment by justbur** [comment]
C-u is not a prefix key. It sets the argument for the subsequent command.
If you hit C-u C-x it should show bindings for C-x and whatever command is
executed will have the prefix argument set. Or maybe I'm misunderstanding...

**Comment by mambolevis** [comment]
I was trying to instrument a function for Debugging using C-u C-M x. If I hit C-u C-M x without "installing" which-key the minibuffer gives me a feedback of key sequence C-u ....  entered. On other hand, when I use the package the minibuffer doesn't provide any information regarding C-u C-M x . It seems that which-key inhibits the echo area.

**Comment by justbur** [comment]
I see `C-u` in the echo area in between `C-u` and `C-M-x`. What are your which-key settings?

**Comment by mambolevis** [comment]
Bellow my settings:
(use-package which-key
  :ensure t
  :config
  (which-key-mode))

**Comment by justbur** [comment]
what do you have for the variable `echo-keystrokes`?

**Comment by mambolevis** [comment]
echo-keystrokes is a variable defined in ‘C source code’.
Its value is 0
Original value was 1

**Comment by justbur** [comment]
Oh I see. I was picking a bad default for `echo-keystrokes` when which-key was enabled. It should be better for you now. Let me know.

**Comment by mambolevis** [comment]
Yes now it is working. Thanks.
One question:
I updated the package directly from melpa and the change you made was already there. Every change you made in your repo is directly available in melpa?  It is just to learn a little bit how the process is made.

Regards,

**Comment by justbur** [comment]
Yes, melpa pulls changes from github directly (usually the master branch).
There is generally a four or five hour delay, but otherwise the changes are
immediately published.
