### ISSUE TITLE
Error running timer ‘which-key--update

### ISSUE THREAD

**Issue by mambolevis** [justbur/emacs-which-key#118]
Hi,

The following message appears when I use fullframe package:
`Error running timer ‘which-key--update’: (void-variable fullframe/previous-window-configuration)`
The configuration of fullframe:
```
(use-package fullframe
  :ensure t
  :defer t
  :init
  (progn
    (fullframe magit-status magit-mode-quit-window)
    (fullframe list-packages quit-window)
    )
  )
```
When I commented `;;(fullframe list-packages quit-window)` the problem disappears.

When I compile my init.el file, the following message appears:
```
Warning (bytecomp): the following functions might not be defined at runtime:
    magit-mode-quit-window
```
Do you have any suggestion or advice around this issue?

Regards,
Levis,

**Comment by justbur** [comment]
I'm not familiar with that package. Can you produce a backtrace with `toggle-debug-on-error` and paste it here?

**Comment by mambolevis** [comment]
![image](https://cloud.githubusercontent.com/assets/13024208/15016839/47930bb2-1213-11e6-90cd-c6ea7953a5fc.png)

The following `C-g` keybinding also fails.

**Comment by justbur** [comment]
If you `(require 'fullframe)` do you get the error still? It appears that the package added advice to `quit-window` without loading the package. Maybe it's an issue with the macro in that package. I think this is a bug with fullframe and not which-key.

**Comment by mambolevis** [comment]
When I `(require 'fullframe)` the problem disappears.

```
(require 'fullframe)
(use-package fullframe
  :ensure t
  :defer t
  :init
  (progn
    (toggle-debug-on-error)
    (fullframe magit-status magit-mode-quit-window)
    (fullframe list-packages quit-window)
    )
  )

```
What is the conclusion?

**Comment by justbur** [comment]
My guess: You are compiling the use-package form which expands all of the macros, including `fullframe`. After the macros are expanded, fullframe is no longer being loaded and hence the advice on `quit-window` refers to an unknown variable that has not been defined yet. 

I'll submit a patch to that package. In the meantime, you can remove the `require` and the `:defer t`.

**Comment by justbur** [comment]
The patch was merged already. You can reopen if you continue to have trouble.
