### ISSUE TITLE
not working on emacs 24.3

### ISSUE THREAD

**Issue by redguardtoo** [justbur/emacs-which-key#119]
24.4 is fine. I use v1.1.7 from stable.melpa.org on debian 7.9

**Comment by justbur** [comment]
Can you give me more information? Is there an error that you can get a backtrace for? I can bump the requirement to 24.4, but I'd like to know why.

**Comment by redguardtoo** [comment]
I got no error message. Could you support Emacs 24.3? I have to use debian in current project.

**Comment by justbur** [comment]
There were two frame width functions added in 24.4 that I didn't know about. I backported them and it appears to be working again. Let me know if you have any more trouble. I don't have enough time to test 24.3 regularly.

**Comment by redguardtoo** [comment]
Thanks. I will test in 24.3 from time to time.
