### ISSUE TITLE
Where is the right place to add hook to disable vim-empty-lines-mode for which-key?

### ISSUE THREAD

**Issue by sooheon** [justbur/emacs-which-key#121]
<img width="683" alt="screen shot 2016-05-06 at 9 53 29 pm" src="https://cloud.githubusercontent.com/assets/302945/15073536/fc411212-13d4-11e6-9c04-4493a002bf01.png">

Normally, I'd add (vim-empty-lines-mode -1) to the mode hook, but for which key I'm getting the empty-lines indicators even in the minibuffer. How can I turn this off?

**Comment by justbur** [comment]
Try `which-key-init-buffer-hook`. If that doesn't work, I'll look into it. I don't use that package.

**Comment by sooheon** [comment]
I've added this to my config: (add-hook 'which-key-init-buffer-hook (lambda () (vim-empty-lines-mode -1))) to no avail.

**Comment by justbur** [comment]
It works for me. You may need to kill the which-key buffer if which-key-mode is already started

**Comment by sooheon** [comment]
Ah it works if which-key-popup-type is minibuffer, not when it is side-window for me.

**Comment by sooheon** [comment]
Additionally, with which-key-popup-type side-window, the first keypress doesnt work, while a subsequent key sometimes works: i.e. SPC shows the empty-line indicators, but SPC-f sometimes doesn't

**Comment by justbur** [comment]
I was testing with side-window. That hook only gets run when the buffer is created which happens when `which-key-mode` is first called. You can try evaling this to confirm that that mode can be disabled

``elisp
(with-current-buffer which-key--buffer
  (vim-empty-lines-mode -1))
```

**Comment by sooheon** [comment]
Ah that works for me. No need for the hook then, I'll just keep that snippet in my config. Thanks.

**Comment by justbur** [comment]
For future reference the issue was that the which-key buffer was created before the hook was added and the hook is only run when the buffer is created.
