### ISSUE TITLE
which-key doesn't show up for lispy keybindings

### ISSUE THREAD

**Issue by nixmaniack** [justbur/emacs-which-key#124]
It used to show available keybindings when `C-4` i.e. `(lispy-x)` was pressed when lispy is active but it's not showing since some time. I don't have exact version to point where it started.

Using spacemacs, if it helps to debug. (Might be conflicting with hydra/transient state?)

**Comment by justbur** [comment]
It looks like it got converted into a hydra. Try `?`

**Comment by nixmaniack** [comment]
Cool! That was new to me, accessing using `?`. I did see it was hydra but wasn't sure of way of accessing it. Thanks!
