### ISSUE TITLE
Question + suggestion

### ISSUE THREAD

**Issue by fniessen** [justbur/emacs-which-key#125]
Hello, very nice mode you've given us!  Thanks a lot...

Question: Why are the letters DREST with a background in your first screenshot?  What does that mean?

Suggestion: Could you put the local-map bindings first (by alphabetical order), then the global ones (by alphabetical order as well), or make it customizable?  I find (now that such a thing is possible -- I'm coming from guide-key) that local key bindings have a much higher probability of being applied, or at least of making sense in the current context...

I've even now observed (and I dunno how to remove that) that I have lots of global key bindings which don't make sense in many buffers (like YASnippet bindings in read-only Help or Dired buffers for example)...

**Comment by justbur** [comment]
> Question: Why are the letters DREST with a background in your first screenshot? What does that mean?

Those are the "special keys" DEL, RET, ESC, SPC and TAB truncated and with a different face. See `which-key-special-keys`.

> Suggestion: Could you put the local-map bindings first (by alphabetical order), then the global ones (by alphabetical order as well), or make it customizable? I find (now that such a thing is possible -- I'm coming from guide-key) that local key bindings have a much higher probability of being applied, or at least of making sense in the current context...

I can look into it. There are already a few sorting options but this is not one of them. See `which-key-sort-order`

Thanks for the nice words.

**Comment by justbur** [comment]
By the way, in the meantime you can already change the face of the keys from local maps using `which-key-local-map-description-face`

**Comment by fniessen** [comment]
I've already changed the fonts (adding a light background and putting local bindings in bold)... but even after that, I found that looking at the most interesting bindings first would make more sense.

Up to you, of course!

**Comment by justbur** [comment]
It makes sense to me. If it's not too hard, I'm happy to add the option.

**Comment by justbur** [comment]
Try

```elisp
(setq which-key-sort-order 'which-key-local-then-key-order)
```
