### ISSUE TITLE
Non nil which-key-idle-secondary-delay causes performance issue

### ISSUE THREAD

**Issue by hedning** [justbur/emacs-which-key#126]
### Description

Setting `which-key-idle-secondary-delay` to eg. `0` causes emacs to use 100%
cpu when the which-key popup is open and the frame has focus. In some cases, eg.
in the spacemacs start buffer (`*spacmacs*`) the cursor will flicker between the
popup and the buffer.

As a secondary issue it also causes the message from an executed command to
be overwritten when the popup is open. I'm guessing this might be related since
it seems that `which-key--start-timer` is run too often from `which-key--update`.

This is a really nice feature which makes the popup a lot more responsive, so it
would be great to have it working.

Tested in spacmacs develop.

### Reproduction
- eval `(setq which-key-idle-secondary-delay 0)`
- open the which-key popup

#### Result

Emacs uses 100% cpu when the frame is focused.

### Reproduction of secondary issue
- eval `(setq which-key-idle-secondary-delay 0)`
- start a prefix binding which will output to the minibuffer
- wait for the popup
- finish the command

#### Result

The minibuffer shows the prefix keys and the `C-h` help text.

**Comment by justbur** [comment]
This passes 0 to `run-with-idle-timer` and I'm not sure what the consequences of that are. Do you still get a hang if the value is >0?

**Comment by hedning** [comment]
Yeah, the same thing happens for values above 0 (tried it up to 3). To be specific, emacs doesn't hang, it's fully usable, but it maxes out a full cpu thread (and causes some cursor issues sometimes).

**Comment by justbur** [comment]
Ok, thanks. I'll look into it, but I haven't experienced anything like this.

**Comment by hedning** [comment]
You're able to reproduce it though? I've now tried it on a clean spacemacs install, a plain emacs install with just which-key and a secondary machine and get the same cpu usage on both the terminal and graphic clients.

**Comment by justbur** [comment]
I see it now, and it should be fixed with d031bad. I didn't notice the effect on the cpu. Thanks for the report. Please reopen if when you get the next version it's not fixed for you.

**Comment by hedning** [comment]
Tried the new version now and it works. Thanks :)
