### ISSUE TITLE
which-key-idle-delay for when which-key has already shown up

### ISSUE THREAD

**Issue by blaenk** [justbur/emacs-which-key#127]
I'd like it if there were a separate delay we could configure (which I would personally set to 0) which would apply only if non-nil, and which would apply from the point after which-key has already appeared the first time.

So for example if I'm going to press `C-c C-x b c`, the regular `which-key-idle-delay` would apply for how long to wait before appearing after pressing `C-c`, then if I could set something like `which-key-post-idle-delay` or something to `0` so that any subsequent presses like `C-x` refresh which-key immediately.

My reasoning is that usually I either know the full key sequence already in which case the regular `which-key-idle-delay` saves me from which-key showing up unnecessarily, but if I wait for which-key to show up for the first key it's probably the case that I am going to be drilling down, and it becomes a hassle to have to wait for the delay to elapse after each key press just to continue drilling down.

**Comment by justbur** [comment]
It already exists but it looks like it didn't make it into the readme so
I'll fix that.

See which-key-idle-secondary-delay.

**Comment by blaenk** [comment]
Works great, thank you!
