### ISSUE TITLE
per-key idle delay

### ISSUE THREAD

**Issue by blaenk** [justbur/emacs-which-key#128]
This might be more of a hassle so I understand if it's not possible, but I was thinking that it would be great if I could set the initial/regular delay to 0 for my custom keys prefix (e.g. `SPC` and/or `C-c`), but otherwise have the regular delay save me from which-key popping up immediately after any other key sequence/binding. It would be the perfect setup for me, and perhaps it can be of some use for spacemacs as well (though I wouldn't know; I don't use that).

**Comment by justbur** [comment]
So you still want to have it pop up for all sequences but to have certain ones pop up more frequently? In other words, it's not that you want to ignore some sequences completely, right?

**Comment by blaenk** [comment]
That's right. So in other words, the regular `which-key-idle-delay` will continue to apply for all sequences, but for certain sequences, you can specify a delay specific to that sequence prefix (much like how you can use `which-key-add-key-based-replacements` to change the description text of certain sequences, except this is for delays.

So for example I could leave my regular `which-key-idle-delay` at whatever I default it at (1.0), but then since the vast majority of my binds are prefixed on `"SPC"` for example (similar to spacemacs), I can set that to a delay of 0, which really facilitates the "drill-down" nature of my bindings.

**Comment by blaenk** [comment]
I'm hoping it's not too complex to accommodate because I feel like it would be the perfect setup, but if it's something you're not open to no problem.

**Comment by justbur** [comment]
try this after updating

```elisp
(setq which-key-delayed-prefixes '([3]))
(setq which-key-delayed-prefixes-delay 3)
```

This will delay `C-c` for an additional 3 seconds past the standard `which-key-idle-delay`. Right now (I can change this if you want) the delayed prefixes are vector key sequences that have to match the current sequence exactly to be delayed. `[3]` represents the sequence `C-c`

**Comment by blaenk** [comment]
Thanks I'll give that a shot!

Is there a way I can determine what the vector is for an arbitrary sequence? For example I want to look up what vector to use for `SPC`. I saw that `key-description` can help you go from vector to string, but I don't know about the other way around.

**Comment by justbur** [comment]
I'll come up with an easier way to do this but you can use listify-key-sequence then convert the list to a vector. SPC should be [32] I think.   
  
  
  

  
  
>

**Comment by blaenk** [comment]
So I got a chance to try out the exact lines you said, except I changed my delay to 0.1. You mentioned that the delay:

> This will delay C-c for an additional 3 seconds **past** the standard which-key-idle-delay

However, my goal was to actually set these delays to something else (i.e. very short or instant), because my regular delay is 1.0. If that's what you meant, I did try them with 0.1 and what happens is that I press `C-c` and it seems like it takes the regular delay (1.0) and then it disappears and reappears continuously, like it flashes, perhaps on that 0.1 interval? I'm not sure.

My only other configuration is:

``` elisp
  (setq which-key-idle-delay 1.0
        which-key-idle-secondary-delay 0
        which-key-use-C-h-commands nil
        which-key-side-window-max-height 1.0)
```

**Comment by blaenk** [comment]
Yeah it flashes as if it's repeatedly re-showing after that prefix-specific delay.

**Comment by justbur** [comment]
Oh, I think it's an interaction with the secondary delay. Can you try disabling that? If that's the problem then I can fix it when I have time.

**Comment by blaenk** [comment]
Sure I'll give that a go! However, it seems like the prefix-specific delays you added, based on the wording you used, are delays _additional_ to the general/normal delay right? The thing is my normal delay is longer, and I want to make the prefix-specific delay way shorter or instant.

I'll give it a shot and report back.

**Comment by justbur** [comment]
I don't understand why you want to make the prefix specific delays so short. I'm not sure I understand the problem you are trying to solve.

**Comment by blaenk** [comment]
Yeah getting rid of my secondary delay did away with the flashing problem.

Perhaps my terminology is incorrect. What I'd like is the following. I have `(setq which-key-idle-delay 1.0)` right? So normally for any key sequence that is pressed, which-key will pop up after 1 second. However, I have a bunch of personal bindings I created in a tree-like structure rooted at `SPC`, similar to spacemacs in case you're familiar with that. So for example I can do `SPC t` to reach keys I can press to toggle various modes, such as say `SPC t a` for toggling auto-fill-mode.

The thing is, because I myself constructed those binds at `SPC` organized in a tree-like manner, which-key is very useful for navigating that tree of binds I created. See this image for an example:

![binds](http://i.imgur.com/2Y1QW81.png)

So for example I'll press `SPC` and look at which-key to remember that I want to do something git-related so I press `g`.

All I'm saying is that the regular `which-key-idle-delay` delay is perfect for everything else, when I press any other keys. But when I press `SPC` I would love it if which-key would pop up instantly so that I could quickly get to the point of figuring out what route I want to take in the tree of binds I created.

I hope that made more sense, if not please tell me and I'll try to rephrase another way.

**Comment by blaenk** [comment]
So hypothetically speaking perhaps if we could do something like:

``` elisp
(which-key-add-key-based-delays
  "SPC" 0.1
  "M-SPC" 0.1
  "C-c" 0.1)
```

So that when those keys are pressed, the delay of `0.1` is used instead of the regular `which-key-idle-delay`, otherwise `which-key-idle-delay` applies as usual.

**Comment by justbur** [comment]
Yes, that made sense. The way I interpreted what you are saying is to set `which-key-idle-delay` to be the minimum delay for any key sequence and then to have an additional delay specified by `which-key-delayed-prefixes-delay` for any prefixes you want delayed further.

**Comment by blaenk** [comment]
Ahhh okay, sorry for being confusing at first.

So when I found out about the secondary delay I was very happy, that's exactly what I want. However, the _initial_ delay for my `SPC` prefix is what's killing me heh. Once I get in, the secondary delay takes over and everything else is perfect.

**Comment by justbur** [comment]
So you want a "fast" key and then to have `which-key-idle-delay` apply to everything else if I understand right

**Comment by blaenk** [comment]
Exactly! That would be amazing!

Preferably if possible I would like the ability to specify arbitrary delays for arbitrary keys though. The reason is that in my case I'm using general.el and so I basically have this tree of personal binds aliased to the root keys `SPC` (for evil normal mode), `M-SPC` (for evil insert mode or emacs mode), and `C-c` (for when I instinctively reach for `C-c`). I imagine others would also find benefit in being able to specify arbitrary delays for whatever keys they see fit.

**Comment by justbur** [comment]
Ok, I understand what you want now, but the design is not that straightforward based on the current code. 

I prefer to stick with the idea that `which-key-idle-delay` is the minimum time that passes before the popup shows, but I made the mechanism for delaying keys a little more generic (and fixed the flashing thing).

See `which-key-delay-functions`. With this hook you can decide whether and by how much to delay the popup based on the key sequence (in string form now). A delay function receives the current key sequence and returns the delay time if the popup should be delayed.

**Comment by blaenk** [comment]
Alright so to do what I want, I should set `which-key-idle-delay` to 0 so that it applies to `SPC`, `M-SPC`, and `C-c`, then in the function I create, if it's _not_ one of those then I return 1.0 (the delay I want to apply to all other keys), otherwise I'll return `nil` (no delay).

Is that correct? I'll give that a shot thanks!

**Comment by justbur** [comment]
Sure, something like this

```elisp
(defun my-delay (prefix)
  (unless (member prefix '("SPC" "M-SPC" "C-c")) 1))
(add-hook 'which-key-delay-functions 'my-delay)
```

Let me know if you have any more problems. I didn't test this extensively yet.

**Comment by blaenk** [comment]
It seems to be working well! The only problem is that the situation is now flipped. The secondary delay seems not to be consulted at all. The reason I wanted something like this was because it was the last missing little detail in getting which-key to be instant for my personal bindings. So whereas I previously had to wait 1 second to begin using which-key for `SPC`, then subsequent nested binds would load instantly thanks to secondary delay, now I get `SPC` instantly but subsequent nested bindings take 1.0.

Sorry to be a hassle, it's nearly there!

**Comment by justbur** [comment]
It seems to work for me. What are your settings?

**Comment by blaenk** [comment]
To be clear, the new change is indeed making it so when I press `SPC` for example, it pops up instantly. What I'm saying is that now subsequent keys (e.g. `SPC e`) ignore the secondary delay, that is, the delay function seems to be applying to the secondary keys as well:

``` elisp
(setq which-key-idle-delay 0.0
      which-key-idle-secondary-delay 0.0
      which-key-use-C-h-commands nil
      which-key-side-window-max-height 1.0)

(defun my-which-key-delay (prefix)
  (unless (member prefix '("SPC" "M-SPC" "C-c"))
    1.0))

(add-hook 'which-key-delay-functions 'my-which-key-delay)
```

**Comment by blaenk** [comment]
I guess if I change the delay function to check if the prefix starts with one of those I can get it to work; I'll give that a shot. It'd be nice if the secondary delay applied though.

**Comment by blaenk** [comment]
Yeah actually that won't work. It does fix the secondary-delay to be instant for keys rooted at one of the ones I want, instead of just the root key (e.g. now applies to `SPC e` not just `SPC`), but I want _all_ secondary keys to be instant:

``` elisp
(defun my-which-key-delay (prefix)
  (unless (--any? (s-starts-with? it prefix) '("SPC" "M-SPC" "C-c"))
    1.0))
```

So by way of example

* `C-x` (1.0 delay) `8` (instant)
* `SPC` (instant) `e` (instant)

So I want all secondary keys to be instant no matter what, as well as certain root/top-level keys like `SPC`, which I've accomplished with the idle function.

**Comment by blaenk** [comment]
I think I can put that with an `(or ...)` to check if there is at least one space in the `prefix`, which means it's a secondary key. I'll try that.

**Comment by justbur** [comment]
I think there might be some conflicts with the timers, which depend on the delay times you set. I'll rework how the timers work soon and hopefully the issue will go away.

**Comment by justbur** [comment]
Try the latest update (https://github.com/justbur/emacs-which-key/commit/6adadec740b64bb33153a197222708ece353ad1f), which I think should be more consistent. Here's your example modified to work with it

```elisp
(setq which-key-idle-delay 0.0
      which-key-idle-secondary-delay 0.0
      which-key-use-C-h-commands nil
      which-key-side-window-max-height 1.0)

(defun my-which-key-delay (prefix length)
  (unless (or (string-match-p "^\\(SPC\\|M-SPC\\|C-c\\)" prefix)
              (> length 1))
    1.0))

(add-hook 'which-key-delay-functions 'my-which-key-delay)
```

I added an argument to the delay functions to make it easy to ignore sequences longer than 1 key.

**Comment by blaenk** [comment]
I can confirm that it seems to be working perfectly! Thank you very much! Feel free to close this.

**Comment by justbur** [comment]
Great :)

**Comment by mambolevis** [comment]
1) I tested the new change and it is working (nice!!). Nonetheless, an old issue appeared again: when pressing `C-u`, it is not shown in the echo area. The problem is located here:
```
(defcustom which-key-echo-keystrokes (if (and echo-keystrokes
                                              (> (+ echo-keystrokes 0.01)
                                                 which-key-idle-delay))
                                         (/ (float which-key-idle-delay) 4)
                                       echo-keystrokes)
```

2) I have an extra question: In my configuration I use `super `and `hyper ` intensively, so I put them in my `my-which-key-delay` as shown below:
```
(use-package which-key
  :ensure t
  :init
  (setq which-key-idle-delay 0.0
        which-key-idle-secondary-delay 0.0
        which-key-side-window-max-height 1.0
        which-key-sort-order 'which-key-prefix-then-key-order)
  (defun my-which-key-delay (prefix length)
    (unless (or (string-match-p "^\\(s\\|H\\|C-c\\)" prefix)
                (> length 1))
      1.0))
  (add-hook 'which-key-delay-functions 'my-which-key-delay)
  :config
  (which-key-mode))
```
How can I setup, for example, the key `super ` to lunch which key popup once I press it? Or maybe the question is: how to define `super `as prefix?

**Comment by justbur** [comment]
1) your setting of 0 for the idle delay effectively makes using `echo-keystrokes` (which is the built-in emacs mechanism for showing key sequences) not possible. The problem is that which-key uses the echo area and that line is to ensure that emacs doesn't echo right after which-key does. There are a couple of options. One is to keep which-key out of the echo area and another is to use a short but non-zero delay. The second is easier. Try these settings for example

```elisp
(setq which-key-idle-delay 0.01
      which-key-idle-secondary-delay 0.01
      which-key-use-C-h-commands t
      which-key-echo-keystrokes 0.005
      which-key-side-window-max-height 1.0)
```

2) super is a modifier no? Maybe I don't understand the question

**Comment by mambolevis** [comment]
1) Yes, in my case the option of using a short but non-zero for the idle delay is the best.
In the case of the idle-secondary-delay it should be zero? 

2) Ok, I supposed that. As you said emacs doesn't see when you press control. I didn't know that `super` and `hyper` keys have the same restriction (Do you know why is the reason of that constrain?)
In fact I tried something like this:
`(global-set-key (kbd "s") my-modes-key-map)` but it didn't work :-). 

Thank you for this very nice package!

**Comment by justbur** [comment]
In general, I think it's probably a good idea to avoid setting any of these to 0 since these control timers and 0 would mean "always fire immediately". There doesn't seem to be any problem with small numbers though.

In `(global-set-key (kbd "s") my-modes-key-map)`, that's just the `s` key. `s-` is the modifier `super`, but you can't bind to a modifier in emacs. You *might* be able to get your OS to send a keystroke when you press `super` but that is outside of the scope of Emacs.

**Comment by mambolevis** [comment]
Thanks!
