### ISSUE TITLE
Is it possible to  active which-key  only for some prefix keys not for all prefix keys

### ISSUE THREAD

**Issue by sickHamm** [justbur/emacs-which-key#129]
like  this in guide-key `(setq guide-key/guide-key-sequence nil)` and `(add-to-list 'guide-key/guide-key-sequence "C-c p")`

**Comment by justbur** [comment]
Not easily at the moment. Are you looking for a whitelist or a blacklist?

**Comment by sickHamm** [comment]
I prefer whitelist ;  a simple variable `t` could mean active all  prefix keys;

--
this is a question issue , you could close if you like; or keep open for a feature request

**Comment by justbur** [comment]
I added a whitelist and a blacklist. For the whitelist, use `which-key-allow-regexps`. Add any regexps for key sequences that you want to allow to that list. When it's nil, the functionality is disabled. 

For example, if you only want the popup on key bindings with the `C-x` prefix do

```elisp
(setq which-key-allow-regexps '("^C-x"))
```

**Comment by sickHamm** [comment]
Thanks, work well.
