### ISSUE TITLE
Is it possible to  active which-key   for  C-M-  prefix key.

### ISSUE THREAD

**Issue by sickHamm** [justbur/emacs-which-key#131]
which-key could work well with `ESC-` prefix key. but couldn't work with `C-M-` prefix key (press and hold Ctrl+Alt).

**Comment by sickHamm** [comment]
I'm wrong， like  `C-M-f` not key sequence，just  single key； because "C-M-" is modifier key just like 
`C-`, which-key also wouldn't active for `C-`.

**Comment by justbur** [comment]
Right, it's not possible. It would be nice. I agree.
