### ISSUE TITLE
Possibility to hide common prefix part for the commands?

### ISSUE THREAD

**Issue by nixmaniack** [justbur/emacs-which-key#132]
<img width="1278" alt="screen shot 2016-07-29 at 5 54 49 pm" src="https://cloud.githubusercontent.com/assets/542810/17248312/4e668404-55b7-11e6-9ab7-938a432ffc12.png">

Is it possible to hide/shorten the common prefix part(`projectile-rails-`) for the commands displayed by which-key?

**Comment by justbur** [comment]
Yes, definitely

```elisp
(push '("projectile-rails-\\(.+\\)" . "\\1") which-key-description-replacement-alist)
```

**Comment by nixmaniack** [comment]
Awesome! That looks nice now. Thank you.

**Comment by scottjacobsen** [comment]
Just for reference, `which-key-description-replacement-alist` is no deprecated. This works for me today:
```elisp
(push '((nil . "projectile-rails-\\(.+\\)") . (nil . "\\1")) which-key-replacement-alist)
```
