### ISSUE TITLE
window is glitching anywhere when I move cursor

### ISSUE THREAD

**Issue by eephyne** [justbur/emacs-which-key#134]
I'm using which-key mainly because I just started using emacs and thats a BIG help for beginner in my opinion.

I set it to side window because its the only one that fit my need.

its work gread except that it glitch everytime I move the cursor, it show up and dissappear right away. I thing its maybe related to the 0.0 delay I put but I like the 0.0 delay

**Comment by eephyne** [comment]
well I did 0.01 and it solve it. 
I think you may need to add a guard to prevent the 0.0 value ?

**Comment by justbur** [comment]
I'll add a note to the readme and the docstring. Thanks

**Comment by hraban** [comment]
Is this still relevant? I don't observe this behaviour on mac, native build from source. How can we repro?
