### ISSUE TITLE
how to configure spacing in which-key?

### ISSUE THREAD

**Issue by yilihong** [justbur/emacs-which-key#138]
Hi, in my which-key buffer, the spacing is really large... I am wondering if there is a way to condense the line spacing a bit, making it narrower (both row and column)?

<img width="1093" alt="screenshot 2016-08-26 16 11 54" src="https://cloud.githubusercontent.com/assets/11595258/18194265/410ae992-7099-11e6-9025-4a465929c48c.png">

**Comment by justbur** [comment]
Are you referring to the spacing between rows? or the width of the columns?

**Comment by yilihong** [comment]
@justbur  I mean the spacing between the rows,

Is there also a way to change how many columns to show?

**Comment by justbur** [comment]
What is the value of `line-spacing`? Do you see the same amount of line spacing in other buffers? You could try setting

```elisp
(setq which-key-separator " : ")
```

to see if it's a problem with the font that's providing your arrow character.

**Comment by yilihong** [comment]
@justbur that works perfectly. thank you! 

<img width="1067" alt="screenshot 2016-09-02 21 00 20" src="https://cloud.githubusercontent.com/assets/11595258/18222571/4da8ce3c-7150-11e6-8f86-0097c832e98e.png">

**Comment by yilihong** [comment]
@justbur I am wondering if there is a way to configure the width of each column in which-key (number of characters, for example?)? 

e.g. in the screenshot, the - : shrink-window-if-larger-than-bluf... is very long, wonder if we can specify the width.

**Comment by justbur** [comment]
To change the max width of every column, use `which-key-max-description-length`. To just change that particular one, there are a couple of ways but a simple one is
```elisp
(which-key-add-key-based-replacements "C-x -" "short description")
```

**Comment by yilihong** [comment]
@justbur works beautifully, thank you.
