### ISSUE TITLE
What determines the name of undeclared prefixes?

### ISSUE THREAD

**Issue by ivanbrennan** [justbur/emacs-which-key#141]
Without any prefix names explicitly declared (via `which-key-declare-prefixes`), some prefixes have names and others show as simply "prefix". For example, after typeing `C-x`, a few of the entries shown are:

```
5 → +ctl-x-5-prefix
6 → +2C-command
8 → +prefix
```

I'm trying to understand what generates these names. If it's possible to define my bindings in a way that will generate descriptive names without requiring me to declare them explicitly, I'd like to do so. I attempted to find an answer by combing through the code, but I'm not yet at that level with elisp.

**Comment by justbur** [comment]
It's a little cumbersome to do this, but the built-in command is called `define-prefix-command`. See https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Keys.html

**Comment by ivanbrennan** [comment]
@justbur Thanks, that worked. You're right though, it is cumbersome, especially trying to integrate it with evil and evil-leader. I'll stick with `which-key-declare-prefixes` since it offers more flexibility with less code.

In case anyone else is looking for an example, here's what I used to try it out in the context of evil and evil-leader bindings:

```emacs-lisp
(define-prefix-command 'buffers-map)
(define-key 'buffers-map "d" 'kill-this-buffer)
(evil-leader/set-key "b" 'buffers-map)
```
