### ISSUE TITLE
Feature request: set minimum height or max numbers of columns ?

### ISSUE THREAD

**Issue by sam217pa** [justbur/emacs-which-key#142]
When I am on a large screen, the labels are displayed all over it like so: 
![image](https://cloud.githubusercontent.com/assets/8091811/18990302/361d3010-8711-11e6-8fc8-307c7ae10df9.png)

I'd like to be able to see them all at once, like clustered in two or three columns at the bottom left.
This is what it does when the frame is smaller.
![image](https://cloud.githubusercontent.com/assets/8091811/18990372/a65d9680-8711-11e6-9ed7-c0e7575644e1.png)

The idea is to have a consistent interface that does not change depending on the frame size.

Do you think you can implement an option like `which-key-side-window-min-height 0.33` or `which-key-side-window-columns` ?

Or even better: Which-key already has this ability and I was dumb enough not to find it…

**Comment by sam217pa** [comment]
Well, it turns out I was dumb enough…

```lisp
(setq which-key-min-display-lines 10)
```

does the job. 

Found about that two minutes after submitting the issue.. embarassing...

**Comment by justbur** [comment]
No problem
