### ISSUE TITLE
Feature request: Prefix-first sort order?

### ISSUE THREAD

**Issue by therockmandolinist** [justbur/emacs-which-key#145]
Hi,

Can't believe I didn't find this package faster, it's wonderful. Would it be possible to have a prefix-first sorting order? 

Since I'm new to the package and only just started using it, I'm actually not really sure if that would make sense or be intuitive (given many nested prefixes, maybe?), but It would be nice to have/test the option! Thoughts?

**Comment by justbur** [comment]
> Would it be possible to have a prefix-first sorting order?

I'm not sure, but I think the option is available already. Try 

```elisp
(setq which-key-sort-order 'which-key-prefix-then-key-order)
```

**Comment by justbur** [comment]
Oh, you want the reverse of that? Where all the prefixes come first?

**Comment by therockmandolinist** [comment]
That is what I was referring to. I'm now unsure if it makes any sense since with a lot of prefixes, the immediately available commands would be obscured, and prefixes are kinda like "more" menus.

That said, I was thinking that it would be nice if the case-insensitive ordering was a customizable variable instead of a separate setting, so one could have `'which-key-prefix-then-key-order` _and_ case insensitive sorting.

**Comment by justbur** [comment]
Added the case toggle (which-key-sort-uppercase-first) and the sort function (which-key-prefix-then-key-order-reverse)

**Comment by therockmandolinist** [comment]
Awesome. Thanks!
