### ISSUE TITLE
Error running timer ‘which-key--update’: (void-function display-buffer-in-major-side-window)

### ISSUE THREAD

**Issue by Dickby** [justbur/emacs-which-key#146]
which key stopped working for me, I get this error message whenever I normally see the which-key window.
emacs 26.0.50.5 
which-key-20161005.1154
tested with 'emacs -Q'

**Comment by justbur** [comment]
emacs 26 ?? Is this from master?

**Comment by Dickby** [comment]
Yes

**Comment by Dickby** [comment]
it still works with emacs 25.1

**Comment by justbur** [comment]
Well that's great. They renamed the function and changed it https://github.com/emacs-mirror/emacs/commit/b8fd71d5709650c1aced92c772f70595c51881d2

I'm not sure it makes sense to fix this right now...

**Comment by kaushalmodi** [comment]
Same here.. breaks on emacs 26 (master build)

**Comment by Dickby** [comment]
That's bad.
I copied the new named function to my .emacs file and gave it the old name.
For now it works.

**Comment by Dickby** [comment]
maby it's possible to check with 'fboundp' if the function exists, and if not take the new one?

**Comment by justbur** [comment]
If that works you can try this as a workaround

```elisp
(defalias 'display-buffer-in-major-side-window 'window--make-major-side-window)
```

I don't have time to look into this right now unfortunately.

**Comment by Dickby** [comment]
works!
thanks

**Comment by kaushalmodi** [comment]
@justbur Yes, that's what I plan to do

**Comment by robbyoconnor** [comment]
This seems to work if you have it at the bottom

**Comment by ninrod** [comment]
Jesus. They will provide a defalias, hopefully, right? I mean, in a release version?

**Comment by ninrod** [comment]
Eli Zaretsky said that it should be reported as a bug: https://lists.gnu.org/archive/html/help-gnu-emacs/2016-10/msg00077.html

**Comment by robbyoconnor** [comment]
Just just hit me

**Comment by oscarfv** [comment]
This issue is now [Bug#24828](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=24828) in the Emacs bug database.

I'll wait a few days for the author's response. It that does not happen, I'll push a fix that adds the alias.

**Comment by justbur** [comment]
Thanks @oscarfv

**Comment by justbur** [comment]
Pushed a fix for this. Please reopen if it doesn't work

**Comment by manuel-uberti** [comment]
Thank you @justbur.
