### ISSUE TITLE
question about which-key-add-key-based-replacements usage

### ISSUE THREAD

**Issue by ninrod** [justbur/emacs-which-key#148]
How do I do a *by-mode* `which-key-add-key-based-replacements`?

In org-mode buffers I want that: 

```lisp
(which-key-declare-prefixes ", l" "label/tag")
```

And in term-mode buffers, I want that: 
```lisp
(which-key-declare-prefixes ", l" "links")
```

basically, I want that `,` be my local leader for major-mode mapping.  So `, a` could mean something in org-mode but something completely different for `js2-mode`, for example. 

Is there a way to do that?

thanks in advance.

**Comment by sriramkswamy** [comment]
Is `which-key-add-major-mode-key-based-replacements` what you are looking for?

```
(which-key-add-major-mode-key-based-replacements 'org-mode
  ", l" "label/tag")

(which-key-add-major-mode-key-based-replacements 'term-mode
  ", l" "links")
```

**Comment by ninrod** [comment]
Yes! thank you! How did you know that you could add a mapping as an argument to that function?

**Comment by sriramkswamy** [comment]
I'm not sure what you mean. If you are asking where I got the information on using this function to add names, [it's in the README](https://github.com/justbur/emacs-which-key#custom-string-replacement-options).

**Comment by ninrod** [comment]
I just found that `C-h f` tells me: 

`(which-key-add-major-mode-key-based-replacements MODE KEY-SEQUENCE
REPLACEMENT &rest MORE)`

I was using the deprecated function. Thanks again.
