### ISSUE TITLE
TODO: require cl-lib directly

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#15]
```elisp
(require 'cl-lib)
```
should replace
```elisp
(require 'cl-macs)
(require 'cl-extra)
```
See [CL package manual](http://www.gnu.org/software/emacs/manual/html_node/cl/), or more specifically: [usage](http://www.gnu.org/software/emacs/manual/html_node/cl/Usage.html#Usage) and [organization](
http://www.gnu.org/software/emacs/manual/html_node/cl/Organization.html#Organization).

**Comment by justbur** [comment]
This is fixed now. Thank you for the clarification. I was getting a compiler warning for `(require 'cl)` and that was my hacky fix
