### ISSUE TITLE
Doesn't work with easy-kill package

### ISSUE THREAD

**Issue by rdotdk** [justbur/emacs-which-key#150]
As the title says, which-key doesn't show suggestions for easy-kill package.

Can be reproduced with the following code using `emacs -q` in `GNU Emacs 25.0.94.1 (i686-pc-linux-gnu, GTK+ Version 2.24.25) of 2016-10-11`.
## Code :

``` elisp
(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-refresh-contents)

(package-initialize)
 ;; install which-key
(package-install 'which-key)
 ;; install easy-kill
(package-install 'easy-kill)
;; enable which-key
(require 'which-key)
(which-key-mode)
;; enable easy-kill and easy-mark
(global-set-key [remap kill-ring-save] 'easy-kill)
(global-set-key [remap mark-sexp] 'easy-mark)

```
## Steps:
1. Start emacs and eval the above mentioned code.
2. Press C-x, wait for a second, the which key shows keys to be pressed after C-x. (Works).
3. Press M-w, wait for a second, the which key doesn't show any keys in popup. 

Normally, pressing M-w emacs will say "The mark is not set now, so there is no region", if no region is selected. But with easy-kill package installed and configured, we can  press w/s/l to select word/sexp/list at point.

**Comment by justbur** [comment]
Briefly testing this, `M-w` maps to the command `easy-kill`, so `M-w` is not a prefix but triggers a complete key sequence (see [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Keymap-Basics.html#Keymap-Basics)). which-key only works with prefixes. The easy-kill maintainer would have to make some changes to make it work with which-key (if they wanted to).
