### ISSUE TITLE
unicode characters not displayed when using emacs --daemon

### ISSUE THREAD

**Issue by rdotdk** [justbur/emacs-which-key#151]
As the title says in which key mode, the unicode characters are not displayed properly.

Emacs version :
GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.30) of 2016-09-21
which key taken today by git clone.
On Ubuntu system Ubuntu 16.04.1 LTS x86_64
minimal config to reproduce the issue

``` elisp
(add-to-list 'load-path "/path/emacs-which-key/")
(require 'which-key)
(which-key-mode)

;; UTF-8 please                                                                                                                                                          
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(prefer-coding-system 'utf-8)

```
When i run the emacs using ``` emacs -nw ``` in terminal i get proper unicode displayed in which key mode on pressing ```C-x```.
![screenshot from 2016-10-20 11-14-02](https://cloud.githubusercontent.com/assets/3027568/19547575/93ef1a8c-96b6-11e6-988c-64fa9b2e15a4.png)

With the same config if i start daemon ```emacs --daemon``` and run the emacsclient with ```emacsclient -t```. I get the following on pressing ```C-x```.
![screenshot from 2016-10-20 11-14-32](https://cloud.githubusercontent.com/assets/3027568/19547594/b95def0a-96b6-11e6-8555-5e4d99998734.png)

**Comment by rdotdk** [comment]
With emacs in daemon mode, i'm unable to insert unicode character with ```C-x 8 ` i ``` but pressing the same keys inserts unicode character when emacs started with ``` emacs -nw ```. Looks like issue with ```emacs```. Do i need to configure anything additional for emacs unicode to work in daemon mode?

**Comment by justbur** [comment]
I don't know how to fix that problem, which as you said is an emacs problem. As for which-key you can use
```elisp
(setq which-key-dont-use-unicode t)
```
to avoid using any unicode characters in the which-key settings.

**Comment by rdotdk** [comment]
I'm seeing this issue only with Ubuntu. With the same Emacs version/packages, it works with Debian. Probably something specific to Ubuntu terminal. 

>(setq which-key-dont-use-unicode t)

>to avoid using any unicode characters in the which-key settings.


Thanks!
