### ISSUE TITLE
Hide specific bindings from which-key display

### ISSUE THREAD

**Issue by deb0ch** [justbur/emacs-which-key#152]
Is there a way of hiding specific key sequences from which-key display panes ?

More specifically, the use case is for bindings like in [Spacemacs](https://github.com/syl20bnr/spacemacs) for navigating windows, sending windows to other buffers and stuff like that.

For instance,
```
1  → window 1    5  → window 5    9  → window 9
2  → window 2    6  → window 6
3  → window 3    7  → window 7
4  → window 4    8  → window 8
```
could be just
```
1..9  → window 1..9
```

This would help uncluttering some crowded which-key panes.

If it is not already implemented, would it be easy to implement ?

**Comment by justbur** [comment]
See `which-key-binding-filter-function`. It will allow for arbitrary manipulations of key bindings like the one you described. If you need help writing the filter function, please ask.

**Comment by deb0ch** [comment]
Thanks so much ! :smiley:

I will let you know if I have any issues using it.

**Comment by deb0ch** [comment]
Hi @justbur,

I finally found some time to work on the matter, and I have come with that solution:

``` elisp
(setq which-key-binding-filter-function
        (lambda (cell prefix)
          (cond
           ((string-match "select-window-1" (cdr cell)) '("0 .. 9" . "window 0 .. 9"))
           ((string-match "select-window-[0-9]" (cdr cell)) nil)
           ((string-match "buffer-to-window-1" (cdr cell)) '("0 .. 9" . "buffer-to-window 0 .. 9"))
           ((string-match "buffer-to-window-[0-9]" (cdr cell)) nil)
           (cell))))
```

Though this works for my particular case, where the user didn't modify any of these bindings, I find it a bit fragile and I think that we could do better.

The problem with that approach is that I receive the bindings separately, and thus can't treat one according to the others.

This would be possible if the `which-key-binding-filter-function` did not give me the elements of the list separated, but was called only once with the whole list instead (the `unformated` list in [which-key.el:1504](https://github.com/justbur/emacs-which-key/blob/master/which-key.el#L1504)).

This way we could be more exact if, for instance, the user just rebound the `SPC 4` key, instead of displaying

```
0 .. 9  → window 0 .. 9
      4  → blah
```

(which is I currently have), we had

```
0 .. 3  → window 0 .. 3
      4  → blah
5 .. 9  → window 5 .. 9
```

Even better, we would not be screwed if the user rebound `SPC 1`.

What do you think ?

**Comment by justbur** [comment]
Hi, Hold off on this for now actually. I want to rewrite and simplify the logic for replacing and modifying key bindings which will also change the api. When I get to it I'll provide an example for this case as well.

**Comment by deb0ch** [comment]
Ok, I'm looking forward to it then :smile_cat: 

If the code handling which-key display modifications in spacemacs will need to be rewritten as well anyways, I would like to submit it as-is for now.

Such cluttered panes are really itching me, especially since the recent addition of 10 window-number bindings to `SPC b` :grimacing: 

Let me know if you advise against it :bowtie:

**Comment by casouri** [comment]
Don't know if you still care but this is how spacemacs handles it:

```
  ;; create a fake key to represent all ten keys 
  (push '(("\\(.*\\) 0" . "winum-select-window-0-or-10") . ("\\1 0..9" . "window 0..9")) which-key-replacement-alist)
  ;; hide other keys
  (push '((nil . "winum-select-window-[1-9]") . t) which-key-replacement-alist)
```

I hope this can be helpful

**Comment by deb0ch** [comment]
@casouri Thank you very much, I was actually asking this for the sake of Spacemacs and the snippet you included is what was implemented following this issue 😁

**Comment by casouri** [comment]
The. I got to say thank you! That’s what I copied into my config. 👍
