### ISSUE TITLE
void-function display-buffer-in-major-side-window

### ISSUE THREAD

**Issue by manuel-uberti** [justbur/emacs-which-key#153]
Hi,

first of all thanks for this great Emacs package. I updated `which-key` from MELPA this morning, and now I get this error:
```
Debugger entered--Lisp error: (void-function display-buffer-in-major-side-window)
  display-buffer-in-major-side-window(#<buffer  *which-key*> bottom 0 ((window-width . which-key--fit-buffer-to-window-horizontally) (window-height lambda (w) (fit-window-to-buffer w nil 1))))
  which-key--show-buffer-side-window((8 . 103))
  which-key--show-popup((8 . 103))
  which-key--show-page(0)
  which-key--create-buffer-and-show([3])
  which-key--update()
  apply(which-key--update nil)
  timer-event-handler([t 0 0 400000 t which-key--update nil idle 0])
```
It happens in `emacs -Q` as well. I am using `GNU Emacs 26.0.50.1 (x86_64-debian-linux-gnu, GTK+ Version 3.14.5) of 2016-10-30`.

**Comment by VanLaser** [comment]
I guess for a while more people will try emacs-26 - maybe until this [patch](http://lists.gnu.org/archive/html/emacs-diffs/2016-10/msg00307.html ) lands on version 25. `display-buffer-in-major-side-window` was removed from emacs 26 (I don't know why, or what function(s) replaced it).

**Comment by manuel-uberti** [comment]
Thanks for the clarification. I'll switch back to `emacs-25` while this gets fixed.

**Comment by VanLaser** [comment]
BTW this issue was raised before, here's a possible solution https://github.com/justbur/emacs-which-key/issues/146#issuecomment-252030746

**Comment by manuel-uberti** [comment]
Awesome, thanks for the tip.
