### ISSUE TITLE
Was there support added for regex within which key strings?

### ISSUE THREAD

**Issue by sriramkswamy** [justbur/emacs-which-key#154]
I am getting the following behavior

Consider a code similar to the one below

```
(which-key-add-key-based-replacements
  "m \\" "mlint"
  "m +" "increase"
  "m ." "org edit special"
  "m *" "org abort edit"
  "m [" "org save edit")
```

- The `\\` inside the string does nothing. The name of the corresponding binding/prefix isn't modified
- `+` also does nothing. The name of the prefix/binding isn't changed
- `.` in the string replaces that and every other which key string following that with `org edit special` - like the `.` in regex
- `*` in a string replaces the prefix, i.e., `m` in this case with `org abort edit`
- `[` throws an error of unmatched expression in the `which-key--update` function and which key is unable to start.

This happens to me with the latest which key package in both Emacs 26 and Emacs 25.1. I run Emacs on macOS.

**Comment by justbur** [comment]
Thank you. You're right, but this was unintentional. I've been cleaning up and simplifying the backend logic for modifying key bindings. 

Your issue should be addressed in a2b3383
