### ISSUE TITLE
Replacement error with the latest update

### ISSUE THREAD

**Issue by drot** [justbur/emacs-which-key#155]
`which-key-20161129.1829`

If we use this:
```
(which-key-add-key-based-replacements
    "C-x a" "abbrev")
```

then we get this upon pressing `C-x a`

![2016-11-30-125504_1038x57_scrot](https://cloud.githubusercontent.com/assets/85483/20751576/c7103eda-b6fc-11e6-89e2-9ed6ff255119.png)

**Comment by justbur** [comment]
Thanks for the report. It should be fixed with the latest commit.
