### ISSUE TITLE
Use only one column when using side-window and undo scrolling when hiding popup

### ISSUE THREAD

**Issue by tarsius** [justbur/emacs-which-key#157]
When displaying bindings in a side-window, then I like to see only one column. More columns cover too much of the other windows and I actually like to see just one column (that's why I tried the side-window style in the first place). A quick way to achieve this is to comment the `while` form following `;; add additional columns as long as they fit`.

I don't mind it much when the use of a side-window causes the contents of other windows to be scrolled while displaying the popup (and when it happens, then that cannot be prevented anyway), but when the side-window is hidden, then I expect the old scrolling to be restored in all the other windows.

Please consider adding a `side-window-one-column` style, or something to that effect, and to find a way to restore the old scrolling. Thanks!

**Comment by justbur** [comment]
If it's just the size of the buffer there's this variable already: `which-key-side-window-max-width`.

If that's not sufficient I can do the one column thing. 

I'll look into the scrolling too.

**Comment by justbur** [comment]
I can't get the scrolling to be affected by the popup. In other words, it seems to always get restored for me. What's the situation?

**Comment by justbur** [comment]
@tarsius added a new option in 47c6f91

**Comment by tarsius** [comment]
Thanks, and sorry for not replying earlier. I wanted to do some experimentation of my own and haven't gotten around to it yet.

> If it's just the size of the buffer there's this variable already: which-key-side-window-max-width.

I think the option that you added is necessary because while I could come up with a width that works most of the time, sometimes my windows are much wider than usual and then I just want one column anyway.

I will reply to the rest later, possibly not after Christmas.

**Comment by justbur** [comment]
No problem. I'm happy to do it for you.

**Comment by tarsius** [comment]
I'll try to come up with instructions on how to reproduce the scrolling issue. Meanwhile some other remarks:

1. When using a side-window shown on the left or right, then it looks strange that it doesn't have a mode-line. Maybe the mode-line should be displayed in those cases and the "[C-h paging/help]" could be displayed there.
2. I still like using a side-window on the left or right, but only when I explicitly requested to see the key bindings. When the buffer pops up due to the timer, then I find that a bit distracting. It would be nice to customize the location depending on whether the buffer was requested explicitly or displayed by the timer. But that's probably not that easy to do because there are several options involved and duplicating them all probably isn't an option.
3. `which-key-side-window-max-width` should probably only have an effect when displaying a side-window on the left or right.
4. Combining (1) through (3) I would like to be able to say: "If I explicitly requested to see the key bindings, then show them in a side-window on the right using a single column and as much space as needed, and show the usage instructions in the mode-line. But if that fails or showing the bindings is triggered by the timer, then show them in the minibuffer, using as many columns as appropriate, and show the usage instructions on the first line. Oh boy.
5. I am (currently) binding `C-h C-h` to `which-key-show-toplevel`. Unfortunately "C-h (Type ? for further options)" which is displayed in the echo area by the first `C-h` isn't removed by the second `C-h`. Maybe that message (or any other) could be canceled using `(message "")`?
6. The visual indicators for truncated lines in the fringe (of the windows that were already being displayed when the which-key window was displayed) are a bit distracting when they appear on every line because the frame is rather thin. Unfortunately I don't see a way to prevent that. I was going to suggest to temporarily hide the right fringe (where those indicators normally appear), but then they just appear in the buffer.

**Comment by tarsius** [comment]
I think I know why I got "- which-key can’t show keys: There is not enough space based on your settings and frame size." before I increased `which-key-side-window-max-width`

```
  Top-level bindings (1 of 3) [C-h paging/help]
     DEL - backward-delete-char-untabi..
```

I.e. Commands are truncated where necessary, but the help line isn't. I assume there is some code which then checks the wide of the longest line and decides that the first line is to long and therefore displaying isn't possible.

**Comment by tarsius** [comment]
I can reproduce the scrolling issue with `emacs -Q -L . -l 157.el`, after placing this file in the `which-key` repository:

```
(require 'which-key)
(setq which-key-popup-type 'side-window)
(setq which-key-side-window-location 'right)
(setq which-key-side-window-max-width 1.0)
(setq which-key-max-display-columns 1)
(setq which-key-show-prefix 'top)
(global-set-key (kbd "C-h C-h") 'which-key-show-top-level)
(which-key-mode)
;; The frame should now be 80 characters wide, if not resize to
;; approximately that.

;; Then move to the end of one of the lines displayed in *scratch* and
;; press "C-h C-h" followed by "C-h a".
```

**Comment by justbur** [comment]
I don't have time to respond to everything right now, but here's a start

> 1. When using a side-window shown on the left or right, then it looks strange that it doesn't have a mode line. Maybe the mode-line should be displayed in those cases and the "[C-h paging/help]" could be displayed there.

Just played with this a little. It looks odd to me, but it's doable. I can add this

> 2. I still like using a side-window on the left or right, but only when I explicitly requested to see the key bindings. When the buffer pops up due to the timer, then I find that a bit distracting. It would be nice to customize the location depending on whether the buffer was requested explicitly or displayed by the timer. But that's probably not that easy to do because there are several options involved and duplicating them all probably isn't an option.

How about this?
```elisp
(let ((which-key-side-window-location 'right))
  (which-key-show-top-level))
```

> 3. which-key-side-window-max-width should probably only have an effect when displaying a side-window on the left or right.

It does only have an effect in that case. Are you seeing differently? 

> 4. Combining (1) through (3) I would like to be able to say: "If I explicitly requested to see the key bindings, then show them in a side-window on the right using a single column and as much space as needed, and show the usage instructions in the mode-line. But if that fails or showing the bindings is triggered by the timer, then show them in the minibuffer, using as many columns as appropriate, and show the usage instructions on the first line. Oh boy.

I would say see the answer to 2 and just define the key binding with the options you'd like to apply. 

> I am (currently) binding C-h C-h to which-key-show-toplevel. Unfortunately "C-h (Type ? for further options)" which is displayed in the echo area by the first C-h isn't removed by the second C-h. Maybe that message (or any other) could be canceled using (message "")?

Odd. It seems to be for me, unless I'm misunderstanding. Do you have `which-key-show-prefix` set to echo? 

> The visual indicators for truncated lines in the fringe (of the windows that were already being displayed when the which-key window was displayed) are a bit distracting when they appear on every line because the frame is rather thin. Unfortunately I don't see a way to prevent that. I was going to suggest to temporarily hide the right fringe (where those indicators normally appear), but then they just appear in the buffer.

You shouldn't have those, unless there is something up with wide unicode characters. Can you try `(setq which-key-separator " : ")` and see if they go away?

**Comment by justbur** [comment]
Added the 1 request in https://github.com/justbur/emacs-which-key/commit/49ab7afd93ef36e5f0261eff7151360edeeea4e6

**Comment by tarsius** [comment]
Using my own wrapper for `which-key-show-top-level` seems like a good idea.

About (5): The message that I don't want to see comes from the Emacs help system. Once I press `C-h` again to invoke `which-key-show-top-level` that message isn't relevant anymore but sticks around. But since I am going to use my own wrapper I can easily deal with that too.

About (6): The lines in the *other* (non-which-key) windows are truncated. I was talking about somehow suppressing the visual indicator of that.

**Comment by tarsius** [comment]
So I am using this now

```lisp
(defun jkl-which-key-show-top-level ()
  "Show top-level bindings."
  (interactive)
  (setq which-key--using-top-level t)
  (let ((which-key-popup-type 'side-window)
        (which-key-side-window-location 'right)
        (which-key-side-window-max-width 1.0)
        (which-key-max-display-columns 1)
        (which-key-show-prefix 'mode-line))
    (which-key--create-buffer-and-show nil))
  (message ""))
```

And outside of that I stick with the defaults.

**Comment by justbur** [comment]
> I.e. Commands are truncated where necessary, but the help line isn't. I assume there is some code which then checks the wide of the longest line and decides that the first line is to long and therefore displaying isn't possible.

Commands are truncated if they are longer than `which-key-max-description-length`. I'll add a check to truncate the help line. 

> About (5): The message that I don't want to see comes from the Emacs help system. Once I press C-h again to invoke which-key-show-top-level that message isn't relevant anymore but sticks around. But since I am going to use my own wrapper I can easily deal with that too.

I guess I could clear the echo area, but that seems a little heavy handed to do in every case. Your case is pretty specific to using `C-h` as a prefix. If you don't want which-key to use the echo area then my inclination would be to avoid touching it.

> About (6): The lines in the other (non-which-key) windows are truncated. I was talking about somehow suppressing the visual indicator of that.

I'm not sure if I want to do this, but maybe a hook or two could be useful here. 

> So I am using this now...

Looks good to me. I need to work on the display of the help line for the mode-line option too.

**Comment by tarsius** [comment]
> Looks good to me.

Yeah, I am pretty satisfied with that too. This was more intended as "there's some things I did run into" than "this has to be fixed" anyway. Thanks for your help! (Feel free to close.)

**Comment by justbur** [comment]
Happy to help. I'll leave it open as a reminder that I want to work on the display of the help strings.

**Comment by tarsius** [comment]
> I'll leave it open as a reminder that I want to work on the display of the help strings.

I am closing this because I am currently cleaning up my todo lists. You might want to add a new issue for that if you still intend to do that.
