### ISSUE TITLE
How to provide commands in a function like which-key--show-keymap 

### ISSUE THREAD

**Issue by drorbemet** [justbur/emacs-which-key#158]
Which-key is of great help in my editing workflow using emacs.
Now I am trying to use it more directly.

Which is the function that takes a keymap and shows it just like which-key--show-keymap does but activates the commands bound in the keymap to execute them when a key is pressed?

In other words using  elisp and without depending on prefixkeys, 
how is a keymap activated and it's which-key-buffer shown immediately without delay?

I searched through the code an didn't find a suitable entry point. Thanks for any hints on that one. 

```elisp
(defun my-key-map-def ()
  "Demonstrating the use of a prefix keymap with a global keybinding."
  (define-prefix-command 'my-key-map)
  (define-key 'my-key-map (kbd "k")
    '(lambda () (interactive)
      (message "Executed a command called from my-key-map.")))
  (global-set-key (kbd "C-S-s-k") 'my-key-map))

(my-key-map-def)

(defun show-keymap-to-call-commands ()
  "How to show which-key keymap with active commands?"
  (interactive)
  (which-key--show-keymap (symbol-name 'my-key-map) (symbol-value 'my-key-map)))
```

For now I changed `which-key--show-keymap` at the default `cond` case to call the command using `call-interactively` or `funcall`. 

```elisp
(cond
  (t (progn
      (which-key--hide-popup)
      (call-interactively (lookup-key keymap key t) t)
      ;; (funcall (lookup-key keymap key t))
      )))
```

But I'm unsure which one is suitable and if this is an additional layer of indirection which changes behaviour of the commands called this way.
Shouldn't be the calling of commands left to the prefix-keymaps and the watching of entered key-sequences to which-key?

[Here](http://stackoverflow.com/questions/24914202/elisp-call-keymap-from-code) is some former discussion about this by abo-abo. He uses `call-interactively` and `funcall` in his hydra keybinding system.

**Comment by justbur** [comment]
which-key doesn't "activate" keymaps. It periodically checks to see if you are in the middle of a key sequence and if you are it shows the available keys following that sequence. It sounds like you are looking for a [hydra](https://github.com/abo-abo/hydra) instead, but I may be misunderstanding what you are asking for.

**Comment by drorbemet** [comment]
Thanks for your reply. I'm trying to find out if which-key could be more simple than hydra in some cases. At the moment I'm using both in concert.

**Comment by doolio** [comment]
@justbur you stated above that `which-key` 

>  ... periodically checks to see if you are in the middle of a key sequence and if you are it shows the available keys following that sequence.

Is this why `which-key` is inhibited on entering the Spacemacs org-agenda transient state and enabled again on exit?

**Comment by justbur** [comment]
Potentially. I'm not familiar with org-agenda in spacemacs though. 
		
		

		
	




On Thu, Aug 10, 2017 at 7:38 AM -0400, "doolio" <notifications@github.com> wrote:












@justbur you stated above that which-key



... periodically checks to see if you are in the middle of a key sequence and if you are it shows the available keys following that sequence.



Is this why which-key is inhibited on entering the Spacemacs org-agenda transient state and enabled again on exit?

**Comment by doolio** [comment]
Ok. I thought you would be best placed to answer this as you authored both Spacemacs' core-transient-state.el and `which-key`. I don't actually use Spacemacs myself but am using their definition of their org-agenda transient state as a [hydra](https://github.com/abo-abo/hydra) in my own configuration. I believe their transient states are hydras with a wrapper but I may be misunderstanding the code. In any case, they make use of two character "heads" in the hydra nomenclature sense e.g. `vw` for `org-agenda-week-view` which conflicts with `which-key--update` if I recall correctly unless I too inhibit `which-key` on entry into my hydra with the hydra [`:pre`](https://github.com/abo-abo/hydra#pre-and-post) keyword (and re-enabling on exit with the `:post` keyword). 

Based on your explanation to this issue above I was curious if that could explain this need to inhibit `which-key` in this fashion. Anyway, I appreciate you taking the time to respond.

**Comment by justbur** [comment]
It's a reasonable question. I just don't follow spacemacs development anymore. Yes, transient-states are just hydras with a modified API more or less. 

The only reason to inhibit which-key is if it pops up at a point you don't want it to. which-key isn't aware of when or how a key sequence is being read. It's going to popup whenever it detects an incomplete key sequence. Since hydras are a similar way of visualizing available keys, it makes sense to prevent which-key from doing anything while a hydra is active. 

Does that answer your question?

**Comment by doolio** [comment]
Yes, it certainly does. Thanks again for taking the time.
