### ISSUE TITLE
SUGGESTION: use a specialized mode-line

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#16]
The default mode-line isn't very helpful for which-key buffer, but we can change it. We change it by setting the variable `mode-line-format` in `which-key/setup`. That variable is buffer-local.

One option is to remove it entirely for which-key buffer:
```elisp
(setq-local mode-line-format nil)
```
Using this should cause the side-window case to look the same as the minibuffer case, when `which-key-side-window-position` is set to `bottom`.

Another option is to use the mode-line to convey some useful information, such as which-key page number and the typed key sequence. For example, if the user typed "C-x" and which-key is showing the 1st page out of 3, the mode-line could look like this:
![which-key-mode-line](https://cloud.githubusercontent.com/assets/4334375/8564140/daf54b14-2550-11e5-821a-42174bc35f90.png)
This has the advantage of saving space in which-key window, but won't affect the minibuffer case. For the minibuffer case, we could imitate the mode-line by inserting a fake mode-line into which-key buffer's text.

**Comment by justbur** [comment]
Interesting. I like the idea. I added the option to show the prefix in the buffer itself. See the variable `which-key-show-prefix`. 

I like the page count idea if we figure out a way to do the paging nicely.

**Comment by justbur** [comment]
I decided to just hide it for now. We can come back to this if we add paging.

**Comment by bmag** [comment]
You introduced a bug:
> save-current-buffer: Symbol's function definition is void: hidden-mode-line-mode

`hidden-mode-line-mode` is defined in spacemacs, and is originally from http://bzg.fr/emacs-hide-mode-line.html. It isn't available out of the box.

**Comment by justbur** [comment]
Whoops. Ok I'll revert it. 

I need to fix the calculation for the height of the side window right case. Using frame height doesn't take the minibuffer or mode line into account.

**Comment by bmag** [comment]
frame-height does take the minibuffer into account, but not the mode line.

Don't revert it, instead replace it with (setq-local mode-line-format nil)`

**Comment by justbur** [comment]
Done!

When I was testing it yesterday, it didn't seem to be taking the minibuffer into account, but I didn't pursue it too carefully

**Comment by bmag** [comment]
I see that you used `(setq-local mode-line-format "")` instead of `(setq-local mode-line-format nil`). The former means there is an empty mode-line, the latter means there is no mode-line at all. Any reasons for preferring an empty mode-line?

**Comment by justbur** [comment]
Not at all. I didn't realize there was a distinction. I'm using nil now. Thanks

**Comment by justbur** [comment]
I think if I do anything I'll create my own "mode line" otherwise there will be inconsistencies between the minibuffer and the side window popups.

**Comment by justbur** [comment]
What if the first slot for the keys was used instead for the prefix keys and information about the number of bindings and the number shown?

**Comment by justbur** [comment]
Did a rough mock-up of the last idea on the status-key branch in case you're curious. Here's the idea

![status-key](https://cloud.githubusercontent.com/assets/2208382/8610158/9de2b392-267c-11e5-865a-2f5ddcc37bbf.png)

**Comment by syl20bnr** [comment]
@justbur Is the first line a regular line or the buffer header ?

**Comment by justbur** [comment]
Each key is in its own "cell" and this occupies the first cell, so no it's not a header line when there are multiple columns

**Comment by justbur** [comment]
Another option would be taking over the last cell to say something like (10 keys not shown)

**Comment by syl20bnr** [comment]
The last cell is a good idea, the user will get to it only if really required.

**Comment by justbur** [comment]
Right. I think I'll try that

**Comment by justbur** [comment]
@syl20bnr I merged the last cell idea to master. It should show up only when all the keys are not shown. Right now it only reports the number of keys not displayed

**Comment by justbur** [comment]
Let's open a new issue if someone wants to propose a different change. We're not using the mode line for now at least.

**Comment by justbur** [comment]
@bmag  I simplified the code for populating the buffer yesterday, which will make new features easier to add. I was thinking about putting the status in the mode line again like you suggested here. It will be much cleaner to do if/when I put in paging. I was wondering if you could look at what I've done on the develop branch to see if that's approximately what you were thinking about. Or maybe if you could point me to a package that handles the mode line in the way you imagined. Thanks!

If you run into any bugs, I'd be happy to hear about them too

**Comment by bmag** [comment]
Ok, I'll look at it. Basically the mode-line is built from "components", as described in the documentation of mode-line-format. Though I had to experiment with it quite a bit to understand what is a valid component. So the matter here is to create a proper component, which isn't too hard once you grasp what is a valid component. There the powerline and smart-mode-line packages, which focus on making the mode-line prettier. In my understanding they are wrappers around mode-line-format, but I'm not sure using them will be simple. Even if we decide not to use powerline or smart-mode-line, it's still worth testing the mode-line's appearance with these packages installed.

**Comment by justbur** [comment]
Thanks, that's interesting. All I did was to temporarily replace the
lighter, but I'll have to look into the construction of the mode line more.

**Comment by bmag** [comment]
Example of what I was thinking about:
![which-key-mode-line-3](https://cloud.githubusercontent.com/assets/4334375/8782633/79148990-2f1f-11e5-90e1-10b2a53ffa32.png)
Achieved by this code:
```elisp
(defun wk-mode-line-format ()
  (let* ((basestring (format "%s/%s keys" 17 22))
         (win-width (window-width))
         (need-width (length basestring))
         (dist-from-edge (/ (- win-width need-width) 2))
         (fmt-string (format "%%%ss" (+ dist-from-edge need-width))))
    (format fmt-string basestring)))
(setq mode-line-format '(t (:eval (wk-mode-line-format))))
```
Notes:
- You see that I'm using the mode-line of the which-key buffer itself. It doesn't mean that it's better than using the lighter, just an option.
- `17` and `22` should be replaced with internal variables (`which-key--shown-keys`, `which-key--total-keys`). Those variables should be set probably in the same place that changes the lighter, or instead of it.
- I could put this status-line at the top of which-key window, by setting `header-line-format` instead of `mode-line-format`.
- The code contains a hack so the "17/22 keys" is printed in middle of mode-line, instead of at the left. There may be a better way to accomplish it.
- The string produced by `wk-mode-line-format` can be propertized. In other words, we can give it a face and colors.
- The mode-line has a different background. I'm not sure how can it be changed.

We can include more information by using appropriate internal variables, so there are two main decisions to be made: 1) Where to show the status- in the lighter, mode-line or header-line? 2) What information to include in the status?
I can help with the implementation if you want, but I won't really have time to implement anything until next week.

**Comment by justbur** [comment]
Thanks, I like the idea for the side window like that, but I don't know how it translates to the bottom and the minibuffer. I kind of like hiding the modeline in the bottom case because it puts the echo area just below the keys, which looks good to me when you have the prefix being echoed in that area. Obviously the minibuffer would have to be different. 

I was starting to work on the paging stuff, which is trickier than I thought it would be, and with multiple pages I haven't come up with a way to display the number of keys and/or pages in the buffer yet in a way that doesn't require some ugly code. I was thinking of creating a margin or gutter in the buffer. This is essentially what I'm doing with the prefix keys now, and I think this might be the best. I could emulate the mode line in the side-window right case (or use it directly). When the buffer's on the bottom, the margin could be along the right side. 

Anyway, I'm curious what you think. No rush
