### ISSUE TITLE
What powerline you use in the screenshot?

### ISSUE THREAD

**Issue by LikiPiki** [justbur/emacs-which-key#160]
Hello. What powerline you use in the screenshot?
https://github.com/justbur/emacs-which-key/blob/master/img/which-key-bottom.png
Thanks a lot!

**Comment by justbur** [comment]
It's not powerline. It's a slightly modified version of [smart-mode-line](https://github.com/Malabarba/smart-mode-line) with the theme set to `respectful`

**Comment by LikiPiki** [comment]
Thanks a lot!
