### ISSUE TITLE
Not all of the ediff "keys -> commands" are listed when the w or r keys are pressed

### ISSUE THREAD

**Issue by duianto** [justbur/emacs-which-key#161]
### Descripton
During an ediff session, when <kbd>w</kbd> or <kbd>r</kbd> is pressed, then the minibuffer doesn't show all the available 
"keys -> commands".

### Steps to reproduce:
1. Start emacs
2. Compare 2 or 3 files: <kbd>M-x</kbd> `ediff` or <kbd>M-x</kbd> `ediff3`
(In spacemacs 2 files can be compared quickly by pressing <kbd>SPC f e D</kbd> to compare `.spacemacs` with `.spacemacs.template`)
3. Press <kbd>w</kbd> or <kbd>r</kbd>

#### 2 files:
The minibuffer shows these messages when
- <kbd>w</kbd> is pressed:
`b -> ediff-save-buffer d -> ediff-save-buffer`

- <kbd>r</kbd> is pressed:
`b -> ediff-restore-diff`

#### 3 files:
- When 3 files are "ediffed" and <kbd>w</kbd> is pressed, then the minibuffer only shows:
`d -> ediff-save-buffer`

- When <kbd>r</kbd> is pressed then the minibuffer only shows:
`c -> ediff-restore-diff`

#### 2 files:
- For the <kbd>w</kbd> key:
 `a -> ediff-save-buffer b -> ediff-save-buffer d -> ediff-save-buffer`

- For the <kbd>r</kbd> key:
`a -> ediff-restore-diff b -> ediff-restore-diff`

#### 3 files:
- For the <kbd>w</kbd> key:
`a -> ediff-save-buffer b -> ediff-save-buffer c -> ediff-save-buffer d -> ediff-save-buffer`

- For the <kbd>r</kbd> key:
`a -> ediff-restore-diff b -> ediff-restore-diff c -> ediff-restore-diff`

### The ediff copy "keys -> commands" are shown correctly
The 2 other keys are shown when <kbd>a</kbd>, <kbd>b</kbd> or <kbd>c</kbd> is pressed. 
For example, when <kbd>b</kbd> is pressed then the minibuffer shows:
`a -> ediff-copy-B-to-A c -> ediff-copy-B-to-C`

#### All the unlisted keys work as expected, they just aren't shown in the minibuffer.

These issues were first discovered in spacemacs, but some of them were also tested with just emacs and the which-key package, and the same thing happened there.

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. eef1a87e)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((markdown :variables markdown-live-preview-engine 'vmd)
 auto-completion chrome emacs-lisp git helm html markdown org)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

**Comment by justbur** [comment]
Thanks for the report. Please test after you get 0d56e43

**Comment by duianto** [comment]
That's smart to use `..` as a sequence, now it works as expected, thanks 👍

**Comment by justbur** [comment]
Actually Emacs does that if the same command has been bound on sequential
keys. It's a rare case, so I'm not totally surprised that which-key was
handling it incorrectly. Thanks again.
