### ISSUE TITLE
Boon Support

### ISSUE THREAD

**Issue by alanpearce** [justbur/emacs-which-key#162]
Would you consider supporting [boon](/jyp/boon) in the same manner as evil and god-mode? It seems like boon sits in between the two.

I'm trying to learn boon and it's a bit of a struggle as the cheatsheet can't show everything. I think only `boon-enclose` and `boon-c-god` need support as most other prefixes are real Emacs prefixes, but I've only just started trying the package.

I've been using which-key for a while now and it's been working well in normal Emacs, so thanks for that!

**Comment by justbur** [comment]
Can you give me a complete example from setting it up to key presses and what you would like to see. I've not seen boon before.

**Comment by alanpearce** [comment]
What is it that you want an example of? Its readme describes setting it up and the keypresses depend on the "front-end" (i.e. keyboard layout).

Maybe I should explain with references to the cheatsheet for qwerty: https://github.com/jyp/boon/blob/master/qwerty.pdf. What doesn't work with which-key right now (that I know of) are the blue keys, as well as 'a' and 'c'. The blue keys should bring up the "Left-hand text region specifiers" and the movement keys. Yellow keys are bound to prefix maps and work already.

Sorry that I can't explain everything; I don't know much about boon yet (which is exactly why I opened this issue)

**Comment by justbur** [comment]
Took a quick look and it doesn't look promising. which-key finds bindings by inspecting active keymaps, but the cases you pointed me to don't use keymaps at all to lookup bindings. `boon-enclose`, which uses `boon-spec-enclosure`, doesn't use a keymap to decide which pair to use for example.

**Comment by alanpearce** [comment]
Thanks for taking the time to investigate. I think I won't continue using boon anyway, so it's not a big deal.

**Comment by justbur** [comment]
No problem. For now it appears to require upstream changes that I'm not interested in asking for.
