### ISSUE TITLE
which-key-show-top-level appears to ignore which-key-add-key-based-replacements

### ISSUE THREAD

**Issue by Mihara** [justbur/emacs-which-key#163]
That is, assuming this:

```
(which-key-add-key-based-replacements
  "C-c"   "mode-specific")
(global-set-key (kbd "<f1>") 'which-key-show-top-level)
```

I would expect to see something other than "`prefix`" against `C-c` after pressing F1, but for some reason I don't, when the other keys relabelled in this manner show up fine.

**Comment by justbur** [comment]
Thanks. It should be fixed with 3c7ecc6. Please reopen if not.
