### ISSUE TITLE
Adding the package to elpa repository !

### ISSUE THREAD

**Issue by justinjk007** [justbur/emacs-which-key#167]
Hi @justbur we are doing a [project](https://github.com/josteink/emacs-oob-reboot) over at @josteink for helping out the new users by adding some most used and wanted default bindings. So we were wondering if you could take necessary actions to put your package up on elpa. Your awesome package seems like a wonderful help for beginners as well as a experienced user like me. \\Edit : typo

**Comment by justbur** [comment]
Hi, I'm happy to do this. I started to work on this for another package of mine, but got sidetracked. I have done the paperwork for copyright assignment, but I'm not sure how many of the contributors have. If you could find a source for what the rules are for contributors that would help.

**Comment by justinjk007** [comment]
@phillord , can you help us out, I have no experience submitting packages to elpa.

**Comment by phillord** [comment]
Sure. All "non-trivial" contributors need to have copyright assignment, which to a first point of reference means more than 11 lines (remaining in the current version). In your case, this means 5 people (including @justbur and assuming that the metadata in your repo is accurate -- i.e. that the code doesn't come from elsewhere). Some of them probably already have copyright assignment I am sure.

After this, you need commit rights to ELPA, and then you push everything up there (I normally do this as an external branch).

**Comment by justbur** [comment]
Thank you for the information @phillord. I'm not a professional programmer and am generally not too familiar with the legal stuff, so sorry for my ignorance. I was certainly inspired by guide-key but started from scratch more or less. There are a function or two I partially borrowed from another package. 

In terms of other contributors, I can ping them about their status. I'm assuming you're referring to @iqbalansari, @syohex, @tarsius and @cute-jumper. Have you all gone through the copyright assignment process yet?

**Comment by tarsius** [comment]
I have signed the copyright assignment for "Emacs" and hereby declare that going forward I consider `which-key` to be "part of Emacs".

**Comment by phillord** [comment]
@justbur No worries. If you have borrowed *verbatim* from a package, then whoever wrote that becomes an author. Again, this is only an issue *if* the code is still in the version that you are intending to publish into ELPA. Once or twice, I've had to change code to remove copyright. Pain but not too bad.

You might want to email emacs-devel to ask if you can include which-key on ELPA. For this, you'll need commit rights, so you need to register on savannah.gnu.org.

**Comment by cute-jumper** [comment]
Yep. I have also signed the copyright paper to FSF.

**Comment by iqbalansari** [comment]
I have also signed the copyright assignments.

**Comment by justbur** [comment]
@syohex I think I found you on the GNU copyright.list. Are you OK with me adding which-key to GNU ELPA?

**Comment by justinjk007** [comment]
So why is this not in elpa yet ?

**Comment by justbur** [comment]
I was waiting on @syohex, but it appears Syohei has submitted the copyright papers so I'm submitting it anyway. I'm not sure how long it will take to be approved.

**Comment by justinjk007** [comment]
Awesome

**Comment by justbur** [comment]
I just merged it into the elpa repo

**Comment by justinjk007** [comment]
Ahhh ..yes https://elpa.gnu.org/packages/which-key.html
