### ISSUE TITLE
Binding descriptions don't get updated for remapped keys

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#169]
Here's an example:

Here is my [config for `counsel`][1] where I choose to `remap` default bindings to equivalent commands by `counsel`.

In the below image, you see that config in the window on the top and the `which-key` interface showing the bindings with `C-h` prefix at the bottom.

Notice that as I chose to *specify* the binding to `C-h F`, `which-key` shows the description of that correctly as `counsel-faces`.

```el
       ("C-h F" . counsel-faces)       ;Overrides `Info-goto-emacs-command-node'
```
But I have chosen to `remap` the default binding of `describe-bindings` to `counsel-descbinds`. 

```el
       ([remap describe-bindings] . counsel-descbinds)
```

`which-key` still thinks that `C-h b` is bound to `describe-bindings` (see the image).

But when I do `C-h c C-h b`, it shows the binding as `counsel-descbinds` correctly.

*Following the same pattern, `which-key` is showing the original bindings instead of all the remapped ones.. see what `which-key` shows as bindings for all the remapped keys in the below `setup-counsel.el`.*

![image](https://cloud.githubusercontent.com/assets/3578197/26261559/a16fbc4a-3c9f-11e7-8f14-6a33eaf665ec.png)

[1]: https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-counsel.el

**Comment by justbur** [comment]
which-key doesn't know about remapped bindings, because they haven't been remapped yet :-). When you hit `C-h b` Emacs sees `describe-bindings` and then checks for any remappings, which are determined dynamically. 

Compare
```elisp
(lookup-key help-map "b") ;; => describe-bindings
(key-binding (kbd "C-h b")) ;; => counsel-descbinds
(key-binding (kbd "C-h b") nil t) ;; => describe-bindings
(describe-buffer-bindings (current-buffer)) ;; => (large output) with C-h b  describe-bindings
```
which-key uses the last function which is fast and written in C to find all of the current bindings. It takes care of determining which bindings are active from all of the maps, but like the examples show it doesn't handle remaps.

**Comment by kaushalmodi** [comment]
Thanks for the explanation. A workaround I believe is to specify the description in parallel to each remapping.

Should I close this issue?

**Comment by justbur** [comment]
Added an option to handle remaps in e8db06e

**Comment by kaushalmodi** [comment]
Works great! Thanks for this instant feature implementation! Also I don't think there's an extra noticeable delay when I set `which-key-compute-remaps` to `t`.. and now it show the *true* bindings :)
