### ISSUE TITLE
BUG: Error running timer `which-key/update': (range-error "ceiling" 1.0e+INF)

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#17]
With these settings:
```elisp
(setq which-key-popup-type 'side-window
      which-key-side-window-location 'right
      which-key-side-window-max-width 20) ; or other small value
```
The which-key buffer isn't displayed, and I get an error message in the minibuffer:
> Error running timer `which-key/update': (range-error "ceiling" 1.0e+INF)

This also happens when setting window location to `left`, but doesn't happen when using `top` or `bottom` and a small max height.

**Comment by justbur** [comment]
The number of calculated columns was 0. I now show a message if this happens and avoid the division by 0. The buffer will not be shown in this case. 

I'm not sure if you want to have a fallback for this scenario, but at least it doesn't throw an error.

**Comment by bmag** [comment]
If there isn't enough space, then there not much we can do about it. I believe using `user-error` here fits better than `message`, since this really is a user error (error is in user settings).

**Comment by justbur** [comment]
I don't know. I think I'd like to be able to have a small frame and just effectively deactivate which-key in those cases. An error could be too intrusive I think. Would you want which-key to throw an error if you resized the frame for a second and had debug-on-error on for example?

**Comment by bmag** [comment]
Good point. I don't have any strong preference this way or that way.

**Comment by justbur** [comment]
Let's just see if people get really confused
