### ISSUE TITLE
How to disable C-h for paging/help before the which-key buffer shows?

### ISSUE THREAD

**Issue by c02y** [justbur/emacs-which-key#172]
I got a key binding `C-h h` for a command, but sometimes I accidentally hit `C-h C-h` quickly and the which-key doesn't even show but there will be a line 

    Top-level bindings n -> next-page, p->previous-page, u->undo-key, h->help, a->abort

in the minibuffer, this is annoy. 

So how can disable C-h for paging the which-key **before** the which-key shows? I mean the two `C-h` are too close and there should be a delay between them.

**Comment by justbur** [comment]
Thanks, I pushed a partial fix for this. I decided to fall back on Emacs default behavior when `C-h` is pressed and the buffer isn't showing.
