### ISSUE TITLE
Would you like to setting "which-key-max-description-length" to a larger number

### ISSUE THREAD

**Issue by ReimuXMX** [justbur/emacs-which-key#174]
Hello, and sorry for my poor English.

I found that in many configurations,
Many commands exceed 27 characters in length.

So, would you like to consider setting this value to a larger number?

I know I can set it myself.
But I still want the defaults to change.

Thank you!

**Comment by justbur** [comment]
> I found that in many configurations,
Many commands exceed 27 characters in length.

I don't find that that's true. I think 27 works well in default emacs. Of course making it larger means that less commands can be shown, so it's not free.
