### ISSUE TITLE
How can I flip the page with the C-h prefix?

### ISSUE THREAD

**Issue by re-mx** [justbur/emacs-which-key#175]
Hello, and sorry for taking your time and my poor English.

My <kbd>C-h</kbd> prefix is shown as two pages under which-key.

But when I type <kbd>C-h</kbd> after <kbd>C-h</kbd> to flip the page, Emacs entered `help-for-help`.

So how can I filp? I do not want to change the default key binding.

Thank you.

**Comment by justbur** [comment]
The key bindings were changed at some point. The default is to go to the next page with `C-h C-n` or `C-h n`, the previous page with `C-h C-p` or `C-h p`, etc. See `which-key-C-h-map`. You're free to customize that keymap if you want different bindings.

**Comment by ReimuXMX** [comment]
Thank you.

**Comment by ReimuXMX** [comment]
Although I am sorry, but I have to reopen the issue.

My question is: "When I press <kbd>C-h</kbd>, how do I turn pages?"

<img width="1152" alt="1" src="https://user-images.githubusercontent.com/26828933/35200780-e1790ef0-ff4e-11e7-9368-0142194f8d3b.png">
You can see there are two pages

Then I pressed <kbd>C-h</kbd>:
<img width="1152" alt="2" src="https://user-images.githubusercontent.com/26828933/35200803-1a8e6078-ff4f-11e7-81d2-c4c7f2380764.png">

So how do I see the second page? Can only change binding?

Thank you.

**Comment by justbur** [comment]
You pressed `C-h C-h`. You need to press `C-h n` or `C-h C-n` to go to the next page.

**Comment by re-mx** [comment]
When I pressed <kbd>C-h n</kbd> or <kbd>C-h C-n</kbd>:
<img width="1152" alt="1" src="https://user-images.githubusercontent.com/26828933/35597519-e8097e3c-0659-11e8-9789-42b4216da825.png">
The 25.3 version will also show the same page.

**Comment by justbur** [comment]
What are your which-key settings?

**Comment by re-mx** [comment]
```
(which-key-mode)
(with-eval-after-load 'which-key
  (diminish 'which-key-mode)
  (which-key-setup-side-window-bottom))
```

`which-key` is installed from Melpa

**Comment by justbur** [comment]
Oh, I see what the problem is. Turning the page won't work if `C-h` is a bound key. This is on purpose, so that paging doesn't make any keys inaccessible. 

The key sequence `C-h C-h` is bound to a command, which is why you are getting this behavior. If you want to turn the page after `C-h` you need to unset `C-h C-h` like this

```elisp
(global-unset-key (kbd "C-h C-h"))
```

**Comment by re-mx** [comment]
Thanks. It works
