### ISSUE TITLE
when pop-up type is minibuffer, can't use C-h for paging

### ISSUE THREAD

**Issue by Csomnia** [justbur/emacs-which-key#179]
Hi:
    when i set pop-up type with side-window, default paging key (C-x) works great, but when I set pop-up type with minibuffer, I can't use C-h key to paging.

**Comment by justbur** [comment]
I never was able to get the paging commands to work well in the minibuffer. The side-window on the bottom (the default) is much more reliable. I'm tempted to remove the minibuffer functionality completely, but for now I added some notes to the README and docstrings. See 159f0f9b78753574a1892ae3e47c8c1938965ea9.
