### ISSUE TITLE
BUG: weird behavior with ace-jump-mode and avy

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#18]
When invoking command `ace-jump-mode` from package `ace-jump-mode`, or command `avy-goto-char` from package `avy`, I experience weird behavior for the side-window case and the frame case.

side-window case: invoking `ace-jump-mode` (or `avy-goto-char`) causes which-key buffer to be shown, but not updated (shows previous content). It doesn't prevent `ace-jump-mode` from working.

frame case: invoking `ace-jump-mode` (or `avy-goto-char`) causes an error message to appear in the minibuffer:
> Error running timer `which-key/update': (wrong-type-argument number-or-marker-p nil)

It doesn't prevent `ace-jump-mode` from working.

No problems with the minibuffer case.

**Comment by justbur** [comment]
Added a check that the key-binding doesn't return a symbol, which it does for `ace-jump-mode`. I'm not sure about `avy-goto-char`. Could you check that on your side?

A guess: Both of these command use `read-char` which is probably getting sent to `this-single-command-keys`, which is what I use to read the key sequence.

**Comment by justbur** [comment]
Checking for keymap now instead of the symbol. See #22

**Comment by bmag** [comment]
That fixed it :+1:
