### ISSUE TITLE
Custom string replacements only apply the first match.

### ISSUE THREAD

**Issue by it3ration** [justbur/emacs-which-key#180]
When adding custom string replacements, only the first match seems to be applied. For example, in the following code, I have two separate replacement rules, one to remove `paredit` prefixes, and the other to remove `hydra` prefixes. They both work fine if the other is removed but when both are present only the first one in `which-key-replacement-alist` is applied.

```elisp
(progn
  (push '((nil . "paredit-") . (nil . "p-"))
        which-key-replacement-alist)
  (push '((nil . "\\`hydra-.+/\\(.+\\)") . (nil . "\\1"))
        which-key-replacement-alist))))
```

This may be by design, but it would be nice if _every_ match was applied, not just the first match that succeeds.

**Comment by justbur** [comment]
That would be what `which-key-allow-multiple-replacements` is for. Set it to `t` to get the behavior you want.

**Comment by it3ration** [comment]
Ah, I wasn't aware of that variable, thank you so much!
