### ISSUE TITLE
FR - allow numeric argument after Control+h

### ISSUE THREAD

**Issue by pyluyten** [justbur/emacs-which-key#182]
After Control+h is pressed to allow viewing next page / previous page / abort, it would be cool to be able to input either - or [0-9] to impact digit-argument.

**Comment by justbur** [comment]
So `C-h 2 n` goes two pages forward in which-key or are you taking about being able to add an argument to the eventual command?

**Comment by pyluyten** [comment]
i mean being able to add an argument to an eventual command.
I think it is more comfortable in many cases to see the commands panel, then think "oh yes i will use that one, and need to add universal arg" than having to figure the whole process before.

Well actually in some cases it already works. But i think it is not really voluntarily because it is not advertised and is not 100% functional. For example the list of functions disappears ; also it is possible to add a one-digit number argument but not several digits ; an error is raised saying the key is not binded.

**Comment by justbur** [comment]
Try 1219622 

I only allow for a single arg for simplicity (and to see if it's useful). `C-x C-h 9 {` for example should have the same result as `M-9 C-x {`.

**Comment by pyluyten** [comment]
works perfectly here, it's very nice you added this. I let you close if you feel this issue done

**Comment by justbur** [comment]
Great
