### ISSUE TITLE
Docstrings?

### ISSUE THREAD

**Issue by steckerhalter** [justbur/emacs-which-key#185]
Am I missing something or is which-key not able to show docstrings? I know it's possible to add a description manually but that's not what I'm after. I don't want to know the function name but what it does and that's usually provided by the docstring. If not it can still fall back to displaying the function name. What do you think? I guess this could be a custom disabled by default.

**Comment by justbur** [comment]
Can you sketch out what you mean? I already show docstrings when you hover over the command with the mouse. Are you talking about showing them in the buffer in place of the command name?

**Comment by steckerhalter** [comment]
Yes, similar to what https://github.com/steckerhalter/discover-my-major does.

**Comment by justbur** [comment]
That helps. Yes, I can do that. I'm thinking of a custom variable to control what is displayed with options like "command name", "command and docstring", and "docstring only".

**Comment by steckerhalter** [comment]
Sounds great.

**Comment by justbur** [comment]
Try c71fbbbc3ec49bac4b73fe2700d633e3037c7ae4

I just put in a simple version for now. If you have suggestions for improvements let me know.

**Comment by steckerhalter** [comment]
Thanks, but now the option to show only the docstrings is missing :)

**Comment by steckerhalter** [comment]
Nice, I found some issue with my hydra:

![screenshot_2018-01-31_15-14-32](https://user-images.githubusercontent.com/3024024/35627578-353e464c-0691-11e8-99a7-28534eb8e4e5.png)

It seems to be taking the docstring the hydra itself?

**Comment by justbur** [comment]
Can you provide some code to reproduce that?

**Comment by steckerhalter** [comment]
```cl
(defhydra hydra-move (global-map "<f10>")
  ("n" next-line)
  ("p" previous-line)
  ("f" forward-char)
  ("b" backward-char)
  ("a" beginning-of-line)
  ("e" move-end-of-line)
  ("v" scroll-up-command)
  ;; Converting M-v to V here by analogy.
  ("V" scroll-down-command)
  ("l" recenter-top-bottom))
```

**Comment by justbur** [comment]
Yes, it's something hydra is doing. From `(documentation 'hydra-move/next-line)`, I get

```
"Create a hydra with a \"<f10>\" body and the heads:

\"n\":    ‘next-line’,
\"p\":    ‘previous-line’,
\"f\":    ‘forward-char’,
\"b\":    ‘backward-char’,
\"a\":    ‘beginning-of-line’,
\"e\":    ‘move-end-of-line’,
\"v\":    ‘scroll-up-command’,
\"V\":    ‘scroll-down-command’,
\"l\":    ‘recenter-top-bottom’

The body can be accessed via ‘hydra-move/body’.

Call the head: ‘next-line’."
```

**Comment by steckerhalter** [comment]
Ok, good for now I guess. Thanks a lot.

**Comment by justbur** [comment]
@steckerhalter FYI https://github.com/abo-abo/hydra/pull/281

**Comment by steckerhalter** [comment]
thanks
