### ISSUE TITLE
(wrong type argument strinp nil) if binding is removed by replacement

### ISSUE THREAD

**Issue by Szunti** [justbur/emacs-which-key#186]
In c71fbbbc3ec49bac4b73fe2700d633e3037c7ae4 which-key--propertize-description is called without first checking if key-binding is nil

**Comment by bmag** [comment]
Some backtraces available over at https://github.com/syl20bnr/spacemacs/issues/10284.

**Comment by justbur** [comment]
Thanks. Please test

**Comment by justbur** [comment]
Whoops, I misread the comments. Hold on

**Comment by Szunti** [comment]
Thank you, works now without problems.
