### ISSUE TITLE
Howto make which-key use a wider portion of the frame? (here: 2-columns)

### ISSUE THREAD

**Issue by triklsbg** [justbur/emacs-which-key#187]
![one-col-which-key-screenshot_20180216_115410](https://user-images.githubusercontent.com/3647083/36304770-22f21806-1311-11e8-9650-f54b794a4b2b.png)
Widening the frame (what i do not want!) gives me 2 columns.
Thanks!

**Comment by justbur** [comment]
Have you tried using `which-key-side-window-max-width`?

**Comment by triklsbg** [comment]
A big value like 0.8 0.9 helped to display 2 cols.
