### ISSUE TITLE
projectile key options are not shown in the request

### ISSUE THREAD

**Issue by mambolevis** [justbur/emacs-which-key#192]
Hi, 

I am using the following configuration in projectile:
```
(use-package projectile
  :ensure t
  :init
  (setq projectile-completion-system 'ivy)
  :bind-keymap
  ("C-c C-p" . projectile-command-map)
  :config
  (projectile-mode 1))
```
When I press `C-c C-p` projectile is activated but the key options are not shown.
If I then press `C-c C-p ` the minibuffer shows projectile key options as expected.

Any suggestion?
Thanks

**Comment by justbur** [comment]
I believe any issue you're seeing here is due to the way `:bind-keymap` is implemented in `use-package`. I'm not familiar with how this works, but it is certainly non-standard emacs behavior to autoload a package in the middle of a key sequence.

**Comment by justbur** [comment]
Found the issue: https://github.com/jwiegley/use-package/pull/686
