### ISSUE TITLE
Heads-up : window-configuration-change-hook is deprecated with Emacs 26

### ISSUE THREAD

**Issue by vxid** [justbur/emacs-which-key#193]
The `window-configuration-change-hook` is deprecated with Emacs 26. According to the changelog of v26:

> Resizing a frame no longer runs 'window-configuration-change-hook'. 'window-size-change-functions' should be used instead.

On Emacs 26, resizing the window while the which-key buffer is visible does not resize it.

I don't know how hard it would be to adapt `which-key--hide-popup-on-frame-size-change` but I do not think I have the elisp skills do do it myself.

**Comment by justbur** [comment]
Thanks! Should be fixed now
