### ISSUE TITLE
disable mode-line in which-key

### ISSUE THREAD

**Issue by jbharat** [justbur/emacs-which-key#194]
This is not a bug as such. I like to add fringe width to my buffers. 

If I add
```
  (setq-default left-fringe-width 15)
  (setq-default right-fringe-width 15)
```
or
```
  (add-to-list 'default-frame-alist '(internal-border-width . 4))
```
the mode-line in which-key overlaps the keys as shown below
<img width="923" alt="screen shot 2018-08-11 at 1 59 23 pm" src="https://user-images.githubusercontent.com/6837979/43987996-e66446be-9d6e-11e8-96a0-fc48808ecb14.png">
<img width="877" alt="screen shot 2018-08-11 at 2 03 05 pm" src="https://user-images.githubusercontent.com/6837979/43988008-5970c27c-9d6f-11e8-93be-d8c6581e1b3c.png">

To get around this I tried adding
```
(add-hook 'which-key-init-buffer-hook (lambda () (setq-local mode-line-format nil)))
```
This works initially but then I get the same mode-line overlapping again after some time.

Is there a way to disable the mode-line in which-key or any other fix?

Using spacemacs develop branch.

**Comment by jbharat** [comment]
Sorry. It was my mistake. I was trying to give a margin to buffer but was trying to achieve it using fringes. Setting right-margin-width and left-margin-width solved it. Now I don't need to disable the mode-line.

**Comment by jbharat** [comment]
I have added `(setq-default left-margin-width 1 right-margin-width 1)`.
Initially, mode-line renders fine, but later the same problem of mode-line overlapping occurs again.

**Comment by jbharat** [comment]
Figured out the cause. Modeline starts to overlap after callings spacemacs's `dotspacemacs/sync-configuration-layers(SPC f e R)`. I will raise this bug in spacemacs. Sorry again.

**Comment by thornjad** [comment]
Link to the issue @jbharat created: syl20bnr/spacemacs#11165
