### ISSUE TITLE
Do I need to explicitly call (which-key-setup-side-window-bottom)?

### ISSUE THREAD

**Issue by re-mx** [justbur/emacs-which-key#195]
Hello, and forgive my poor English...

If I want to use the default settings, do I need to explicitly call `(which-key-setup-side-window-bottom)`?

Like this:
```elisp
(which-key-mode)
(with-eval-after-load 'which-key
  (which-key-setup-side-window-bottom))
```

Thank you.

**Comment by justbur** [comment]
No, you should only need the first line to get the default settings.

**Comment by re-mx** [comment]
Thanks.
