### ISSUE TITLE
which-key-show-major-mode doesn't appear to exist?

### ISSUE THREAD

**Issue by TyOverby** [justbur/emacs-which-key#196]
I'm in a major mode that I want to learn more about the key-bindings, but `which-key-show-major-mode` doesn't show up in my `M-x` list

**Comment by justbur** [comment]
It's not bound to a key by default. You either need to execute the command using `M-x` or bind it in your config file with `define-key` or a function of that sort ([emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Commands.html#Key-Binding-Commands))

**Comment by TyOverby** [comment]
Oh, my mistake, I type "C-x" instead of "M-x".  When I use "M-x" to pull up a list of commands, `which-key-show-major-mode` isn't one of them.

**Comment by justbur** [comment]
It should be. Are you not seeing any commands from which-key, or just that one?

**Comment by TyOverby** [comment]
It looks like `which-key-show-major-mode` is the only one that is missing.  Is there a way of checking to see which version of `which-key` I have installed?  Maybe I'm on an old version?

**Comment by TyOverby** [comment]
ah, I thought I was loading it off of melpa, but I just checked and it was a local cache.  The version is indeed out of date.
