### ISSUE TITLE
Wrong type argument: which-key--pages, nil

### ISSUE THREAD

**Issue by phil-s** [justbur/emacs-which-key#197]
With current master commit c938bbf8d4b506d8a16bedf0059703236ce05a50 and Emacs 26.1

    emacs -Q -l which-key.el -f which-key-mode

Type, e.g.:  `C-x C-h` without pausing to let which-key do its thing.

If you *do* allow which-key to do its thing, then the issue will not subsequently occur.

    Debugger entered--Lisp error: (wrong-type-argument which-key--pages nil)
      signal(wrong-type-argument (which-key--pages nil))
      (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj)))
      (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))
      (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9)))
      (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face)
      (progn (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face))
      (if (string-equal prefix-keys "") (progn (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face)))
      (concat (if (string-equal prefix-keys "") (progn (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face))) full-prefix (which-key--propertize (substitute-command-keys (concat " \\<which-key-C-h-map>" " \\[which-key-show-next-page-cycle]" which-key-separator "next-page," " \\[which-key-show-previous-page-cycle]" which-key-separator "previous-page," " \\[which-key-undo-key]" which-key-separator "undo-key," " \\[which-key-toggle-docstrings]" which-key-separator "toggle-docstrings," " \\[which-key-show-standard-help]" which-key-separator "help," " \\[which-key-abort]" which-key-separator "abort" " 1..9" which-key-separator "digit-arg")) 'face 'which-key-note-face))
      (let* ((prefix-keys (which-key--current-key-string)) (full-prefix (which-key--full-prefix prefix-keys current-prefix-arg t)) (prompt (concat (if (string-equal prefix-keys "") (progn (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face))) full-prefix (which-key--propertize (substitute-command-keys (concat " \\<which-key-C-h-map>" " \\[which-key-show-next-page-cycle]" which-key-separator "next-page," " \\[which-key-show-previous-page-cycle]" which-key-separator "previous-page," " \\[which-key-undo-key]" which-key-separator "undo-key," " \\[which-key-toggle-docstrings]" which-key-separator "toggle-docstrings," " \\[which-key-show-standard-help]" which-key-separator "help," " \\[which-key-abort]" which-key-separator "abort" " 1..9" which-key-separator "digit-arg")) 'face 'which-key-note-face))) (key (string (read-key prompt))) (cmd (lookup-key which-key-C-h-map key)) (which-key-inhibit t)) (if cmd (funcall cmd key) (which-key-turn-page 0)))
      (if (not (which-key--popup-showing-p)) (which-key-show-standard-help) (let* ((prefix-keys (which-key--current-key-string)) (full-prefix (which-key--full-prefix prefix-keys current-prefix-arg t)) (prompt (concat (if (string-equal prefix-keys "") (progn (which-key--propertize (concat " " (progn (or (and (memq (type-of which-key--pages-obj) cl-struct-which-key--pages-tags) t) (signal 'wrong-type-argument (list 'which-key--pages which-key--pages-obj))) (aref which-key--pages-obj 9))) 'face 'which-key-note-face))) full-prefix (which-key--propertize (substitute-command-keys (concat " \\<which-key-C-h-map>" " \\[which-key-show-next-page-cycle]" which-key-separator "next-page," " \\[which-key-show-previous-page-cycle]" which-key-separator "previous-page," " \\[which-key-undo-key]" which-key-separator "undo-key," " \\[which-key-toggle-docstrings]" which-key-separator "toggle-docstrings," " \\[which-key-show-standard-help]" which-key-separator "help," " \\[which-key-abort]" which-key-separator "abort" " 1..9" which-key-separator "digit-arg")) 'face 'which-key-note-face))) (key (string (read-key prompt))) (cmd (lookup-key which-key-C-h-map key)) (which-key-inhibit t)) (if cmd (funcall cmd key) (which-key-turn-page 0))))
      which-key-C-h-dispatch()
      funcall-interactively(which-key-C-h-dispatch)
      call-interactively(which-key-C-h-dispatch nil nil)
      command-execute(which-key-C-h-dispatch)

**Comment by justbur** [comment]
Thanks! Should be fixed with ace569b, but feel free to reopen if not.

**Comment by phil-s** [comment]
Thank you for the fix.  I can confirm this prevents the error, but after testing I've raised a related issue #198.

**Comment by phil-s** [comment]
Thank you for the fix.  I can confirm this prevents the error, but after testing I've raised a related issue #198.
