### ISSUE TITLE
Not capturing the prefix key.  "Key translations Starting With :"

### ISSUE THREAD

**Issue by phil-s** [justbur/emacs-which-key#198]
If I type `C-x C-h` then the help buffer is titled `Key translations Starting With :` and shows me *all* bindings, similarly to `C-h b`.

Debugging `which-key-show-standard-help`, I'm seeing the following behaviour:

* I type `C-x C-h`
* `which-key-C-h-dispatch` is called
* `(if (not (which-key--popup-showing-p))` is true, so
* `which-key-show-standard-help` is called, in which
* `(eq which-key--prefix-help-cmd-backup 'describe-prefix-bindings)` is true, so
*  `(describe-bindings (kbd (which-key--current-key-string)))` is called, but
* `(which-key--current-key-string)` is returning `""` rather than a value based on `C-x`.

**Comment by justbur** [comment]
Thank you for the detailed report. Please try 43e3e3d
