### ISSUE TITLE
TODO: smarter calculation of max dimensions

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#20]
Currently, `which-key/side-window-max-dimensions` and `which-key/frame-max-dimensions` don't take into account the actual layout of the selected frame. When the available size in the frame is smaller than the user-defined max height and width, this could cause bugs.
This is probably more important for the side-window case than the frame case.

**Comment by justbur** [comment]
What do you think about making the user settings specify a fraction of the current frame for the side-window case? That might be the more reasonable way to do it. Then the buffer just wouldn't show if the frame is too small, instead of maybe taking over the whole frame.

**Comment by bmag** [comment]
We could and should support user settings that specify either a fraction or a whole number of lines/columns. I've done something similar before, it's not hard.

Why do you say that the buffer may take over the whole frame? Please explain.

I partially disagree about not popping the window if the frame is too small. I consider the following to be a reasonable logic:
- user specifies a max size through a user option (customizable variable). Size can be a fraction or a whole number.
- `which-key/side-window-max-dimensions` considers the user's settings and the current layout of the screen, then returns the max size that is available. If the user-defined size can't fit in the current layout, then the function returns the max size that does fit. This is the step that the issue refers to.
- which-key tries to populate the buffer with as many keys as possible, without exceeding the size calculated by `which-key/side-window-max-dimensions`. If there isn't enough space for any key, stop here and don't display the buffer.
- the actual size of the which-key buffer is passed to `which-key/show-popup`, which displays the buffer. That size can be smaller than the size returned by `which-key/side-window-max-dimensions`. There shouldn't be any problem in displaying the buffer, since we already know that there will be enough space.

When I wrote "smarter calculation", I meant that I need to implement the behavior I described for `which-key/side-window-max-dimensions`. I will implement it this weekend.

**Comment by bmag** [comment]
I think this TODO is not necessary anymore, so I'm closing it.
