### ISSUE TITLE
filtering which-key-show-top-level

### ISSUE THREAD

**Issue by tim042849** [justbur/emacs-which-key#200]
Evil and which-key have given me a new lease on life for emacs. Kudos to both developers.
I recently discovered which-key-show-top-level and now would like to be able to filter it. 
On my version of which-key that function calls `which-key--create-buffer-and-show with only the
`prefix-title argument set. I would like to see an example of of how to write a filter function that would collect a subset of top-level bindings, such as F(n) bindings or those combined with the Control key. 
I've written a lot of very basic elisp functions, so I would just need a bit of a start. Thanks.

**Comment by kenoh** [comment]
Something like this works for me for filtering over function names:
```emacs-lisp
(defun k/which-key-show-top-level (filter)
  (interactive "sFilter: ")
  (which-key--create-buffer-and-show nil nil (lambda (x) (s-matches? filter (cdr x)))))
```
Just change `cdr` to `car` to filter over keybindings.

**Comment by tim042849** [comment]
Thank you kenoh, your comment is very helpful.

I have written the following:

```
(defun tj-which-key-starts-with (filter)
  "Filter over keybindings. Argument should match 
the beginning of a string representation of the binding."
  (interactive "sFilter: ")
  (which-key--create-buffer-and-show
   nil nil (lambda (x)
         (s-matches? filter (car x) 0))))
```

It does not appear that the optional START argument to 's-matches
is being processed as I would expect it.

If I provide "F" as the 'filter argument the buffer results will
display not just the bindings beginning with "f", but any binding
with a embedded "f". I had assumed that the '0' as a START index
should filter only instances where the binding startwith an "f".
