### ISSUE TITLE
which-key-idle-delay doesn't work at all

### ISSUE THREAD

**Issue by c02y** [justbur/emacs-which-key#206]
Setting `which-key-idle-delay` doesn't work for me at all, no matter what its value is, like 0, 0.1, 2.0, 5.0, the time of the which-key window popup is the same, around 2s which I cannot tolerate.

Here is all my config of which-key
~~~
(which-key-mode)
(unbind-key "C-h" help-map)
(which-key-setup-side-window-bottom)
(setq which-key-use-C-h-for-paging nil
      which-key-special-keys nil
      which-key-sort-order 'which-key-description-order
      which-key-show-remaining-keys t
      which-key-max-description-length 35)
(setq which-key-highlighted-command-list
          '("helm\\|toggle\\|projectile\\|describe"
                ("\\(^cscope\\)\\|\\(^ggtags\\)" . warning)
                ("register" . success)
                ("rectangle" . error)
                ("help\\|emacs\\|bookmarks" . highlight)
                ))
~~~
FYI:

Emacs 26.1 in terminal

Ubuntu 16.04 64bit LTS

**Comment by justbur** [comment]
I don't see where you have it in your setup code, but this value needs to be set before the mode is activated. I thought this was in the docstring, but it wasn't so I just added a note.

**Comment by c02y** [comment]
Thanks, it works, and you should mention it in README.
