### ISSUE TITLE
Which-key buffer content to a regular buffer

### ISSUE THREAD

**Issue by agzam** [justbur/emacs-which-key#209]
Is it possible to copy entire content of the which-key buffer into a regular buffer?
Use case for this:
You run `which-key-show-top-level`, toggle docstrings - there's a lot of stuff. I'd like to study it more, but which-key buffer is not persistent - it disappears easily.

**Comment by justbur** [comment]
Try `which-key-dump-bindings` in 77586e6

**Comment by agzam** [comment]
Holy mother of meta-key, this is so awesome! Thank you @justbur from the bottom of my heart!
