### ISSUE TITLE
[Feature] Support posframe as display type

### ISSUE THREAD

**Issue by cslux** [justbur/emacs-which-key#211]
`which-key` should support [posframe](https://github.com/tumashu/posframe) as display type.

**Comment by justbur** [comment]
What about https://github.com/yanghaoxie/which-key-posframe?

**Comment by cslux** [comment]
Whoops 😅.

Thanks Justin!



On May 22, 2019 1:35:40 PM UTC, Justin Burkett <notifications@github.com> wrote:
>What about https://github.com/yanghaoxie/which-key-posframe?

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com
