### ISSUE TITLE
[FEATURE] Add a persistent mode

### ISSUE THREAD

**Issue by billywade** [justbur/emacs-which-key#213]
It would be cool if I could have a persistent buffer that can show either all major-mode commands or all useful general commands and I could toggle them with a keybind. 

Whenever a command is actually used, it would narrow like normal, and after the command is executed, it would go back to the original command list, but never closing unless I instructed it to.

**Comment by justbur** [comment]
Currently, `which-key-show-major-mode` will popup a buffer with major mode commands. It hides on the next command, but you could override that. Would there then be two which-key buffers (one persistent one and one that pops up normally)? 

This sounds more like a [hydra](https://github.com/abo-abo/hydra) to me, to be honest.

**Comment by billywade** [comment]
It would only be one buffer at a time, just toggled between the persistent and nonpersistent. How could I override on the hiding on next command?

Hydra does the persistence thing, but it looks like it's more about making new binds rather than discovering existing ones. I like my modal setup, and your package helps me figure it out better. 

I'd just like to have `which-key-show-major-mode` up when I'm in insert mode and `which-key-show-top-level` in command mode, which I figured I'd actually bind to my insert and command mode activation bindings on my end. It would narrow normally, and at the end of the command bring up the buffer again.

**Comment by justbur** [comment]
ok, try this to start

```elisp
(remove-hook 'pre-command-hook 'which-key--hide-popup)
(add-hook 'evil-insert-state-entry-hook 'which-key-show-major-mode)
(add-hook 'evil-normal-state-entry-hook 'which-key-show-top-level)
```

It may need some tweaking, but this is a starting point.

**Comment by billywade** [comment]
Great, so right now it has the persistence, but it'll only show major mode keys, never changing when I activate command mode. I had to tweak it a little because I'm using xah instead of evil, so here's what I have so far:

```
(remove-hook 'pre-command-hook 'which-key--hide-popup)
(add-hook 'xah-fly-insert-mode-activate-hook 'which-key-show-major-mode)
(add-hook 'xah-fly-command-mode-activate-hook 'which-key-show-top-level)
```

**Comment by billywade** [comment]
Actually, you already answered my initial question, how to add a persistent mode: the `(remove-hook 'pre-command-hook 'which-key--hide-popup)`. So I'll close the actual issue, although if you're willing it'd still help me out to figure this out more.

**Comment by justbur** [comment]
You mean the `which-key-show-top-level` call never occurs?

**Comment by billywade** [comment]
Yeah, exactly.

**Comment by justbur** [comment]
I just tried again with evil, and it works for me. You can test it with `M-x which-key-show-top-level RET`. If that works, it might be an issue with the hook not firing when it's supposed to.

**Comment by billywade** [comment]
Yeah, I can run it via `M-x` just fine. How would I go about debugging the hook?

**Comment by justbur** [comment]
Just took a quick look at xah fly keys. There appears to be two ways to activate command mode, one runs the hook in question and one doesn't. First make sure you're running the right command. I think the default is to run the one without the hook (not sure why).

**Comment by billywade** [comment]
huh, changing it to `(add-hook 'xah-fly-command-mode-activate-no-hook 'which-key-show-top-level)` doesn't change anything.

**Comment by justbur** [comment]
It depends on what command you execute to go from insert mode to command mode. Based on the defaults for that package, I think you want this (after loading `xah-fly-keys`)

```elisp
(define-key xah-fly-key-map (kbd "M-SPC") 'xah-fly-command-mode-activate)
```

The default is to use the function `xah-fly-command-mode-activate-no-hook` which doesn't run the hook in question.

**Comment by billywade** [comment]
So should I try `xah-fly-command-mode-activate`? It isn't working, either.

**Comment by justbur** [comment]
I'm not sure what to say then, because I'm not familiar with that package. As far as I can tell, there doesn't seem to be anything broken on the which-key side

**Comment by billywade** [comment]
Fair enough. I'll ask on reddit and @ xah about it and see what they have to say. Thanks!

**Comment by jjzmajic** [comment]
https://gitlab.com/jjzmajic/wk-hydra

**Comment by justbur** [comment]
@jjzmajic Interesting, thanks

**Comment by jjzmajic** [comment]
The way I'm doing it right now is kinda hacky. Some internal calls to `which-key--hide-popup` can't be disabled by removing it from `pre-command-hook`. You mind If I submit a small PR with a config variable to make it a little cleaner? As far as end-bed user is concerned it works fine as-is, but still...

**Comment by billywade** [comment]
@jjzmajic so is this a package that functionally does what I'm looking for?

**Comment by jjzmajic** [comment]
@billywade yessir

**Comment by billywade** [comment]
Sweeeeeet. Is it in Melpa?

**Comment by jjzmajic** [comment]
Unfortunately not.. Realized I wasn't the only one who had the thought when I saw this issue so I wrote it yesterday. I'll get to it soon, but since I switched to straight I got lazy about these things

**Comment by jjzmajic** [comment]
@billywade I'll try and make PR tomorrow and I'll let you know when it's up.
@justbur, forgot to tag you.. How do you feel about that PR?

**Comment by billywade** [comment]
Thanks boss!

**Comment by jjzmajic** [comment]
@billywade the package is now here: https://gitlab.com/jjzmajic/hercules.el

I also submitted a PR to MELPA. I'll keep you posted.

**Comment by justbur** [comment]
@jjzmajic Yes, happy to look at it.

**Comment by jjzmajic** [comment]
Great! https://github.com/justbur/emacs-which-key/pull/216

**Comment by treymerkley** [comment]
@jjzmajic I just installed it. Soooo excited. So how do I go about setting it up for what I'm looking for here?
