### ISSUE TITLE
Side window resize changes frame layout

### ISSUE THREAD

**Issue by matthias-margush** [justbur/emacs-which-key#214]
Hi. My emacs plugin ([spacebar](https://github.com/matthias-margush/spacebar)) creates a side-window at the top of the frame with a fixed height.

`emacs-which-key` seems to resize the frame windows when `which-key-popup-type` is set to `side-window`. 

A quick way to reproduce my issue is to eval this:
```emacs-lisp
(display-buffer-in-side-window
 (current-buffer)
 '((side . top)
   (slot . 0)
   (window-height . 2)
   (preserve-size . (nil .t))
   (left-margin-width . 0)
   (right-margin-width . 0)
   (size-fixed . t)
   (window-parameters . ((no-other-window . t)
                         (no-delete-other-windows . t)))))
```

Then run a which-key sequence that has an initialize size that shrinks, with a pause between each key. (In spacemacs, I can do this with "SPC h k".) You should see the side-window at the top of the frame grow each time you do this.

This is as far as I've gotten. I'm curious if there is something I can do in my code, or if this is an emacs bug? (I'm also seeing this behavior in other plugins that use side-frames for transient interactions, like magit.)

A change like this in which-key solves the problem (as does switching the popup type to minibuffer or frame):

```
modified   which-key.el
@@ -1170,7 +1170,8 @@ call signature in different emacs versions"
       (delete-windows-on which-key--buffer)
       (display-buffer-in-side-window which-key--buffer alist))
      ((get-buffer-window which-key--buffer)
-      (display-buffer-reuse-window which-key--buffer alist))
+      (delete-windows-on which-key--buffer)
+      (display-buffer-in-side-window which-key--buffer alist))
      (t
       (display-buffer-in-side-window which-key--buffer alist)))))
```

**Comment by justbur** [comment]
I tried your instructions, but I'm not sure what I'm looking for (and I didn't notice anything obvious). In other words, I'm not sure I understand what you mean here

> Then run a which-key sequence that has an initialize size that shrinks, with a pause between each key. (In spacemacs, I can do this with "SPC h k".) You should see the side-window at the top of the frame grow each time you do this.

**Comment by matthias-margush** [comment]
I was able to work around the resizing by registering a hook when my window size changes - and [changing it back](https://github.com/matthias-margush/spacebar/blob/master/spacebar.el#L227-L236). It does seem strange - I would have expected the side window `size-fixed` and `preserve-size` attributes of my side window to provide it a fixed size. This workaround solves it for me, for now though.
