### ISSUE TITLE
Use which-key as a minor mode hook

### ISSUE THREAD

**Issue by Ergus** [justbur/emacs-which-key#215]
Hi I am doing some work for the package 'composable' and we want to add some support to use which-key.

composable-mode is activated when the user press a keybind (Like M-w), the mode has some keybindings defined in the local mode.

When the user press any of those the mode makes something and exists.

My initial idea was to add this lines:

```
  (which-key--show-keymap (symbol-name composable-mode)
			(cdr (assq composable-mode minor-mode-map-alist)))
```

when activating the minor mode. The completion in this way is good enough, but it forces to press the binding one extra time now to deactivate which-key first. And there is not delay timer.

Please is there a better way to do this? Or could you make a suggestion to know how to fix this two issues propperly?

**Comment by justbur** [comment]
It would help me if you could give steps to reproduce the problem and then explain what you want to happen. I'm not familiar with that package.

**Comment by Ergus** [comment]
Hi: 
Sorry for the delay.

I don't consider it as a which-key problem, just that I am probably doing something wrong in my code.

Suppose that I have a minor-mode that defines a keymap. But it is activated when pressing some binding. (Similar to isearch-mode somehow) and then it deactivates after some steps.
If I add a call to which-key--show-keymap (for example with a hook to isearch-mode); then after isearch (C-s) is pressed I expect to see the which-key window showing the local bindings of isearch-mode (ej: M-s: prefix M-e: edit C-r isearch-backward RET: isearch-exit)

The issue now is actually that in this way if I press RET once, it will exit which-key (not isearch), and I will need and extra RET to exit isearch. 

What do you suggest?

**Comment by justbur** [comment]
I just merged a PR that might help here. Try this (I threw it together with minimal testing):

```elisp
(defun wk-isearch-enter ()
  (setq which-key-persistent-popup t)
  (which-key-show-keymap 'isearch-mode-map t))

(defun wk-isearch-exit ()
  (setq which-key-persistent-popup nil)
  (which-key--hide-popup))

(add-hook 'isearch-mode-hook 'wk-isearch-enter)
(add-hook 'isearch-mode-end-hook 'wk-isearch-exit)
```

You'll need the latest commit for this to work (da2e093e916bf9ae7512c104512b92eca8fb224e).

**Comment by Ergus** [comment]
Hi justbur:

Very thanks for the  changes. It works like a charm. Now I have it in some modes I can't remember the bindings ;p

Best Regards,
Ergus
