### ISSUE TITLE
symbol's function definition is void: which-key-add-key-based-replacement

### ISSUE THREAD

**Issue by taigacute** [justbur/emacs-which-key#217]
Hi, i got this error when i open emacs.   i cached the load-path and disabled (package-initialize) .so  what i missed with which-key . i wirte a funtion to load key and desc
```lisp
(defun boom--keybind-register (key desc &optional modes)
   (if modes
      (dolist (mode modes)
        (which-key-add-major-mode-key-based-replacements mode key desc))
    (which-key-add-key-based-replacements key desc)))
```
I can use which-key but got error 
![image](https://user-images.githubusercontent.com/41671631/63640950-fe1c1680-c6d8-11e9-8e90-668cb8369d70.png)

**Comment by shamansir** [comment]
I got the same issue today.
