### ISSUE TITLE
Binding keys for faster paging

### ISSUE THREAD

**Issue by clemera** [justbur/emacs-which-key#218]
Hi there,

I would like to be able to flip pages with single keystrokes. For example `[` and `]` instead of `C-h p` and `C-h n`. How could I achieve that? I already tried several things without success (macros, key translation). I'm okay with a hacky solution for my config, too ;)

**Comment by clemera** [comment]
I came up with this ridiculous hack (it seems to work but hopefully there is a better way?):

    (define-advice which-key--show-page (:around (f &rest args remap-hack))
      (define-key key-translation-map "[" (kbd "C-h p"))
      (define-key key-translation-map "]" (kbd "C-h n"))
      (apply f args))

    (define-advice which-key--hide-popup (:around (f &rest args) remap-hack)
      (define-key key-translation-map "[" nil)
      (define-key key-translation-map "]" nil)
      (apply f args))

    (advice-add 'which-key-C-h-dispatch :around
                (defun which-key-hack (f &rest _args)
                  (cl-letf (((symbol-function #'read-key)
                             (lambda (&rest _)
                               (if (eq last-input-event ?\[)
                                   ?p
                                 ?n))))
                    (apply f _args))))

**Comment by clemera** [comment]
Here is a ridiculous hack that works (hopefully there is a better way?):

    (define-advice which-key--show-page (:around (f &rest args remap-hack))
      (define-key key-translation-map "[" (kbd "C-h"))
      (define-key key-translation-map "]" (kbd "C-h"))
      (apply f args))

    (define-advice which-key--hide-popup (:around (f &rest args) remap-hack)
      (define-key key-translation-map "[" nil)
      (define-key key-translation-map "]" nil)
      (apply f args))

    (advice-add 'which-key-C-h-dispatch :around
                (defun which-key-hack (f &rest _args remap-hack)
                  (cl-letf* ((orig (symbol-function #'read-key))
                             ((symbol-function #'read-key)
                              (lambda (&rest _)
                                (cond ((eq last-input-event ?\[)
                                       ?p)
                                      ((eq last-input-event ?\])
                                       ?n)
                                      (t
                                       (funcall orig))))))
                    (apply f _args))))

**Comment by justbur** [comment]
That is pretty ridiculous :), but you gave me an idea. Maybe you'll like this better

``` elisp
(define-key key-translation-map "]" (lambda (_)
                                      (if (which-key--popup-showing-p)
                                          (progn
                                            (setq unread-command-events (list ?n))
                                            "\C-h")
                                        "]")))

(define-key key-translation-map "[" (lambda (_)
                                      (if (which-key--popup-showing-p)
                                          (progn
                                            (setq unread-command-events (list ?p))
                                            "\C-h")
                                        "[")))
```

**Comment by clemera** [comment]
Thanks, that's better! BTW I have added a completing-read command to `which-key-C-h-map` which allows selecting one of the candidates via completion. If you are interested I will clean it up and make a PR.

**Comment by clemera** [comment]
What do you mean by optional? You have to invoke it via `C-h <key>` when the popup is showing so you only get it on demand.

**Comment by clemera** [comment]
After thinking about it, because that functionality is useful outside of which-key I will probably make a standalone package for it. One could than use it with `which-key` but also use it as `prefix-help-command`:

    (setq prefix-help-command 'counsel-key-prefix-help)
    (define-key which-key-C-h-map "h" 'counsel-key-prefix-help)

But currently I use internal `which-key` functions to get the bindings, so either I have to make `which-key` a dependency or implement that functionality again. Currently I'm using this to get the bindings:

    (mapcar #'caddr (which-key--get-bindings nil map nil t))

**Comment by clemera** [comment]
Thinking again, after all it would make sense if `which-key` would provide a completion command for `prefix-help-command` so I will make a PR the next days and then you may decide ;)

**Comment by MoHKale** [comment]
I'm curious, did you ever make that pull request @clemera?

**Comment by clemera** [comment]
No, I didn't, after all I was not sure if it should be included, but I blogged about it [here](https://with-emacs.com/posts/ui-hacks/prefix-command-completion/).

**Comment by MoHKale** [comment]
Thnx, looks pretty cool :)
