### ISSUE TITLE
BUG: which-key not showing

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#22]
With vanilla emacs, which-key does not show at all. Works fine with spacemacs, though.

Steps to reproduce:
1. emacs -Q -l path/to/s.el -l path/to/which-key.el
2. M-x which-key-mode
3. C-x
Expected result: which-key shown in the minibuffer
Actual result: which-key isn't shown at all

Probably introduced by some recent change.
Tried emacs 24.3, 24.5 and 25, same behavior. On spacemacs I don't experience this bug - which-key works as expected.

**Comment by justbur** [comment]
Can you try it now? 

I check directly for the key-binding pointing to a keymap now. In vanilla emacs, this-single-command-keys returns a symbol so the bug was in the logic for the update function

**Comment by bmag** [comment]
Works!
