### ISSUE TITLE
Can I enable which-key only for a single mode?

### ISSUE THREAD

**Issue by mrbig033** [justbur/emacs-which-key#221]
# My Environment

- OS: MX Linux 18
- Result of `$ uname -r`: 4.19.0-5-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- i3 version 4.13
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- GNU Emacs 27.0.50
- [~/.emacs.d](https://github.com/mrbig033/emacs)

# Issue

I want for `which-key` to only work on `info-mode`, and **not at all** in any other mode. How can I do this?

**Comment by justbur** [comment]
Not exactly. `which-key-mode` is a global mode. You could turn it on in `info-mode-hook`, but then there is not a clear way to turn it off. 

You might try [Manual Activation](https://github.com/justbur/emacs-which-key#manual-activation), and only use it when needed.

**Comment by mrbig033** [comment]
Okay, then. Than may I suggest adding this feature? I don't need `which-key` for anything else. Thanks.

**Comment by justbur** [comment]
Here's a hack that should work.

```elisp
(setq which-key-inhibit t)
(add-hook 'Info-mode-hook (lambda () (setq-local which-key-inhibit nil)))
(which-key-mode)
```

I'm not interested in doing much more than this.

**Comment by mrbig033** [comment]
That's cool.
