### ISSUE TITLE
Option to ignore keystroke if it is not a valid option

### ISSUE THREAD

**Issue by muhmud** [justbur/emacs-which-key#224]
Tried looking for an existing option to do this; it would be great if there was an option to simply ignore a keystroke if it didn't represent a valid key, and thereby not cancelling the sequence, instead of the "is undefined" message.

This would be especially useful when you're in a mode that uses mouse tracking, as a slight move of the mouse when it's over the emacs window is enough to cancel a key sequence.

**Comment by justbur** [comment]
I believe this question has come up before, but this is not something that should be which-key's responsibility. which-key does not read keystrokes. It just eavesdrops on the process and shows what the valid next keystrokes would be.

**Comment by muhmud** [comment]
OK, thanks, makes sense; I'm going to try & figure out how to do this from spacemacs

**Comment by justbur** [comment]
FWIW, it's more involved than you might think at first, because this functionality is baked pretty deep into emacs.

**Comment by introom** [comment]
For example, pressing C-g after C-x, is it possible to show the normal quit message instead of also showing C-x C-g is undefined.
