### ISSUE TITLE
preserve labels upon prefix remaps

### ISSUE THREAD

**Issue by mphojele** [justbur/emacs-which-key#230]
Say I have a prefix key on `SPC a o` that leads to `org-mode` related bindings. I decide to have an alternate mapping of that very same prefix on `SPC o o` using this snippet:
```el
(define-key spacemacs-default-map (kbd "oo")
  (lookup-key spacemacs-default-map "ao"))
```
How do I ensure that the label for `SPC a o` is transferred to `SPC o o` as well as labels of any prefixes under it?

**Comment by justbur** [comment]
You probably want the mechanism described in [this section of the readme](https://github.com/justbur/emacs-which-key#key-based-replacement). There are other alternatives above and below.

**Comment by mphojele** [comment]
currently this is what you I have to do when remapping:
```el
(define-key spacemacs-default-map (kbd "oo")
    (lookup-key spacemacs-default-map "ao"))
  (which-key-add-key-based-replacements "SPC oo" "org")
  (which-key-add-key-based-replacements "SPC ooB" "org-brain")
  (which-key-add-key-based-replacements "SPC ooC" "clock")
  (which-key-add-key-based-replacements "SPC oof" "feeds")
```
Is there a conscise, or better way of doing this?

**Comment by justbur** [comment]
Yes, there are several. You can modify `which-key-replacement-alist` directly, write a helper function (which spacemacs likely has already), use [this mechanism](https://github.com/justbur/emacs-which-key#automatic), etc.

**Comment by mphojele** [comment]
Thank you for your help
