### ISSUE TITLE
Uppercase sorted first regardless of setting

### ISSUE THREAD

**Issue by ScottFreeCode** [justbur/emacs-which-key#233]
If I set `which-key-sort-uppercase-first` to off/nil, save it, restart Emacs and `C-h` for a keymap with lots of letters of both cases, the capital letters are still before the lowercase ones.

(This is not fixed by toggling docstrings, unlike the other sort order issue #232 .)

Using Emacs 26.3, which-key 20191221.1857

I can provide screenshots if that would help; let me know if you need anything else to reproduce.

<details>
<summary>which-key configuration</summary>

```
 '(echo-keystrokes 0.1 nil nil "This is also set by which-key, but we want it to be lowered even if which-key is missing.")
 '(which-key-compute-remaps t)
 '(which-key-echo-keystrokes 0.1 nil nil "I do not know why they need a separate setting for this, but if we do not set it which-key overrides our regular echo-keystrokes setting.")
 '(which-key-idle-delay 0.1)
 '(which-key-is-verbose t)
 '(which-key-mode t)
 '(which-key-show-prefix (quote mode-line) nil nil "redundant in most cases but (mostly) avoids wiping out echo area in commands that use both it and a transient map (e.g. isearch)")
 '(which-key-show-transient-maps t)
 '(which-key-sort-order (quote which-key-local-then-key-order))
 '(which-key-sort-uppercase-first nil)

 '(which-key-local-map-description-face ((t (:inherit which-key-highlighted-command-face))))

;(global-set-key (kbd "<menu>") #'which-key-show-top-level) ; for beginners, but the default M-x equivalent is better for the experienced
(global-set-key "\C-cx" #'which-key-show-top-level)
(global-set-key "\C-cX" #'reserved) ; for a which-key command that is to #'which-key-show-top-level what #'which-key-show-full-keymap is to #'which-key-show-keymap

(define-prefix-command 'my/which-key-menus)
(global-set-key "\C-ck" 'my/which-key-menus)
(global-set-key "\C-ckm" #'which-key-show-major-mode)
(global-set-key "\C-ckM" #'which-key-show-minor-mode-keymap)
(global-set-key "\C-ckx" #'which-key-show-keymap)
(global-set-key "\C-ckX" #'which-key-show-full-keymap)
```
</details>

**Comment by justbur** [comment]
Which sort function are you using? And when you restart are you sure your setting is saved?

**Comment by ScottFreeCode** [comment]
Definitely with `which-key-local-then-key-order`; the list in the folded section was found by `grep which-key .emacs` so I know it's saved. I think I saw the same behavior with the default sort; I could go double-check, if that helps isolate the issue.

**Comment by justbur** [comment]
Hm, after looking at this, the definition is ambiguous (and there is a bug in the code). How are you expecting it to work?

**Comment by ScottFreeCode** [comment]
Hmm; so I was thinking, with the capital-first setting: `A B C a b c`, and without it: `a b c A B C`. I suppose it could also be `A a B b C c` or `a A b B c C` though; maybe another setting for grouping case vs interleaving?

Looks like it works how I wanted with the fix, at any rate; thanks!
