### ISSUE TITLE
Feature Request: current prefix name with show prefix in modeline or echo area

### ISSUE THREAD

**Issue by ScottFreeCode** [justbur/emacs-which-key#234]
If I set the prefix show location to first line or last line, and enter a named prefix map (e.g. `C-h` is named "help-command"), this prefix location shows the name of the prefix map (awesome!), whereas other locations (modeline, echo area) show the same prefix that Emacs would have echoed.

I'd love if the modeline location also showed the name, and if the echo area location showed both the name if any and the prefix. Last-line looks great with the name and Emacs putting the prefix in the echo area, but modeline or echo area stands out better than last-line in my opinion.

(Note: I'm using popup type window. Conceivably other popup types may differ in visibility of the prefix echoed by Emacs.)

(Also, I assume a blanket use of the same display logic would probably not work well for the "left of keys" show prefix option, where space is expensive!)

**Comment by justbur** [comment]
You want me to have an option where which-key uses the whole modeline for the prefix name, is that correct?

**Comment by ScottFreeCode** [comment]
There already is a modeline option for the prefix display; it just doesn't display prefix's names like the first-row and last-row options do.

**Comment by ScottFreeCode** [comment]
Looks great; thanks!
