### ISSUE TITLE
Question: Full keymaps

### ISSUE THREAD

**Issue by ScottFreeCode** [justbur/emacs-which-key#236]
Is there a which-key command that is to `which-key-show-top-level` what `which-key-show-full-keymap` is to `which-key-show-keymap`?

Are there equivalent full keymap commands for `which-key-show-major-mode` and-or `which-key-show-minor-mode-keymap`?

**Comment by justbur** [comment]
Just added

**Comment by ScottFreeCode** [comment]
Cool, just passing through the same argument to the show keymap function!

I guess for all current bindings there's `C-h b`, so a which-key equivalent isn't strictly needed, though it would be nice for consistency.
