### ISSUE TITLE
Melpa stable outdated (tagged releases)

### ISSUE THREAD

**Issue by ScottFreeCode** [justbur/emacs-which-key#237]
Looks like the latest melpa stable version of whcih-key is from over a year ago and is missing a few fixes and features: https://github.com/justbur/emacs-which-key/compare/v3.3.1...master

I usually prefer the stable versions when available; would be nice to tag a few updates (especially if any more fixes or features go in, but I know your time is limited).

P.S. I haven't said it already because I wanted it to show up on my top (most recent) issue, but thanks for making which-key! I recommend it to everyone I suggest trying Emacs; in fact, while I could survive without it now, I probably wouldn't have learned Emacs without it!

**Comment by justbur** [comment]
Done and thank you for the nice words
