### ISSUE TITLE
How to Change C-h Prefix?

### ISSUE THREAD

**Issue by kingbari** [justbur/emacs-which-key#244]
I'd like to change the `C-h` prefix to `C-SPC` and so I added the following to my init.el, but it has no effect.

`(define-key which-key-mode-map (kbd "<C-SPC>") 'which-key-C-h-dispatch)`

Help understanding how to make this change would be appreciated. Thanks.

**Comment by justbur** [comment]
This has come up in slightly different ways a couple of times before. See #228 for example
