### ISSUE TITLE
which-key-group-description-face no longer applied

### ISSUE THREAD

**Issue by progfolio** [justbur/emacs-which-key#248]
Emacs recently changed `make-text-button` so that it does not mutate it's first arg if it is a string.
`which-key--propertize-description` was relying on this mutation and returning the original string arg it was passed.
Fortunately, this is an easy fix because we can rely on the return value of `make-text-button` in the new case and it should still work with the previous behavior. Will submit pull.

Thanks,
Nicholas Vollmer

**Comment by justbur** [comment]
ok, thanks
