### ISSUE TITLE
More compact layout

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#25]
Check out the fill-columns branch for a different layout algorithm that allows for variable column widths and a more compact layout. It also fills vertically first, rather than horizontally. Here's an example (the previous implementation wouldn't have fit all three columns because of the one long function name in the last column).

![new-layout-alg](https://cloud.githubusercontent.com/assets/2208382/8622129/b8e5d874-26f7-11e5-9a84-ad0b25ba9e6c.png)

**Comment by bmag** [comment]
Very nice :+1: looks much better IMO

**Comment by justbur** [comment]
Merged to master
