### ISSUE TITLE
Access key binding data programmatically (to generate "cheat sheet")

### ISSUE THREAD

**Issue by d4h0** [justbur/emacs-which-key#250]
Hi,

Is there a way to access the key binding data of `emacs-which-key` programmatically?

I'm new to Emacs (I'm using Doom), and I'd like to generate a cheat sheet with all keybindings plus additional information (the command/function, a short description, and a link to the full documentation).

It seems, most of the data is available with `emacs-which-key`.

Would it make sense, to add a command to `emacs-which-key` that generates a "cheat sheet" buffer for the current major mode? I think that would be helpful for many Emacs newbies.

`emacs-which-key` itself is great, but the ergonomics are not very good if someone wants to get an overview of what is possible (a single file or buffer would be much better IMO. And, as I wrote, I'd like to add additional information).

PS: If it's not possible to access the data: I'd be thankful for a hint where I find the place in the source code where the data is collected.

**Comment by justbur** [comment]
It's a reasonable assumption, but I don't think which-key is the best avenue for doing this. If I remember right, doom uses a package called general to do make the keybindings and general has a mechanism for recording the bindings (for later dumping to a buffer). 

There is also the somewhat clumsy method of evaluating `(describe-buffer-bindings (current-buffer))` in the buffer that you want to see the keybindings for, but it's probably easier to use existing functionality.

**Comment by d4h0** [comment]
Thank you so much for this information!

The disadvantage of using general.el, would be that it only has bindings that are defined via general.el, right?

Anyway, that gives me some keywords for further search queries.

Thanks again!

**Comment by dxlr8r** [comment]
I have the same issue. After reading the source code, I believe this is a start atleast: 

```
(require 'which-key)
(setq km 'foobar)

(defun which-key--format-and-replace (unformatted &optional prefix preserve-full-key)
  (list unformatted prefix preserve-full-key))
(which-key--get-bindings nil (symbol-value 'km) nil nil)
```

This will list the keybindings and their commands.
