### ISSUE TITLE
Ignore keybinding not working anymore?

### ISSUE THREAD

**Issue by TheBlob42** [justbur/emacs-which-key#257]
In the documentation of `which-key-replacement-alist` it states:

> If REPLACEMENT is anything other than a cons cell (and non nil) the key binding is ignored by which-key.

which I use to ignore my `winum` keybindings and instead replace them with a single which key entry like so:

```
(push '((nil . "winum-select-window-[1-9]") . t)
	which-key-replacement-alist)
```

Since the last update to version "20200721.1927" the ignoring does not work for me anymore :crying_cat_face: 
I am still able to replace the description of those commands:

```
(push '((nil . "winum-select-window-[1-9]") . (nil . "Something"))
	which-key-replacement-alist)
```

Is this a bug which was introduced recently or am I missing something which has changed in one of the recent updates? :thinking:

**Comment by justbur** [comment]
@rgrinberg any chance your change caused this?

**Comment by rgrinberg** [comment]
I'll have a look

**Comment by jkroes** [comment]
I'm experiencing the same issue as @TheBlob42 since upgrading my version of which-package on one of two operating systems. The older Melpa version, which-key-20200702.219, works. The version with the issue is which-key-20200721.2156. So one of the last two commits?

**Comment by rgrinberg** [comment]
Sorry for taking a while on this. #258 should fix this.
