### ISSUE TITLE
which-key candicates have a bad alignment

### ISSUE THREAD

**Issue by slarsar** [justbur/emacs-which-key#266]
I have a configuration :`which-key-set-max-description-lengh nil`  and `which-key-side-window-max-hight 0.8 `.

when I set doc-string in minibuffer by `C-w C-h d` to open docstring 

the right column not align well.

![image](https://user-images.githubusercontent.com/46400566/92943590-89538000-f485-11ea-9002-b700c73138bd.png)

the second and third column not align well

![image](https://user-images.githubusercontent.com/46400566/92943934-f109cb00-f485-11ea-893c-6dd0ce9b81e9.png)

**Comment by justbur** [comment]
What’s the question?

**Comment by slarsar** [comment]
How can I align then second column?

**Comment by justbur** [comment]
Ah I see now. It looks like you’re using some Unicode characters for your keys. Can you try without the Unicode and see if the problem goes away?

**Comment by slarsar** [comment]
> Ah I see now. It looks like you’re using some Unicode characters for your keys. Can you try without the Unicode and see if the problem goes away?

thx, the problem resolved after I unset Unicode .

**Comment by justbur** [comment]
Ok. There doesn’t seem to be a good way of aligning wide Unicode characters
in emacs so this would be a hard one to fix
