### ISSUE TITLE
Search commands and only show matching keys

### ISSUE THREAD

**Issue by super-tomcat** [justbur/emacs-which-key#269]
I love this package however it would be even better if we could drill down to just certain keybindings, something like isearch but as we type in a search term it searches the commands and displays those keys that match... i think this would be useful when a lot of bindings popup but you really just need to find certain ones.

**Comment by justbur** [comment]
In a sense, this is already available through an intermediate package. If you type `C-h C-h` in the middle of a key sequence emacs will call `describe-bindings`, which by itself is not that easy to use. However, you can also use `counsel-mode` from the counsel package, which will override `describe-bindings` with `counsel-descbinds` and you will get an interactive interface to search through the bindings. There is an analogous function available through the helm interface as well.

**Comment by super-tomcat** [comment]
Okay, thanks, i will have a look at those options, although i don't use counsel-mode
