### ISSUE TITLE
Submit to MELPA?

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#28]
I want to put off working on the paging stuff for the moment, because I'm not sure exactly the best way to do it yet and I want to see what problems people have with the current code. 

I'd like to get more people to use this to find the problems and such, so I was thinking of MELPA. But before I do that, I'm trying to think about what issues need to be resolved first. So my list is something like

**Do now**
- [x] Fix docstrings and add them where needed (#24)
- [x] Use new layout functions for a few days to find bugs
- [x] Merge status-key branch and decide if it should be the default
- [x] Fix any pressing issues with the window size calculations
- [x] Address any MELPA requirements
- [x] elisp conventions

**Do later**
- [ ] Work on paging/scaling functionality for next release

@bmag and @syl20bnr if you think there's something else please let me know. Thanks

**Comment by bmag** [comment]
Also check the [elisp conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Coding-Conventions.html).

**Comment by justbur** [comment]
I submitted it to MELPA and tagged v0.1
