### ISSUE TITLE
which-key does not work during read-key-sequence

### ISSUE THREAD

**Issue by minad** [justbur/emacs-which-key#284]
Example:

~~~ elisp
(setq map (make-sparse-keymap))
(define-key map "xa" #'ignore)
(define-key map "xb" #'ignore)

(let ((overriding-terminal-local-map map)
      (which-key-show-transient-maps t))
  (read-key-sequence nil))
~~~

Which key shows the help view "x +prefix", but after pressing additional keys the help view is not updated. And it even stays alive. This seems to be a conflict between the transient keymap installed by which-key and the one already being present?

See also https://github.com/justbur/emacs-which-key/issues/223

**Comment by justbur** [comment]
Confirmed, thanks

**Comment by bdarcus** [comment]
I just wanted to offer a gentle bump for this issue. Would great if it could be addressed.

The new menu description support is a great addition, BTW!

**Comment by minad** [comment]
UPDATE: I assume that this issue is fixed if one passes the COMMAND-LOOP=t argument to `read-key-sequence`.

**Comment by justbur** [comment]
@minad Are you suggesting that I need to add that argument or that it should be added in your original code?

**Comment by minad** [comment]
Original code, I close this!
