### ISSUE TITLE
How to config it like this？

### ISSUE THREAD

**Issue by yyangdid** [justbur/emacs-which-key#287]
1. My cursor is here, the cursor line at the bottom of the window, before using which-key：
![1](https://user-images.githubusercontent.com/10922667/114045080-56a62480-98ba-11eb-97fd-6da080e80ce3.png)

2. This is using which-key, my cursor line at the center of the window:
![2](https://user-images.githubusercontent.com/10922667/114045189-6e7da880-98ba-11eb-8a38-edc1048acfa1.png)

3. This is after using which-key, my cursor line still at the center of the window:
![3](https://user-images.githubusercontent.com/10922667/114045794-e2b84c00-98ba-11eb-8ade-d2c672184ec8.png)

I hope the cursor line  will auto return to 1 when after which-key, at the bottom of the window.
How should I config it?

**Comment by justbur** [comment]
There's no option for controlling that behavior, and off the top of my head, I don't know how to make emacs behave the way you want it to.

**Comment by yyangdid** [comment]
Ok, thank you, I finded a package: which-key-posframe, it's fine. 👍
