### ISSUE TITLE
which-key vs. guide-key screen shots

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#29]
I've done some screen shots to show the difference between which-key and guide-key, so you can use them if you want.

3 horizontally-split windows, which-key, `(which-key/setup-side-window-right)`:
![which-key-right](https://cloud.githubusercontent.com/assets/4334375/8633002/954c14f2-27bd-11e5-8e75-a04ca1f23987.png)
Compare with guide-key, `(setq guide-key/popup-window-position 'right)`:
![guide-key-right](https://cloud.githubusercontent.com/assets/4334375/8633004/b6da22da-27bd-11e5-8ebf-609e3e80542a.png)
guide-key shows less shortcuts, and the windows are not split evenly.

2 vertically-split windows, which-key, `(which-key/setup-side-window-bottom)`:
![which-key-bottom](https://cloud.githubusercontent.com/assets/4334375/8633010/f8617406-27bd-11e5-998c-101bb9b137eb.png)
Compare with guide-key, `(setq guide-key/popup-window-position 'bottom)`:
![guide-key-bottom](https://cloud.githubusercontent.com/assets/4334375/8633014/0909b156-27be-11e5-8f41-6c064cc71697.png)
guide-key shows less shortcuts, and the windows are not split evenly. You can see that which-key doesn't fully show "x" and "z" on the far right, but it's still much better than guide-key.

**Comment by justbur** [comment]
Looks good thanks. Want to add them to the readme? Could also just link to
this issue

**Comment by bmag** [comment]
I think it would be nice to add them to the readme. Should I do it or you?

**Comment by justbur** [comment]
Sure if you don't mind.

There's still some bugs with the layout functions that I need to fix. I
think that's why the text might be getting cut off.
