### ISSUE TITLE
In terminal mode, change popup side-window separator

### ISSUE THREAD

**Issue by shadowrylander** [justbur/emacs-which-key#296]
Hello!

As in the title; would it be possible to change the separator between the side-window and the rest of the buffer from "/" to something else?

Thank you kindly for the help!

**Comment by justbur** [comment]
Would you be able to add a screenshot? I'm not sure what separator you're referring to

**Comment by shadowrylander** [comment]
I would if I could, but it seems that the side-window options aren't working right now; for some reason I can't move the window to the right of the screen, no matter the max-width or positional settings.

**Comment by justbur** [comment]
I just tested and they work ok for me. I'll need more info to track down a problem.

**Comment by shadowrylander** [comment]
Understandable; how can I help? I'm using doom-emacs with the AUR emacs-gcc package on WSL 2 on Windows 10 currently.

**Comment by shadowrylander** [comment]
Actually, just moved away from doom, and it's working fine now. Sorry about that.

**Comment by shadowrylander** [comment]
However, I still want to change the fringe characters; I realize now that it's not exactly a which-key setting. Sorry for taking up space here! I'll go ahead and close this, then.
