### ISSUE TITLE
The function 'length>' is not known to be defined.

### ISSUE THREAD

**Issue by h7x4ABk3g** [justbur/emacs-which-key#309]
I think this `length>` function from some 3rd party dependency snook its way into a commit about 6 hours ago. Or is there a typo?

See line 1404 at https://github.com/justbur/emacs-which-key/commit/e236920b231ee1d86ae215598f7a9d8294467310#diff-bf1fffe40ec4f7913216328a397d79f60f7756031547a8e1b7f2a5f601db2f29

**Comment by justbur** [comment]
Maybe it's a new function (it's not in a package for me). 

Should be fixed with 3f76f5178d28e3b45c236ca83c37613851598abd. 

Thanks

**Comment by h7x4ABk3g** [comment]
Thanks!
