### ISSUE TITLE
Unicode correction

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#31]
@bmag I added `which-key-unicode-correction` as a variable. Setting it higher than 0 will "lie" about the available width and make the window seem smaller to the layout functions. 

When you get a chance could you try your case where the characters were getting cutoff using this variable? Thanks!

**Comment by bmag** [comment]
The docstring doesn't say whether `which-key-unicode-correction` is a number of columns or pixels, I assume columns.
With a value of 0 I get the familiar cutoff. With a value of 10 there is no cutoff. There is a bit of space on the right, but not too much. With any value between 1 and 9 which-key displays an error in the minibuffer: "which-key can't show keys: Settings and/or frame size are too restrictive."

Value of 0:
![cutoff](https://cloud.githubusercontent.com/assets/4334375/8638606/4d37348c-28c9-11e5-9f68-7f0d10e86c76.png)

Value of 10:
![no-cutoff-10](https://cloud.githubusercontent.com/assets/4334375/8638591/e7ae262a-28c8-11e5-850f-8af13fb33cf8.png)

Value of 8:
![error-unicode-8](https://cloud.githubusercontent.com/assets/4334375/8638587/d14c3e80-28c8-11e5-8610-d8c5f0181038.png)

The behavior I experience also depends on the frame size. For some frame sizes I don't get any cutoff even when `which-key-unicode-correction` is 0, but for others a value of 0 can give the error above.

**Comment by justbur** [comment]
Thanks for the detail. I'll look into this and fix the docstring. It should
function as a number of columns.

**Comment by justbur** [comment]
I fixed the docstring. I'm having trouble explaining why it would not show with a value of 8. This looks like a bug to me.

**Comment by justbur** [comment]
I made a couple of tweaks but didn't find a fix necessarily. I still don't understand the weird results here. 

I was playing with `(font-at (point))` and found a font that gives me wide arrows, but it wasn't source code pro. One of the fonts was falling back to lucida sans (I think it was ubuntu mono). When I used that command on my arrow with source code pro, it reported back source code pro. 

As far as I can tell here, the unicode correction is doing its job, but it's possible I can't replicate your setup/font/whatever.

**Comment by justbur** [comment]
I figured out the can't show keys problem and fixed it. 

Can you try the 8 case again?

I have no idea if this website is correct, but here is a listing of the fonts that support the character I'm using `#x2192`: http://www.fileformat.info/info/unicode/char/2192/fontsupport.htm

**Comment by bmag** [comment]
Seems to work :+1:  I'm not getting that error anymore, even though I tried. Also the cutoff seems to be gone for me - I have to change `which-key-unicode-correction` and my frame size on purpose in order to reproduce the cutoff.

**Comment by justbur** [comment]
Sounds good. Thanks for checking. The keys can't be shown thing was
unrelated to the Unicode stuff. You just stumbled onto a bug.

**Comment by justbur** [comment]
I'll close for now
