### ISSUE TITLE
New compiler warnings

### ISSUE THREAD

**Issue by tarsius** [justbur/emacs-which-key#312]
Recent changes resulted in these new compiler warnings:

```
Compiling /home/jonas/.emacs.d/lib/which-key/which-key.el...

In which-key--safe-lookup-key:
lib/which-key/which-key.el:1443:11: Warning: defsubst
    ‘which-key--safe-lookup-key’ was used before it was defined

In which-key--format-and-replace:
lib/which-key/which-key.el:1705:68: Warning: Unused lexical argument `prefix'

In which-key--get-keymap-bindings:
lib/which-key/which-key.el:1821:57: Warning: reference to free variable
    ‘evil-state’
```

I am guessing the second one is actually a bug, but you are in a better position to quickly determine that, so no commits from me this time.

(May I interest you in my [`auto-compile`](https://github.com/emacscollective/auto-compile) package? If you used that it would become less likely that you overlooked such problems.)

**Comment by justbur** [comment]
Thanks, see 27d9fec

> (May I interest you in my auto-compile package? If you used that it would become less likely that you overlooked such problems.)

I have it and use it :), but I didn't have a compiled version of the file in the directory so it wasn't doing anything.
