### ISSUE TITLE
Descriptions with wrong faces

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#32]
As you can see, some of the groups have the wrong face. For example, "rings" (r) and "symbol" (s) are groups, but are displayed like regular commands. They should be blue, not purple.
![wrong-face](https://cloud.githubusercontent.com/assets/4334375/8639603/b43cd7d6-28e7-11e5-9c88-e5d73ee25b14.png)

Full list of groups with wrong faces in the image above:
- C -> colors
- T -> themes
- c -> comments
- g -> version-control
- h -> highlight
- j -> split
- n -> numbers
- r -> rings
- s -> symbol

**Comment by justbur** [comment]
Group detection is really basic right now. The group has to start with
"group:" or Prefix. I could try to check for whether the binding is a
keymapp which is probably smarter.

**Comment by justbur** [comment]
It was something else actually. It should be fixed now
