### ISSUE TITLE
Minimum Lines of which-key window not set

### ISSUE THREAD

**Issue by nyambol** [justbur/emacs-which-key#325]
`(setq which-key-min-display-lines 13) ` does not, in fact, set the window to a minimum of 13 lines high. Perhaps, there's confusion on what 'lines' actually refers to. 

I have a set of key bindings that is one line. The above setting does shift them to the left and stack them 3 lines vertically. But the other 10 lines seem to be AWOL.

The point is just that I would like to have some vertical space beneath my small set of keybindings.

Thanks.

**Comment by justbur** [comment]
Thanks. Try 521a59b6f461232a008fba62f79bbb14f487b16e

**Comment by justbur** [comment]
Note that you'll have to set `which-key-allow-imprecise-window-fit` to a non-nil value to make this work the way you want it to.
