### ISSUE TITLE
Replacing description of a group changes its face

### ISSUE THREAD

**Issue by bmag** [justbur/emacs-which-key#33]
I changd the descriptions of <kbd>C-x 4</kbd>, <kbd>C-x 5</kbd> and <kbd>C-x C-k</kbd>, which are all prefix keys. As a side effect, which-key now shows them with `which-key-command-description-face`, instead of `which-key-group-description-face`.
```elisp
(which-key/add-key-based-replacements "C-x 4" "other window")
(which-key/add-key-based-replacements "C-x 5" "+other frame")
(add-to-list 'which-key-description-replacement-alist '("kmacro-keymap" . "kbd macros"))
```

**Comment by justbur** [comment]
I need to work on the group stuff some more. What you can do as a work
around is make the replacement start with "group:" that will trigger the
face and that string should be removed.

**Comment by justbur** [comment]
I checked those examples and they work for me now (without the work around). The "+other frame" one will become "++other frame" but I think you were trying to trigger the face with the +.

**Comment by bmag** [comment]
Yes, absolutely. Thank you.

**Comment by justbur** [comment]
Found another potential issue with those functions, so I rewrote them a bit.
