### ISSUE TITLE
which-key-show-transient-maps clobbers itself

### ISSUE THREAD

**Issue by Mihara** [justbur/emacs-which-key#335]
So I tried to enable `which-key-show-transient-maps`.

When I try to call up which-key in cases where the number of bound keys is very large, like `which-key-show-top-level`, help paging kicks in, and suddenly the entire page gets replaced with a help page for the transient keymap of the help pager. Which makes the whole setting surprisingly less useful.

While I am not entirely certain this isn't me misconfiguring something (For what it's worth, I'm using `which-key-posframe` too, but that's the only thing I can think of being relevant) I doubt it.

Could something be done about that?

**Comment by justbur** [comment]
Thanks. It looks like a bug to me

**Comment by justbur** [comment]
Can you try 8d934c571fb954232c4cbe6f1dab554a35ad5e7d?

**Comment by Mihara** [comment]
Looks like it works. Thanks! :+1:
