### ISSUE TITLE
How to switch among different pages of keys conveniently in which-key mode? 

### ISSUE THREAD

**Issue by hongyi-zhao** [justbur/emacs-which-key#348]
Currently, I have the following configuration for `which-key`:

```elisp
(use-package which-key
  :diminish which-key-mode
  :config
  (which-key-mode))
```

When I hit `C-h`, the following keys list will be triggered in minibuffer: 

![image](https://github.com/justbur/emacs-which-key/assets/11155854/0261cbb0-f575-4691-ad80-837624ab1b14)

As you can see, there are multiple pages of keys in this case, but I don't know how to switch among different pages of keys conveniently. I've tried to look at the document, but still failed to figure out the correct solution. Any tips will be appreciated.

Regards,
Zhao

**Comment by justbur** [comment]
The default behavior is covered [here](https://github.com/justbur/emacs-which-key#method-1-default-using-c-h-or-help-char) in the README.
