### ISSUE TITLE
which-key can’t show keys: There is not enough space based on your settings and frame size

### ISSUE THREAD

**Issue by dragove** [justbur/emacs-which-key#349]
I just installed emacs-which-key with [elpaca](https://github.com/progfolio/elpaca) as my package manager. But I got this error:

`- which-key can’t show keys: There is not enough space based on your settings and frame size`

My window size should be wide enought since [meow's keypad mode](https://github.com/meow-edit/meow/blob/master/TUTORIAL.org#keypad) works well

Emacs version: 30.0.50.166435 with pgtk and native-comp

screenshot:

![photo_2023-05-27_23-50-52](https://github.com/justbur/emacs-which-key/assets/24190403/6ac6e074-4e97-43a4-af45-e859cbd90441)

keypad mode:

![swappy-20230527-235753](https://github.com/justbur/emacs-which-key/assets/24190403/c1f6ea8a-0619-47fc-8e2d-7a35e3b83a05)

**Comment by ricma** [comment]
FWIW, I had the same issue. Removing the `which-key.elc` file solved it for me. Not sure where it came from, unfortunately.

**Comment by dragove** [comment]
> Removing the which-key.elc file solved it for me.

Thank you, I removed the elc file and rebuild it then everything gets working.
