### ISSUE TITLE
Customize which-key-C-h-dispatch prompt

### ISSUE THREAD

**Issue by antrmn** [justbur/emacs-which-key#350]
It is possible to customize the `which-key-C-h-map` in order to add custom commands to issue after `<prefix> C-h` is called. However, those new keybindings can not be displayed in the echo area since the prompt is hardcoded to show the next-page, previous-page, undo-key, toggle-docstrings, help, abort and digit-arg commands.

It would be nice to be able to customize this prompt.

**Comment by justbur** [comment]
Sure, see df6b0cb
