### ISSUE TITLE
How can I hide keys from the which-key popup? 

### ISSUE THREAD

**Issue by LemonBreezes** [justbur/emacs-which-key#366]
Hi. I want to hide some commands from the Harpoon package that are bound to SPC 1-9.

**Comment by justbur** [comment]
Yes, you can use `which-key-replacement-alist' to do this. Please see the documentation for that variable and let me know if you have questions.

**Comment by LemonBreezes** [comment]
> Yes, you can use `which-key-replacement-alist' to do this. Please see the documentation for that variable and let me know if you have questions.

Thanks! I finally figured it out:
```elisp
(add-to-list 'which-key-replacement-alist '(("" . "harpoon-go-to-[0-9]+") . ignore))
```
