### ISSUE TITLE
Error running timer ‘which-key--update’: (void-function take)

### ISSUE THREAD

**Issue by rochgs** [justbur/emacs-which-key#373]
Hello there :wave: 

When I input a prefix and wait for suggestion, I get not suggestions but the message:

```
Error running timer ‘which-key--update’: (void-function take)
```

Checking the native compile log I see a related warning:

```
which-key.el:2019:24: Warning: the function ‘take’ is not known to be defined.
```

I can see `take` is called from [that point in the code](https://github.com/justbur/emacs-which-key/blob/e21ee102ed5f2f60bd0bc47382c70aa8fd5b9c5b/which-key.el#L2019). Other than that, I know little to none about Lisp or Emacs built-in functions (if that's what that `take` is), so I don't know what else to do. I have the same configuration in another machine with the exact Emacs version. You can check my configuration [here](https://github.com/rochgs/.emacs.d), if needed. I am doing nothing fancy. Installing `emacs-which-keys` with `straight` [here](https://github.com/rochgs/.emacs.d/blob/39506b43fbe63ee018ca161aea7afe92db7dbfee/init.d/packages.el#L15), then `(which-key-mode 1)` [here](https://github.com/rochgs/.emacs.d/blob/39506b43fbe63ee018ca161aea7afe92db7dbfee/init.d/modes.el#L20C1-L20C19).

My Emacs version:

```
GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0) of 2023-05-14, modified by Debian
```

Any tip will be more than welcome. Thank you :bow:

**Comment by rochgs** [comment]
Quick update. This no longer applies:

> I have the same configuration in another machine with the exact Emacs version

Straight just updated the packages and now I have the same issue in the other instance,

I see the call to `take` [was made two weeks ago](https://github.com/justbur/emacs-which-key/commit/94a29cda9f75c9901667bf45ff25bd8c892cb416). I suppose that made the package incompatible with my Emacs version or it added new requirements I am missing.

**Comment by justbur** [comment]
Should be fixed now. We're prepping this package to be included in emacs itself, and `take` is now a built-in function, but I see it was only added recently.

**Comment by rochgs** [comment]
> Should be fixed now.

Indeed!

> We're prepping this package to be included in emacs itself

Those are excellent news :raised_hands: 

Thank you for your time and effort.
