### ISSUE TITLE
Print the echo-keystrokes modified message just once?

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#38]
Hi,

I tried out which-key today and so far it looks great right out of box.

A minor pet-peeve.. I have this minor mode enabled globally and I use desktop-mode.

So each time I restart emacs, as this minor mode gets enabled in all the buffers, I see these in my \*Messages\* buffer:

```
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25) [2 times]
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25) [8 times]
Buffer has been modified; could not load undo-tree history
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25)
Buffer has been modified; could not load undo-tree history
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25) [4 times]
Buffer has been modified; could not load undo-tree history
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25) [5 times]
Buffer has been modified; could not load undo-tree history
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25) [8 times]
org-mode fontification error
Which-key-mode enabled (note echo-keystrokes changed from 1 to 0.25)
Wrote /home/kmodi/.emacs.d/emacs_25_0.desktop.lock
Desktop: 28 buffers restored, 1 failed to restore.
Quit
```

Can this this prevented from printing out for each buffer?

**Comment by justbur** [comment]
I agree that's annoying. I'll look at it later. Thanks for the report

**Comment by justbur** [comment]
It should only show once now. Can you check with your setup to confirm?

**Comment by kaushalmodi** [comment]
Thanks. It is now fixed.

btw.. the note string reads strange to me. 

Should it be: `which-key: echo-keystrokes was changed from %s to %s`?

I removed the extra `note` and slightly reworded that. *Also I made the `W` lower case because the package name is all lower case.*

**Comment by justbur** [comment]
That's probably better
