### ISSUE TITLE
Implicit prefix map bindings are not shown

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#39]
I have these bindings in my emacs setup:

```el
;; Unicode
(require 'iso-transl)
;; Add custom bindings to "C-x 8" map
(dolist (binding '(;; >
                   (">"       . nil) ; First unbind ">" from the map
                   (">="      . [?≥]) ; greater than or equal to
                   (">>"      . [?≫]) ; much greater than
                   (">\""     . [?»]) ; right-pointing double angle quotation mark
                   (">'"      . [?›]) ; single right-pointing angle quotation mark
                   (">h"      . [?☛]) ; black right pointing index
                   ;; <
                   ("<"       . nil) ; First unbind "<" from the map
                   ("<="      . [?≤]) ; less than or equal to
                   ("<<"      . [?≪]) ; much less than
                   ("<\""     . [?«]) ; left-pointing double angle quotation mark
                   ("<'"      . [?‹]) ; single left-pointing angle quotation mark
                   ("<h"      . [?☚]) ; black left pointing index
                   ;; arrows
                   ("<right>" . [?→]) ; rightwards arrow
                   ("<left>"  . [?←]) ; leftwards arrow
                   ("<up>"    . [?↑]) ; upwards arrow
                   ("<down>"  . [?↓]) ; downwards arrow
                   ;; misc
                   ("r"       . [?▯]) ; white vertical rectangle
                   ("R"       . [?▮]) ; black vertical rectangle
                   ("*r"      . [?₹]) ; indian rupee sign
                   ("1/3"     . [?⅓]) ; fraction one third
                   ("0"       . [?​]) ; zero width space
                   ))
  (define-key iso-transl-ctl-x-8-map (kbd (car binding)) (cdr binding)))
```

When I hit `C-x 8`, it shows the bindings correctly. 

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8702566/7e5ab9b6-2ae6-11e5-8fa1-f2928611c2da.png)

But after that when I hit `>` it does not show the nested bindings (because `>` is sort of bound to an implicit prefix map and not an explicit one?).

Zoomed view:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8702592/acd56d54-2ae6-11e5-8b3b-e5f365fa3965.png)

Here are the nested bindings for `>`:

```el
                   (">"       . nil) ; First unbind ">" from the map
                   (">="      . [?≥]) ; greater than or equal to
                   (">>"      . [?≫]) ; much greater than
                   (">\""     . [?»]) ; right-pointing double angle quotation mark
                   (">'"      . [?›]) ; single right-pointing angle quotation mark
                   (">h"      . [?☛]) ; black right pointing index
```

*I can ignore the misalignment.. it's because I have `C-x 8 0` bound to `ZERO WIDTH SPACE`.*

[My `which-key` setup](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-which-key.el)

**Comment by justbur** [comment]
Not sure yet, but here's some more information. There seems to be something different about how `iso-transl-ctl-x-8-map` works that I haven't figured out yet.

This suggests the map should be quoted: http://www.emacswiki.org/emacs/PrefixKey

When I use `global-set-key` like this it works fine
```lisp
(require 'iso-transl)
(define-key iso-transl-ctl-x-8-map (kbd ">") nil)
(defun success () (interactive) (message "Typed C-x 8 >>"))
(global-set-key (kbd "C-x 8 > >") 'success)
```
I'll do more digging later.

**Comment by kaushalmodi** [comment]
I have always been using keymap vars without quotes and they have worked.
 
But here is what I tried:

- The `>` "maps" didn't get expanded with or without the quotes.
- It expands fine in `guide-key` (But now I cannot go that to that. Thanks to your work, I am spoiled by how beautifully `which-key` is rendering the key maps :))

I can later try looking in `guide-key` code if it handles such bindings in a special manner.

**Comment by justbur** [comment]
If it works in guide-key, that should give me enough clues to see what's happening. I'll check it out when I get a chance

**Comment by justbur** [comment]
Found the issue but I'm not sure how I want to fix it yet. The problem is that `(key-binding (kbd "C-x 8 >"))` is returning nil in your setup when it should be returning a keymap. This has been working well in all the other prefix cases I've tested so I don't know why it's different here yet.

**Comment by kaushalmodi** [comment]
Hmm, I am setting it to `nil` first 

```el
                   (">"       . nil) ; First unbind ">" from the map
```
But then I am rebinding `>=`, `>>`, etc to other things. I cannot do the below bindings unless I unbind its existing binding.

```el
                   (">="      . [?≥]) ; greater than or equal to
                   (">>"      . [?≫]) ; much greater than
                   (">\""     . [?»]) ; right-pointing double angle quotation mark
                   (">'"      . [?›]) ; single right-pointing angle quotation mark
                   (">h"      . [?☛]) ; black right pointing index
```

**Comment by justbur** [comment]
I don't think that's the problem exactly

**Comment by justbur** [comment]
Can you check your code now? It should work. Had to add another test against the `key-translation-map` because `iso-transl-ctl-x-8-map` is stored there and not in the "regular" keymaps

**Comment by justbur** [comment]
By the way you can use something like this to fix the spacing issue (It just changes how the key is shown). Replace "ZWS" with whatever you want to display there.

```lisp
(which-key-add-key-based-replacements "C-x 8 0" "ZWS")
```

**Comment by kaushalmodi** [comment]
Thanks! This is now fixed for me.

Also thanks for the "ZWS" tip. I was already using `which-key-key-based-description-replacement-alist` but it didn't occur to me that I can use that for stuff other than simply putting descriptive prefix names :)

https://github.com/kaushalmodi/.emacs.d/blob/f78ccb2415575939f8c4d1f4b2a76925faf94adc/setup-files/setup-which-key.el#L28

**Comment by justbur** [comment]
I like those arrows. I wanted to use more unicode characters as replacements, but I was worried about all the different fonts people maybe using and all of the bug reports I'd get. 

I was thinking that we could compile a list of nice unicode replacements and then include them as an option that you have to explicitly turn on.

**Comment by kaushalmodi** [comment]
Thanks! You can try using `char-displayable-p` function as used in [`pdf-tools`](https://github.com/politza/pdf-tools/commit/c0f8ff8b1c5f05af633a6bd978422464e477c1a8). 

I use this in my init to take care of unicodes:
- [Check if unicode font is available (Symbola in my case)](https://github.com/kaushalmodi/.emacs.d/blob/ab7f55f91a4c57075d3440f1af53540771f45a7c/setup-files/setup-symbola.el#L8-L12)
- [Set backup lighter if symbola not available](https://github.com/kaushalmodi/.emacs.d/blob/ab7f55f91a4c57075d3440f1af53540771f45a7c/setup-files/setup-shackle.el#L25-L27)
