### ISSUE TITLE
Is there a way to never show/select an empty *which-key* buffer?

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#41]
At times, on emacs startup, I am faced with just a blank \*which-key\* buffer even when I have set the `which-key-popup-type` to `'minibuffer`. My understanding was that that buffer get created only when you choose the other options like `'side-window`.

Can we make that buffer non-selectable so that user couldn't switch to it interactively?

Also that buffer should not show up by itself because it could be confusing at first as to what happened because all we see is a blank \*which-key\* buffer without a mode-line.

The first time this happened, I just kept waiting for emacs to look as usual when it starts up, but actually emacs had finished loading and I realized I was waiting on the blank \*which-key\* buffer :)

**Comment by kaushalmodi** [comment]
I will verify if this issue is resolved by this commit ( https://github.com/justbur/emacs-which-key/commit/ac6831fe6d83461226b965173e718737be480c55 ) once it hits Melpa.

**Comment by justbur** [comment]
Strange that it would get selected, but yes, please let me know if that helps

Right now I setup the buffer no matter what because it was simple, but if it becomes an annoyance I can make it so that the buffer is only created when it's needed.

**Comment by kaushalmodi** [comment]
The issue gets fixed by the commit I referenced above. Thanks @xuchunyang.

**Comment by justbur** [comment]
Great
