### ISSUE TITLE
Discussion: Sorting

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#44]
Opening this issue in case other suggestions want to be made for how to sort results (see #42)

**Comment by kaushalmodi** [comment]
I am pasting a part of my comment in that old issue thread here ( https://github.com/justbur/emacs-which-key/issues/42#issuecomment-122054701 ) which I think is interesting to pursue. It would be nice to sort the keys first by keymap and then alphabetically. If not that, at least use different faces for keys from different keymaps.

>> (3) key or description grouping prefixes and commands separately

> I like the next grouping better, by keymap. That way related commands are listed together.

>> (4) key or description grouping by keymap (major then minors)

> In general, I liked the idea to be able to group by prefix maps. A very good example would be to list the rectangle and register block in different groups when user hits C-x r. In guide-key, it set different faces for different gropus but did not arrange them (that would be great too).

**Comment by justbur** [comment]
I just looked into it and it seems guide key relied on a user specified regexp to highlight groups of keys. That's certainly possible but not quite the same thing as finding their respective keymaps and organizing them that way

**Comment by PythonNut** [comment]
I would definitely love the ability to organize by the map the keybinding came from (with or without colors). That means that the keys are sorted by topic, which can be really helpful.

**Comment by justbur** [comment]
@PythonNut As far as I know it's tricky to determine for a given key which keymap it comes from, but I had a thought about a way to easily do this. Are you familiar with `helm-descbinds`? because it would be easy to use the same order that that tool prints in, which is the order produced by `describe-buffer-bindings`. I'd be happy to add that as an option.

**Comment by PythonNut** [comment]
@justbur I don't use `helm-descbinds`. I normally just do <kbd>M-x</kbd> `describe-bindings` + isearch. That said, the ordering sounds perfect. In fact, I can't really tell how your implementation would deviate from the proposal.

**Comment by justbur** [comment]
Actually @pythonnut I think this is really simple. You should get the same
order by setting which-key-sort-order to nil. If you want to make changes
from there I can look into it.

**Comment by PythonNut** [comment]
@justbur I just tried that and it looks great.

**Comment by kaushalmodi** [comment]
I like the recently added highlighting feature. [This][1] gets me similar to what `guide-key` did; separation of rectangle and register/bookmark commands visually.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/9968347/df24a614-5e15-11e5-9c77-6a8ee23f999e.png)

[1]: https://github.com/kaushalmodi/.emacs.d/blob/046cc9daeea30b68426160c13699ad3e6da502de/setup-files/setup-which-key.el#L63-L73

**Comment by justbur** [comment]
@kaushalmodi Great! I didn't add that feature initially, because I thought it might be too noisy, but I like your use of it

**Comment by hmelman** [comment]
Something (I think) I'd like is the ability to move all the prefix bindings to the beginning or end of the list.

**Comment by justbur** [comment]
@hmelman It shouldn't be too hard to do this, but I'd like to know if/how you would like to sort within the prefix bindings and whether you'd like them to come first or last.

**Comment by hmelman** [comment]
It's something I'd have to play with but my sense is that it should be another setting. So I could sort by key or description as now, but also have a setting to move prefixes to start or end of list. End is probably more useful to me (particularly in the C-x 8 case).

**Comment by justbur** [comment]
@hmelman If you know any elisp, all you need to do is write a comparison function that takes two cons cells (car is the string describing the key and cdr is a string for the command description) and reports if the first should come before the second. Here's one interpretation of your request

```elisp
(defun prefix-last-then-by-keys (acons bcons)
  (let ((apref? (which-key--group-p (cdr acons)))
        (bpref? (which-key--group-p (cdr bcons))))
    (if (not (eq apref? bpref?))
        (and (not apref?) bpref?)
      (which-key-key-order acons bcons))))
(setq which-key-sort-order 'prefix-last-then-by-keys)
```

`which-key--group-p` is the function I use to identify prefixes in the code.

**Comment by hmelman** [comment]
Yes, I think I like this as a sort order. Thanks.

**Comment by justbur** [comment]
@hmelman If you use it for a while and continue to like it, let me know and I can add it as a built-in option.

**Comment by hmelman** [comment]
Yes, I definitely like this (prefix-last-then-by-keys).

**Comment by justbur** [comment]
@hmelman e9aa7c37b8e48c4f187d5584cd04b26616fa2c23 To use it, do 
```elisp
(setq which-key-sort-order 'which-key-prefix-then-key-order)
```

**Comment by axionix** [comment]
I'm new to emacs, and this is a helpful utility. however, i'd really like the ability to sort capital keys next to lowercase keys. I have similar commands bound to the same key, such as a -> goto-address-mode, A -> goto-address-prog-mode. however all capital keys are listed before any lowercase keys.

**Comment by justbur** [comment]
@axionix It's not documented yet, but I recently added
```elisp
(setq which-key-sort-order 'which-key-key-order-alpha)
```

**Comment by axionix** [comment]
@justbur thanks!

**Comment by justbur** [comment]
I think we have a good range of options, so I'll close this. I'm happy to consider others if someone wants to reopen.

**Comment by ChauhanT** [comment]
Hi, does which-key have an option to sort in the order of definition? I have gone through the github page and couldn't find anything!

**Comment by hmelman** [comment]
> Hi, does which-key have an option to sort in the order of definition? I have gone through the github page and couldn't find anything!

@ChauhanT I usually use `customize-group` for a package (in this case `which-key`) to see all its options.  Searching for "sort" in that customize buffer takes you right to `which-key-sort-order`.  Searching the source for all the `defcustom`s is the equivalent.

**Comment by ChauhanT** [comment]
Thanks @hmelman, I am indeed new and didn't how I could use `customize-group` this way! I see now there is no way to sort according to the order of definition.

**Comment by hmelman** [comment]
> I see now there is no way to sort according to the order of definition.

You can set `which-key-sort-order` to `which-key-description-order` which I think will do what you want.
