### ISSUE TITLE
Local/global keymaps

### ISSUE THREAD

**Issue by wavexx** [justbur/emacs-which-key#45]
I've been trying which-key since it has been in melpa (a few days ;)), mostly for fun to discover which key is mapped to what (as opposed to: from function to keybinding).

One thing that I noticed is that it would make sense to indicate whether the binding is in a local map vs global map, maybe just by using a customizable face which is the same by default.

**Comment by justbur** [comment]
Makes sense to me. I don't mind making the faces different by default, too, if it's not too intrusive. I could even imagine 3 categories: Global, Major Mode, Other (minor + other local). 

If you want to propose a scheme for the faces, I could implement it as an option to start.

**Comment by wavexx** [comment]
Somehow, I would put global faces with a bold face, and other (that is: non-global/non-major) with maybe italics? (although I don't like italics). I would avoid striking differences though: I like the fact that all bindings are shown, it's mostly a tweak to be able to distinguish them visually.

**Comment by justbur** [comment]
I agree that it should just be a hint and not a drastic difference. I also don't like italics :-). I prefix with a "+" for the groups in addition to a difference face. Maybe just a single character hint would work in this case?

**Comment by wavexx** [comment]
On 19/07/15 15:15, Justin Burkett wrote:
> I agree that it should just be a hint and not a drastic difference. I
> also don't like italics :-). I prefix with a "+" for the groups in
> addition to a difference face. Maybe just a single character hint would
> work in this case?

I think another character is already too much (the list if very busy
already for some prefix keys).

Some experimentation is needed, going by imagination is hard.

If you allow the faces to be customized, just default to the regular
face for now and leave the report open.

I'll try some combinations and report back if you whish.

**Comment by justbur** [comment]
Fair enough. I'll let you know when I have something ready

**Comment by justbur** [comment]
@wavexx Do you know a relatively simple way to do this? From what I can see it's complicated to figure which map will apply for a given key 

https://www.masteringemacs.org/article/mastering-key-bindings-emacs
http://emacs.stackexchange.com/questions/653/how-can-i-find-out-in-which-keymap-a-key-is-bound

**Comment by wavexx** [comment]
On 22/07/15 03:36, Justin Burkett wrote:
> @wavexx <https://github.com/wavexx> Do you know a relatively simple way
> to do this? From what I can see it's complicated to figure which map
> will apply for a given key
> 
> https://www.masteringemacs.org/article/mastering-key-bindings-emacs
> http://emacs.stackexchange.com/questions/653/how-can-i-find-out-in-which-keymap-a-key-is-bound

It's hard, unfortunately I don't know any better way.
I this case, kaymap-at-point might be enough for us?

**Comment by justbur** [comment]
@wavexx So I just added `which-key-local-map-description-face` to see if this can be a simple fix for the issue you raised here. 

This face will apply when the binding can be found in `(current-local-map)`. This seems to be useful from what the documentation says. For example, it seems that "most" major-modes should store there bindings here. Searching the global map is problematic because so many of the bindings could be shadowed. I'd prefer to keep the check simple so it is easy to describe to people, and I'm not sure there is one right way to accomplish what you want. 

If you could play with this, the command face and the group face, I could make tweaks as you see fit.

Another possibility is to work in the categorization provided by helm-descbinds.el. That is easy to accomplish because the method is so similar to what which-key does, but it seems hard to deal with more than a few categories in a graceful way.

**Comment by justbur** [comment]
Never mind what I said about the global map not working. This should work for any keymap.

**Comment by wavexx** [comment]
On 29/07/15 04:51, Justin Burkett wrote:
> This face will apply when the binding can be found in
> |(current-local-map)|. This seems to be useful from what the
> documentation says. For example, it seems that "most" major-modes should
> store there bindings here. Searching the global map is problematic
> because so many of the bindings could be shadowed. I'd prefer to keep
> the check simple so it is easy to describe to people, and I'm not sure
> there is one right way to accomplish what you want.

I think that's a great start, and maybe it's already enough.

I would also be against complicated checks. which-key IMHO needs to be
fast in order not to be obtrusive.

> If you could play with this, the command face and the group face, I
> could make tweaks as you see fit.

I'll have a run.

> Another possibility is to work in the categorization provided by
> helm-descbinds.el. That is easy to accomplish because the method is so
> similar to what which-key does, but it seems hard to deal with more than
> a few categories in a graceful way.

There's also a limit in what you can fontify in a sensible way.

IMHO, after 3 different styles, remembering what face means what already
loses meaning.

**Comment by wavexx** [comment]
On 29/07/15 14:04, Justin Burkett wrote:
> Never mind what I said about the global map not working. This should
> work for any keymap.

I tried a bit, and seems to be just what I had in mind.
For C-c, it's *immediately* useful.

I tried several combinations of fontification, but

:inherit which-key-command-description-face
:weight bold

seems to be the most obvious.
You immediately notice why it's bold.

Depending on the theme, the other standard font-lock faces do not "tell"
me anything.

What do you think?

**Comment by wavexx** [comment]
On 30/07/15 16:55, Yuri D'Elia wrote:
> Depending on the theme, the other standard font-lock faces do not "tell"
> me anything.
> 
> What do you think?

Or actually:

 '(which-key-command-description-face ((t nil)))
 '(which-key-local-map-description-face ((t (:inherit
font-lock-function-name-face)))))

seems even better to me.
Less noisy.

**Comment by justbur** [comment]
I also find it useful, and I think both of your suggestions are good. I'm not sure if it makes sense as a default or just to put the suggestions in the documentation. Are you suggesting it should be the default?

**Comment by wavexx** [comment]
On 30/07/15 21:05, Justin Burkett wrote:
> I also find it useful, and I think both of your suggestions are good.
> I'm not sure if it makes sense as a default or just to put the
> suggestions in the documentation. Are you suggesting it should be the
> default?

I cannot decide for you about the default: I think the current is
reasonable as well, but I currently prefer my second suggestion. Being
less colorful by default gives more accent to the local map.

For python-mode and ess-mode which I happened to use today while testing
WK, it feels great. Both modes uses the local map heavily, especially
under C-c.

**Comment by justbur** [comment]
Right, well I'm glad it helps. I'll add a section to the README about this with your suggestion for those who want some more control. Thanks for the help
