### ISSUE TITLE
which-key-side-window-location

### ISSUE THREAD

**Issue by wavexx** [justbur/emacs-which-key#46]
I think there should be a 'auto setting in there, which chooses between two axes such as 'right and 'bottom depending on the most available space. Maybe with a list: '(right bottom).

I'm using 'right, but since I'm using a tiling window manager, the frame gets resized often automatically. In a two vertically-split emacs frames, 'bottom would have more space, whereas 'right just doesn't show anything due to the minimum size constraint.

**Comment by justbur** [comment]
Nice idea. I'll put it on my list of TODOs. Thanks

**Comment by justbur** [comment]
@wavexx You can try '(right bottom) or any other 2 element list for locations on the develop branch.

**Comment by justbur** [comment]
I merged it to master yesterday. It's described in the readme.

**Comment by wavexx** [comment]
On 22/07/15 13:28, Justin Burkett wrote:
> I merged it to master yesterday. It's described in the readme.

Works very well, I can say by trying randomly it's much more effective
than a fixed position.

**Comment by justbur** [comment]
Great. Only downside is you're not sure where it's going to come from :-).
Thanks for the idea

**Comment by wavexx** [comment]
On 23/07/15 14:09, Justin Burkett wrote:
> Great. Only downside is you're not sure where it's going to come from :-).

If you're using a dynamic/tiling window manager, which resizes the frame
very often, this is "acceptable".

I either work with one frame maximized or a frame and another window of
some kind (usually documentation) side-by-side.

This behavior feels totally logical (ie: it appears where I would like
it to be).

**Comment by justbur** [comment]
Sounds good. I'll add that point to readme
