### ISSUE TITLE
What is which-key?

### ISSUE THREAD

**Issue by nloyola** [justbur/emacs-which-key#47]
The introduction section in the *README.org* does not actually state whatch **which-key** is. If it told what it did, I could decide if I want to install it or not.

I realize that I can click on the link for **guide-key-mode** but why?

**Comment by justbur** [comment]
The short description of the repo is "Emacs package that displays available keybindings in popup", but your point is well taken. I haven't had a chance to write a good readme yet.

**Comment by justbur** [comment]
Just did a quick update. Is that better?

**Comment by nloyola** [comment]
That's perfect! Thank you. I wish a lot more Emacs package authors did this.

The commit is 45d6eb6.
