### ISSUE TITLE
which-key doesn't list keys after paging

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#49]
Whether or not we need to list one or more pages for a given prefix like `C-x` or `C-c`, once the `which-key-show-next-page` binding is pressed, `which-key` does not show the key lists for any key pressed after that.

Below example would demonstrate this issue:
- Open an `org-mode` buffer. This is because I want to show this issue when `C-c` needs more than 1 page.
- In that buffer, when you hit `C-c`, you see the first page.
- Hitting the key set for paging shows the second page perfectly fine.
- As I sort the keys by key order, the `C-v` key bound to `org-babel` commands shows up on the second page.
- Now if I hit `C-v`, `which-key` does not show the commands bound to `C-c C-v` map.

If I repeat the above steps **except** doing the paging, `C-c C-v` keys are displayed fine by `which-key`.

[[my which-key setup]][1]

[1]: https://github.com/kaushalmodi/.emacs.d/blob/0df8cc2824b634009f0198e32fa2d92c49e7ca99/setup-files/setup-which-key.el

**Comment by justbur** [comment]
Thanks I'll try this later. Sounds like a bug. Can you try this with the side-window popup type? Might be related to #48

**Comment by kaushalmodi** [comment]
Yes, I can replicate the same issue with `which-key-popup-type` set to `'side-window` too.

**Comment by justbur** [comment]
Ok thanks

**Comment by justbur** [comment]
I think it should work now. Can you check your case?

**Comment by kaushalmodi** [comment]
Thanks! This is fixed for me now.
