### ISSUE TITLE
Show x/y pages only if `n-pages`>1

### ISSUE THREAD

**Issue by kaushalmodi** [justbur/emacs-which-key#50]
I was looking into the code on how to not show `1/1` if there is only one page to show.

```el
             (status-left (propertize (format "%s/%s" (1+ i) n-pages)
                                      'face 'font-lock-comment-face))
             (status-top (propertize (format "(%s of %s)" (1+ i) n-pages)
                                     'face 'font-lock-comment-face))
```

So my suggestion is to set `status-left` and `status-top` to `""` when `n-pages` is `1`.

**Comment by justbur** [comment]
Do you think it's not helpful to know that all keys are shown? I'm not sure it's always obvious

**Comment by kaushalmodi** [comment]
If `1/2` is displayed, I know that all keys are not shown.
If not `x/y` status is displayed, I know that all keys are shown.

I suggested this because in 90%+ cases, I see `1/1`.

**Comment by justbur** [comment]
Right, I was thinking that it helps a first time user to always show it to be familiar with it, but I think hiding it probably makes more sense. I'll do that instead

**Comment by kaushalmodi** [comment]
Thanks!
