### ISSUE TITLE
Key description is wrong if the keybinding is changed.

### ISSUE THREAD

**Issue by person808** [justbur/emacs-which-key#51]
The keybinding description are mapped directly to keybindings so a changed keybinding will show the wrong description. This likely only affects people using Spacemacs or other distributions where keybindings and descriptions are predefined.

![image](https://cloud.githubusercontent.com/assets/6396431/8868334/cc5c3e86-3172-11e5-89a6-342028168a27.png)

`SPC SPC` is mapped to `hs-toggle-hide` for me, but the description is `ace word`. I think that mapping descriptions to function names would solve this problem

**Comment by justbur** [comment]
This is part of the default spacemacs configuration for which-key, which can be changed depending on what @syl20bnr thinks. The relevant part is here: 
https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L3233-L3247

You'll have to change it in your own files. The relevant part of the readme is here. Let me know if you have questions
https://github.com/justbur/emacs-which-key#key-based-replacement.

**Comment by justbur** [comment]
I should also say that you can turn off all of the replacement stuff (by setting all of the replacement alists to nil) and get verbatim descriptions of command names if you like.

**Comment by syl20bnr** [comment]
I was wrong to think about such alist :-( The key should be the function
which the invariant and not keyboard key. Sorry for this.

Le vendredi 24 juillet 2015, Justin Burkett <notifications@github.com> a
écrit :

> This is part of the default spacemacs configuration for which-key, which
> can be changed depending on what @syl20bnr <https://github.com/syl20bnr>
> thinks. The relevant part is here:
>
> https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L3233-L3247
>
> You'll have to change it in your own files. The relevant part of the
> readme is here. Let me know if you have questions
> https://github.com/justbur/emacs-which-key#key-based-replacement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justbur/emacs-which-key/issues/51#issuecomment-124478648>
> .
>


-- 
-syl20bnr-

**Comment by justbur** [comment]
No problem. There's another alist that works by targeting function names.
It doesn't have the mode specific stuff but that shouldn't be an issue in
this case.

**Comment by syl20bnr** [comment]
Excellent ! Which-key rocks !

Le vendredi 24 juillet 2015, Justin Burkett <notifications@github.com> a
écrit :

> No problem. There's another alist that works by targeting function names.
> It doesn't have the mode specific stuff but that shouldn't be an issue in
> this case.
>
> On Fri, Jul 24, 2015 at 7:26 AM Sylvain Benner <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I was wrong to think about such alist :-( The key should be the function
> > which the invariant and not keyboard key. Sorry for this.
> >
> > Le vendredi 24 juillet 2015, Justin Burkett <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> a
> > écrit :
> >
> > > This is part of the default spacemacs configuration for which-key,
> which
> > > can be changed depending on what @syl20bnr <
> https://github.com/syl20bnr>
> > > thinks. The relevant part is here:
> > >
> > >
> >
> https://github.com/syl20bnr/spacemacs/blob/develop/spacemacs/packages.el#L3233-L3247
> > >
> > > You'll have to change it in your own files. The relevant part of the
> > > readme is here. Let me know if you have questions
> > > https://github.com/justbur/emacs-which-key#key-based-replacement.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/justbur/emacs-which-key/issues/51#issuecomment-124478648
> > >
> > > .
> > >
> >
> >
> > --
> > -syl20bnr-
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/justbur/emacs-which-key/issues/51#issuecomment-124488835
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justbur/emacs-which-key/issues/51#issuecomment-124491991>
> .
>


-- 
-syl20bnr-

**Comment by justbur** [comment]
See here https://github.com/justbur/emacs-which-key/blob/master/README.org#key-and-description-replacement

**Comment by justbur** [comment]
@person808 this should work now. Can you check on your end?

**Comment by person808** [comment]
Yup it works great!
