### ISSUE TITLE
Use (or include an option for) unicode characters as abbreviation for special characters

### ISSUE THREAD

**Issue by epitzer** [justbur/emacs-which-key#52]
Personally, I find the inverted face with abbreviated special keys (tab, return, delete, and space) a little unintuitive. Would it be possible to use unicode symbols instead. For example:
* U+21B9 ↹ (leftwards arrow to bar over rightwards arrow to bar) for `tab`
* U+23CE ⏎ (return symbol) for `return`
* U+21E4 ⇤ (leftwards arrow to bar) for `delete`
* U+2423 ␣ (open box) for `space`

I am unsure about `escape` as the corresponding unicode symbol seems not very widespread (U+238B ⎋ broken circle with northwest arrow).

It seems that this should already be possible with `key-replacement` but I am not sure how it interferes with special key handling.

What do you think?

**Comment by justbur** [comment]
It's definitely possible to do this now. The replacements occur before the special key handling, so all you need is something like this for each one you want to do

```elisp
(push '("TAB" . "↹") which-key-key-replacement-alist)
```

You can also set `(setq which-key-special-keys nil)` which will disable the special key stuff (but it's actually unnecessary to do this if you are already replacing them.

**Comment by epitzer** [comment]
Cool, thank you. I will definitely do that.

Do you think that these settings could be useful defaults too, or be bundled in some way?

**Comment by justbur** [comment]
I think unicode is cool, but it's been problematic, because the character width can change based on the font (screwing up the way the layout works) and of course everyone uses different fonts. 

The best way to do it that I can think of right now would be to describe a setup in the readme that people could drop into their init file. That way they could immediately see if the characters are supported by their font. If you wanted to come up with nice replacements like you did here, I'd be happy to add a section to the readme

**Comment by epitzer** [comment]
You are right it should not be the default.

We could add U+2196 ↖ (north west arrow) to the above list as suggestion for replacing `escape`, which completes the list of default special keys and seems *common* enough to be supported by many fonts.

**Comment by justbur** [comment]
Nice, I'll add a section to the readme later. I think the special key stuff deserves it's own section. I can put the unicode alternative in there too. Thanks!

**Comment by epitzer** [comment]
Cool!

I have to note however, that in my current setup, the symbols are no longer correctly aligned :-(
![2015-07-24_162852](https://cloud.githubusercontent.com/assets/1774452/8876684/7442de80-3221-11e5-9e7b-0d734b75d4a6.png)

**Comment by justbur** [comment]
Yeah that's the width thing. The layout assumes a constant character width.
Your arrows are wide too probably but it doesn't cause problems since they
are in every column.

**Comment by justbur** [comment]
Added to readme
