### ISSUE TITLE
Show keybinding for paging

### ISSUE THREAD

**Issue by epitzer** [justbur/emacs-which-key#53]
I was thrilled to see the note `(1 of 2)` at the bottom that suggest that there is more, however, it took some time to find out how to turn to the next page. Extending this label to e.g. `(1 of 2) press <F5>` would help new users find their way around immediately.

**Comment by justbur** [comment]
That's a good idea. I'll have to think about the right way to do this, since the key is not bound by default. See https://github.com/justbur/emacs-which-key#paging

**Comment by justbur** [comment]
Added a version of this in the latest commit. It depends on `which-key-paging-key` being correct

**Comment by justbur** [comment]
What do you think @epitzer?

**Comment by epitzer** [comment]
I am using the version as configured in spacemacs, so I am not 100% sure if it is the same, but I like it very much.

**Comment by justbur** [comment]
Yes, it's the same as the default. Glad it works for you
