### ISSUE TITLE
Not showing after SPC u <num> SPC

### ISSUE THREAD

**Issue by louy2** [justbur/emacs-which-key#56]
As title. It's not strictly an expected behavior given the current state of which-key, but I think it's nice to have the consistency.

**Comment by justbur** [comment]
Are you saying it's not working with prefix arguments in general or in this
specific case?

**Comment by louy2** [comment]
Uhm... I don't use prefix arg very often so I don't know prefix arg other than numbers. Basically any number in place of <num> shows this. Since after a `SPC u <num>` it should be a normal command, I expect which-key to list all normal command again.

**Comment by justbur** [comment]
Ok I'll try it when I get a chance. Thanks for the report

**Comment by justbur** [comment]
Figured it out. It wasn't a which-key problem. It's a problem with the configuration in spacemacs. I have a pull request against spacemacs to fix this and rework that configuration. 

Relevant commit is 005f80e

Thanks for the report

**Comment by justbur** [comment]
I think this is fixed now. If it works for you @louy2 can you close the issue? Thanks

**Comment by louy2** [comment]
Works like a charm! Thank you!
