### ISSUE TITLE
Timer error when using sudoedit/emacsclient combination

### ISSUE THREAD

**Issue by drot** [justbur/emacs-which-key#57]
Hello and thank you for this wonderful package! I have my `$EDITOR` set as `emacsclient` and the following error pops up when attempting to sudoedit a file:

`Error running timer ``which-key--update': (wrong-type-argument keymapp nil)`

Strangely enough the timer error doesn't appear when editing files not owned by root.
This is on `GNU Emacs 24.5.1 (i686-pc-linux-gnu, X toolkit, Xaw scroll bars)`

**Comment by justbur** [comment]
Thank you!

That's weird. Is this right away or when you're in the middle of entering a
key sequence? If it's in the middle of a key sequence, what is the key
sequence? And it's definitely only happening with sudo?

**Comment by drot** [comment]
It happens either with `C-x` or `C-c`. I press that combination, wait and the timer error appears. So far it doesn't appear on *normal* files.

**Comment by justbur** [comment]
Ok, would you mind doing `M-x toggle-debug-on-error`? You should enter the debugger at some point. If you just paste what the debugger shows here it should help me figure this out. I can try to reproduce it on my own later.

**Comment by drot** [comment]
Full error log: http://sprunge.us/GbPL
Started with a *blank* configuration file: http://sprunge.us/MZBF

**Comment by justbur** [comment]
Thanks, I think I got it. Please reopen this if my fix doesn't work.

**Comment by drot** [comment]
Yes, it is working now. Thanks for the speedy fix!

**Comment by justbur** [comment]
Great!
