### ISSUE TITLE
[feature] display the prefix command

### ISSUE THREAD

**Issue by syl20bnr** [justbur/emacs-which-key#58]
I thought it would be cool to have an option to be able to have the prefix command name printed in the minibuffer.

Say I type `SPC s` which corresponds to prefix command `search/symbol` which-key displays:

```
search/symbol 
B -> helm-buffers-smart...   L -> ..
F -> helm-files....          P -> ...
```

**Comment by justbur** [comment]
Great idea! I'll try to do it

**Comment by justbur** [comment]
I think it might make sense only for explicitly named groups otherwise the names are not that interesting. Is that what you were thinking?

**Comment by syl20bnr** [comment]
I don't have preference for anonymous prefixes. The defcustom could propose
both behaviors. Maybe displaying explicitly "anonymous prefix" would bother
us enough to force us to name the remaining anonymous prefixes :-)

Le samedi 15 août 2015, Justin Burkett <notifications@github.com> a écrit :

> I think it might make sense only for explicitly named groups otherwise the
> names are not that interesting. Is that what you were thinking?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/justbur/emacs-which-key/issues/58#issuecomment-131369851>
> .
>


-- 
-syl20bnr-
