### ISSUE TITLE
which-key echo-keystrokes question

### ISSUE THREAD

**Issue by cmccloud** [justbur/emacs-which-key#59]
I'm not 100% about this yet, but it looks as though which-key will sometimes set the value of echo-keystrokes to nil when the mode is activated.

Is this intentional?

**Comment by justbur** [comment]
If echo-keystrokes is too high it will clobber anything that which-key
shows in the echo area so yes and actually which-key shows all of the
information that echo-keystrokes does plus more.

It should only do it when the echo area is actually used by which-key.

Are you having an issue with it? Spacemacs unfortunately resets
echo-keystrokes which is an issue I haven't solved yet. I mentioned it to
@syl20bnr at one point with no response.

**Comment by cmccloud** [comment]
Ah, some of us noticed that sometime recently echo-keystrokes weren't showing up. Setting echo-keystrokes to a postive value in config fixed it for me, and I was poking around to see what parts of spacemacs might have touched it.

**Comment by syl20bnr** [comment]
I have no idea :-)

**Comment by justbur** [comment]
I don't think the current behavior is optimal, and I'm open to other suggestions. There are two problematic cases:

1. If `which-key-show-prefix` is `'echo` then the prefix as well as other information (page numbers, key hints, and prefix titles) is displayed in the echo area. I can't "lock" the echo area so the next message there (like the one triggered by `echo-keystrokes` wipes it out. 

2. If `which-key-popup-type` is `'minibuffer` then the which-key popup uses the same space and the same problem arises. 

I had it at one point where I was taking the existing value of `echo-keystrokes` and finding the midpoint between 0 and `which-key-idle-delay`, which was fine, but then the echo area kind of flashes as the keystrokes are echoed, followed shortly by the which-key echos. I gave up and made it zero by default, but you can change it when which-key is active using `which-key-echo-keystrokes`. 

@syl20bnr The problem in spacemacs is that spacemacs sets `echo-keystrokes` to I think 0.6 after which-key is initialized, so if `which-key-idle-delay` is less than 0.6 (default is 1), `echo-keystrokes` is going to overwrite anything which-key puts in the echo area.

Note: It's possible to configure which-key to not use the echo area at all, but I like making use of the extra line.

**Comment by justbur** [comment]
@syl20bnr I misspoke. I am overriding echo-keystrokes in spacemacs. The thing I said about spacemacs setting it back to 0.6 (I checked it was 0.02) was something that was happening earlier, but no longer happens. If you want to keep it at 0.02 that shouldn't interfere with which-key. I can just set `which-key-echo-keystrokes` to 0.02 and that setting will be preserved.

**Comment by justbur** [comment]
@cmccloud I fixed the echo-keystrokes backup issue. Please open a new issue if you notice any problems with it.
