### ISSUE TITLE
Is there guide-key/highlight-command-regexp in which-key-mode?

### ISSUE THREAD

**Issue by c02y** [justbur/emacs-which-key#61]
I can use this:

    (setq guide-key/highlight-command-regexp
	  '(("^helm-" . warning)
            ("rectangle" . link))

`link` and `warning` can be color like "red".

to set all the command which contains the specific string the specific color.

Can I do this in which-key-mode?

**Comment by justbur** [comment]
No not currently. You can look at the faces section of the readme for the
faces that are available.

If I added something like this how would you want it to work exactly?

**Comment by c02y** [comment]
I already posted an example, if you are still confused, just check out guide-key github page. It is very well documented. 

于 2015年9月16日 GMT+08:00下午6:46:52, Justin Burkett <notifications@github.com> 写到:
>No not currently. You can look at the faces section of the readme for
>the
>faces that are available.
>
>If I added something like this how would you want it to work exactly?

**Comment by justbur** [comment]
I'm not confused. Your example leaves a lot unspecified. Guide-key applies a default face if you leave one unspecified. Do you have a proposal for the default face? Are you suggesting that the command and the key should have this face applied? What about the separator? Should it apply to prefixes?

**Comment by c02y** [comment]
It is fine for me if only the commad's face is applied, it is better if it is easy to make the whole line which includes prefix, separator and the command the same color. 

I'm satisfied with the default faces, I just want to highlight some commands such as describe-*, helm-*,cscope-*, rectangle* just like you set a different color for prefix key like "C-x 4".

**Comment by justbur** [comment]
It's not impossible to highlight everything, but the way it's setup now the keys and the commands are highlighted separately, so it would be easiest to just highlight the commands for this. 

So here's my proposal. You can specify the face for the commands according to a regexp like you did above. If you just put in a regexp, which-key will apply a default highlight face (which I'll set to something simple like underlining, but you can change that). How does that sound?

**Comment by c02y** [comment]
Sounds good to me.

**Comment by justbur** [comment]
Add in 4d7363df197894ca5fcdc0c1f9e509d8f16aaedf

```elisp
(setq which-key-highlighted-command-list
  '("^helm-"
        ("rectangle" . link))
```
will by default add an underline to helm commands and highlight the rectangle ones with the link face.

**Comment by c02y** [comment]
Yes, Thank you.

This is my configuration:

    (setq which-key-highlighted-command-list
    	  '("^helm-" "toggle" ;; default link
    		("^cscope-" "register" . warning) 
    		("^ggtags-" . warningg)
    		("register" . warningg)
    		("rectangle" . error)
    		("^projectile-" . error)
    		("help" . highlight)
    		("emacs" . highlight)
    		("bookmark" . highlight)))

Can I make it shorter, especially for those words such as "help" "emacs" and "bookmark" sharing the same face ?

**Comment by justbur** [comment]
You could do something like this if you like
```elisp
(setq which-key-highlighted-command-list
      '("^helm-" "toggle" ;; default link
        ("\\(^cscope-\\)\\|register\\|\\(^ggtags-\\)" . warning)
        ("\\(^projectile-\\)\\|rectangle" . error)
        ("help\\|emacs\\|bookmark" . highlight)))
```

**Comment by c02y** [comment]
Thank you.

**Comment by justbur** [comment]
Closing. Please re-open if you have problems
