### ISSUE TITLE
Typo in which-key-highlighted-command-face docstring

### ISSUE THREAD

**Issue by hmelman** [justbur/emacs-which-key#64]
(defface which-key-highlighted-command-face
      '((t . (:inherit which-key-command-description-face :underline t)))
      "Default face for the command description when it is a command
    and it matches a string in `which-key-highlighted-command-face'."
      :group 'which-key-faces)

should be: "and it matches a string in `which-key-highlighted-command-list'."

**Comment by justbur** [comment]
Thanks! Fixed in df53b5d11cf507b68c2b8ec9d566981d241667f4
