### ISSUE TITLE
Question - Disable automatic popup, use manual

### ISSUE THREAD

**Issue by synic** [justbur/emacs-which-key#66]
Now that I've gotten to know most of the keys I want, I'd like to disable the automatic popup of which-key, and instead bind it to some key (like `C-h`) so I can call it up after I've started a key combination.

Is this currently possible with configuration options?

**Comment by justbur** [comment]
Kind of. You can't disable it at the moment but you can set a long idle delay which is effectively the same thing

**Comment by justbur** [comment]
The C-h binding already pops up the buffer before the idle timer triggers it so that works already

**Comment by synic** [comment]
Ok, that'll will work.  Thank you!

**Comment by synic** [comment]
Hrmm, it doesn't seem to work as well.  When you let it time out, pressing successive keys bring up successive which-key dialogs, for instance, `SPC` would bring up all the keys on `SPC`, and if you then press `w`, you get all the keys available after the `w`.  

If you type `C-h` to bring up the dialog, it does not follow your keypresses, and successive `C-h` presses do not do what you would expect them to.

**Comment by justbur** [comment]
Ah yes that all makes sense. Honestly I haven't used it this way and it
wasn't really designed to be used this way. I think disabling which-key and
using helm-descbinds is the way to go for this use case, but I'm happy to
work on this some if you really want to stick with which-key.

**Comment by synic** [comment]
You are probably right, it's just that which-key is so much prettier ;-)

It's up to you if you want to add it in.   One of these days when I know what I'm doing, maybe I'll try to do it.

Thanks for the help!

**Comment by justbur** [comment]
If you want to describe the exact behavior you expect in this case I'll put
it on my todo list.

**Comment by clemera** [comment]
@justbur Is this possible with the current version? I'm interested in this as well. I would like to avoid the automatic popup and only show the which key popup on demand when pressing `C-h` after a prefix and then proceed with the key sequence.

**Comment by justbur** [comment]
@clemera Try something like this (after 5cbfccd5fec9b8f75b0933d2f0350592cebd32e8).

```elisp
(setq which-key-idle-delay 600)
(which-key-mode 1)
(setq prefix-help-command 'which-key-manual-update)
```

The idle delay is just set high so that which-key effectively never automatically shows the buffer. With this configuration, using `C-h` within an incomplete key sequence should trigger which-key.

**Comment by clemera** [comment]
@justbur Thanks a lot! Currently it does only work on first invocation (I tried with emacs -Q, version 26.1):

    `C-x` ;; waiting and nothing happens as it should be
    `C-h` ;; which key triggers and I can call a command or quit with `C-g`
    `C-x` ;; after the above which key triggers now immediately

Strangely it does seem to work again when I use the mouse to click somewhere.

**Comment by justbur** [comment]
@clemera I can't reproduce this. The only thing I can think of is that you don't have `which-key-idle-delay`set to a high value or are somehow resetting the value of this variable by mistake. 

Feel free to open a new issue.

**Comment by justbur** [comment]
@clemera FYI I just changed the implementation. See https://github.com/justbur/emacs-which-key#manual-activation

**Comment by clemera** [comment]
@justbur Awesome, it works now for me, too. Thank you so much!
