### ISSUE TITLE
`which-key--buffer` persists after `describe-key` command

### ISSUE THREAD

**Issue by iqbalansari** [justbur/emacs-which-key#68]
**Steps to reproduce**

1) Enable `which-key-mode`
2) Press <kbd>f1</kbd><kbd>k</kbd>
3) In the prompt the appears press any prefix key and wait for `which-key-idle-delay` time so `which-key--buffer` appears (for example press <kbd>f1</kbd> and wait)
4) Complete the key-sequence (example press <kbd>k</kbd>)

**Expected result**

The `which-key--buffer` should be hidden after the key sequence is completed

**Observed result**

The `which-key--buffer` persists and hides only after executing a command

I am using Emacs v24.5, on Ubuntu 12.04. My `which-key` configuration is below.

```emacs-lisp
(setq which-key-idle-delay 0.3)
(which-key-setup-side-window-bottom)
(setq which-key-paging-prefixes '("C-x" "C-c"))
(setq which-key-paging-key "<f5>")
(setq which-key-side-window-max-height 0.5)
```

This issue happens for any function that uses `read-key-sequence` for example execute the following form

```emacs-lisp
(read-key-sequence "Test: ")
```

Now enter <kbd>f1</kbd> and wait so that `which-key--buffer` appears then press <kbd>k</kbd>, the form would return the keys read but the `which-key--buffer` will stay on screen until another command is executed.

Its seems that the issue happens due to combination of the facts that `which-key` polls for the value of `this-single-command-keys` and uses `pre-command-hook` to delete the `which-key--buffer`. Since `this-single-command-keys` returns the value of last key sequence read, it returns non-nil value even when the keys are being read using `read-key-sequence` (for example `describe-key` does this) due to which-key display is triggered, however `which-key` does not get a chance to cleanup the `which-key--buffer` until next command is executed (and the `pre-command-hook` is run). A possible fix might be to run `which-key--hide-popup` in the `post-command-hook` too.

**Comment by justbur** [comment]
Thank you for the detailed report. To be clear, do you think that the which-key buffer should popup in the middle while entering a key sequence for `describe-key`? Because another way to approach this would be to try to suppress that behavior.

**Comment by justbur** [comment]
@iqbalansari I merged your pr. Thank you! I am curious about your thoughts to the previous question.

**Comment by iqbalansari** [comment]
Personally I do not mind being shown the possible keys when `describe-key`.

Technically there is one small issue with suppressing popup for `describe-key`. The problem is that `read-key-sequence` can be invoked by commands/functions other than `describe-key` and I could not find a generic way to detect if the keys are being read by the main command loop or some custom command, as such I guess you would have to hard-code the name of commands that use `read-key-sequence`, which would be less than ideal. On the flip side the number of commands that use `read-key-sequence` is very small, I know only `describe-key` but I may be wrong, so hard-coding might still work.

**Comment by iqbalansari** [comment]
It turns out I was wrong a grep for `read-key-sequence` on emacs source's lisp directory yielded 92 results so it not as rare as I had thought. Additionally users might declare custom functions with use `read-key-sequence`, `which-key` would not have any way to detect such functions.

**Comment by justbur** [comment]
It's something I hadn't really considered so I appreciate you raising the issue. It's difficult I think to know the intention of an arbitrary function calling `read-key-sequence`, so I don't want to do anything different now but it's something to keep in mind. As long as you are happy with the current behavior, I'm fine leaving it as is. Thanks again

**Comment by justbur** [comment]
If there is some function for which which-key popping up is especially annoying we can put in a special case for that (or possibly a list of commands that inhibit which-key while they are executed).

**Comment by iqbalansari** [comment]
Ideally popup should not have being shown for `read-key-sequence` by commands but I realize that it is difficult to achieve that and as I said I do not mind it. So I think this should work for now. If I come across a generic way to detect if `read-key-sequence` if being directly called by the main loop rather than a command I will report back.

A customization list of commands sounds like a good middle ground :+1: .

**Comment by iqbalansari** [comment]
BTW I want to thank you this package and really appreciate your effort. **Thank you**

**Comment by justbur** [comment]
I'll look into it too when I get a chance. Glad you like it :smile:

**Comment by iqbalansari** [comment]
I just got a way to detect if `read-key-sequence` is being invoked by a command, we can check the value of the variable `this-command` if it is `nil` then the `read-key-sequence` was invoked by the main loop otherwise it was invoked by a command. This of course fails if `read-key-sequence` is invoked a non-interactive function but I cannot think of a non-interactive function using interactive function like `read-key-sequence` (not saying there isn't, there might be such functions but I guess they are rare).

**Comment by justbur** [comment]
Great, do you want to make a pr?

**Comment by iqbalansari** [comment]
Yes sure, PR is on its way!
