### ISSUE TITLE
Frame popup problems

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#7]
It pops up as a smallish window, flickers, and disappears almost immediates. This is using emacs25 on win8. Need to check with emasc24 on linux. I don't have the ability to try osx.

**Comment by bmag** [comment]
If your emacs window is maximized, then the popup frame is hidden behind the main frame. Do you see the popup if you make your main frame smaller?

BTW, I'm using emacs24 on linux.

**Comment by justbur** [comment]
No, I still get the same behavior without the maximized window. 

I noticed the echo area starts filling up with "switch-frame- switch-frame- ...."

**Comment by justbur** [comment]
Just tried my other machine and it doesn't flicker per se, but the popup only flashes for an instant and goes away. 

I can look into this more later. Thanks again for your help

**Comment by justbur** [comment]
Probably needs more testing than what I did, but I'll close it for now
