### ISSUE TITLE
-pad not found

### ISSUE THREAD

**Issue by jonpither** [justbur/emacs-which-key#72]
When I try to install.

**Comment by syohex** [comment]
I suppose you use too old [dash.el](https://github.com/magnars/dash.el). Please upgrade dash.el and retry.
`-pad` was introduced at version 2.7.0(https://github.com/magnars/dash.el/blob/2.7.0/dash.el#L901). Latest version is 2.12.0.

**Comment by jonpither** [comment]
Fixed - thanks.

**Comment by justbur** [comment]
Thank you @syohex. I added a note to the readme about the dependencies.
