### ISSUE TITLE
[Feature] Back to the Future

### ISSUE THREAD

**Issue by syl20bnr** [justbur/emacs-which-key#73]
I drop here this idea coming from twitter: https://twitter.com/p_pavlov/status/651423038374838272

**Comment by justbur** [comment]
I don't know about that... That would require messing with core emacs functionality (not that it's not possible of course)

**Comment by syl20bnr** [comment]
Ok I thought you already had the basis with the `C-h` feature.

**Comment by justbur** [comment]
It can definitely be done. It's just a matter of popping the last key off
the key sequence and filling `unread-command-events` with everything else.
For me, it would be more appropriate in another package, since I don't
really see this as a which-key specific feature. The idea behind `C-h` was
to execute the page flip and pretend that the same key sequence was still
active.

**Comment by syl20bnr** [comment]
I don't think this kind of feature makes a lot of sense without any feedback like what which-key proposes.

**Comment by justbur** [comment]
Ah, I see. I just through this together to try
```elisp
(defun go-back ()
  (interactive)
  (setq unread-command-events
        (mapcar (lambda (ev) (cons t ev))
                (butlast (listify-key-sequence (this-command-keys)) 2))))
(define-key evil-leader--default-map (kbd "w C-g") 'go-back)
```

**Comment by syl20bnr** [comment]
Actually this possibility to cancel a key to explore the key bindings can be pretty useful and I found myself willing to to it at least once.

**Comment by syl20bnr** [comment]
Cool, I cannot try it for now but I'll be able to give it a try later today.

**Comment by justbur** [comment]
The nice thing about `C-h` is that it's (kind of) bound in every submap. I don't know of another key that has this property, so any key that you chose would have to be manually bound in all the submaps (I think)

**Comment by syl20bnr** [comment]
Indeed, maybe setuping a pre-command hook that auto-uninstall could do the trick. It would only resume the last which-key buffer directly.

**Comment by syl20bnr** [comment]
Say `backspace` is hit, the pre-command hook installed by the which-key show buffer action intercept it, modify the event, redisplay which-key at this point.
If the pre-command hook predicate is not met then it auto uninstall itself.

**Comment by justbur** [comment]
I think I got it
```elisp
(defun go-back ()
  (interactive)
  (setq unread-command-events
        (mapcar (lambda (ev) (cons t ev))
                (butlast (listify-key-sequence (this-command-keys)) 2))))

(defun define-recursive (map key def &optional recursing)
  (when recursing (define-key map key def))
  (map-keymap (lambda (ev df)
                (when (keymapp df)
                  (define-recursive df key def t)))
              map))

(define-recursive evil-leader--default-map "\C-g" 'go-back)
```

**Comment by justbur** [comment]
@syl20bnr Try this after updating to https://github.com/justbur/emacs-which-key/commit/8f23bd79c6bf44245925dddacb56a4f485117928
```elisp
(which-key-define-key-recursively evil-leader--default-map "\C-g" 'which-key-undo)
(mapcar
 (lambda (mode-map)
   (which-key-define-key-recursively (cdr mode-map) "\C-g" 'which-key-undo))
 evil-leader--mode-maps)
```

**Comment by justbur** [comment]
This is implemented now

**Comment by syl20bnr** [comment]
Thank you!

-syl20bnr-
