### ISSUE TITLE
Ability to show toplevel keybindings

### ISSUE THREAD

**Issue by iqbalansari** [justbur/emacs-which-key#74]
While `which-key` works great for viewing keybindings starting with a prefix, there is not way in `which-key` to view the toplevel keybindings directly. This would be helpful in context of modes (though the utility is not limited to these) like dired which bind a lot of commands to single keys. What are your thoughts?

I have partially [implemented](https://github.com/iqbalansari/emacs-which-key/tree/feature/toplevel-bindings) this (no paging for toplevel popup yet) in separate branch. If you like the idea (and the implementation) I will polish up the code and open a pull request

**Comment by justbur** [comment]
Sure, open a pull request. I think it might take a few iterations to get this right. I haven't tested your code yet.

**Comment by iqbalansari** [comment]
> I think it might take a few iterations to get this right

I agree with you, parsing toplevel keybindings is a bit tricky.

**Comment by justbur** [comment]
Just closing because we have the pull request open
