### ISSUE TITLE
Avoid requiring s.el

### ISSUE THREAD

**Issue by hmelman** [justbur/emacs-which-key#76]
s.el is a little slow to load since it requires ucs-normalize. It seems like which-key is only using s-pad-right and s-repeat. Replacing them with calls to format and make-string would remove the dependency on s.el entirely.

**Comment by justbur** [comment]
Didn't realize it slowed anything down. I'm happy to remove the dependency

**Comment by justbur** [comment]
Done in d63ce4f19698b57191a220b09672cc2a81ec640b. Good idea, thanks
