### ISSUE TITLE
evil, which-key-declare-prefixes and which-key-declare-prefixes-for-mode along with which-key-idle-delay

### ISSUE THREAD

**Issue by torgeir** [justbur/emacs-which-key#77]
Hey!

And thanks for a great minor mode! I'm really enjoying which-key.

In the process of cleaning up my key bindings and improving the mnemonics, I wanted to use which-key to help me out. I'm not using spacemacs I'm just taking a similar approach of my own for elisp-learning purposes. So I whipped up these examples which work out nicely

```elisp
(setq which-key-idle-delay 0)

(which-key-declare-prefixes "SPC m" "Major mode")
(which-key-declare-prefixes "SPC me" "Major mode evaluate")
(evil-leader/set-key "meb" 'eval-buffer)

(which-key-declare-prefixes-for-mode 'lisp-interaction-mode "SPC l" "Specific mode")
(which-key-declare-prefixes-for-mode 'lisp-interaction-mode "SPC le" "Specific mode evaluate")
(evil-leader/set-key-for-mode 'lisp-interaction-mode "leb" 'eval-buffer)
```

Both `SPC m` and `SPC l` work as you'd expect

<img width="750" alt="screen shot 2015-10-18 at 11 43 51" src="https://cloud.githubusercontent.com/assets/118202/10563513/9f97953a-758d-11e5-9c39-aac196932313.png">

However, paired with `(setq which-key-idle-delay 0.8)` this happens:

`SPC m` work as you'd expect

<img width="750" alt="screen shot 2015-10-18 at 11 50 43" src="https://cloud.githubusercontent.com/assets/118202/10563546/86c75b52-758e-11e5-929b-f95cb74911aa.png">

`SPC l` seems to flash the which-key buffer, so fast I can barely see it, but bails out and gives `SPC l is undefined`

<img width="750" alt="screen shot 2015-10-18 at 11 50 57" src="https://cloud.githubusercontent.com/assets/118202/10563547/8b4837f0-758e-11e5-9209-62031fe4dced.png">

Don't know if it's a bug or if I'm misunderstanding the apis (or some other modes might be interfering), just wanted to chime in for your two cents

**Comment by justbur** [comment]
> SPC l seems to flash the which-key buffer, so fast I can barely see it, 

The flash is likely an interaction with the built-in option `echo-keystrokes`. See if you are resetting it somewhere. If you set it to nil, it will disable it. If it's not that, there's probably a message that's getting displayed at roughly the same time that the which-key message is displayed. Check your "*Messages*" buffer.

> but bails out and gives SPC l is undefined

That's not a which-key thing. Which-key doesn't touch your actual key bindings, so Emacs reporting that a key is undefined is a problem somewhere else. 

I was able to get the configuration you provided working here, so it seems that there is some other problem. I'm happy to help, but I'll probably need some more info.

**Comment by torgeir** [comment]
I was setting `echo-keystrokes` to `0.1`.

I'm pretty sure it was the which-key window flashing, and I believe I was seeing the `l`-binding there for a split second. However, now that I have ported the rest of my bindings to the same format https://github.com/torgeir/.emacs.d/commit/7df3eb5f7e88c8650d75a1c9d7a8f82ff77fdb22 (and some of the later) things seems to be working as intended..

Thanks anyway, I guess :)

Relevant which-key prefixes+keybinding defuns if someone stumbles across this: https://github.com/torgeir/.emacs.d/blob/86df55cf8ff7fa76f88431dac23737808b88d0a9/setup/defuns.el#L317-L336

**Comment by justbur** [comment]
> I'm pretty sure it was the which-key window flashing, and I believe I was seeing the l-binding there for a split second. 

Hm ok. If you see it again in please open an issue again and I'll try to reproduce it.

**Comment by torgeir** [comment]
Will do, thanks.
