### ISSUE TITLE
Would you mind creating a library for which-key-like pop-up menus?

### ISSUE THREAD

**Issue by endrebak** [justbur/emacs-which-key#78]
I'm thinking of something that takes an `alist` of `key - text` and creates a formatted table.

Colors and menu positioning should be possible to change.

Should not be tied to the keymap functionality in `which-key`, since like BB pointed out in the spacemacs gitter, `evil` can be quirky. 

I'll make pull-requests and test stuff when/if I have something to play around with.

Feature addition to consider (sometime in the future): multiple menus in a buffer, where each menu has a header of sorts. Could be achieved by passing in multiple alists.

**Comment by justbur** [comment]
Here's a list of features that which-key has that I'm not sure if you would want included:
 1. timers for popping up
 2. sorting
 3. replacement alists
 4. paging
 5. "hints" like the ones that show the current key sequence in the echo area
 6. lighter manipulation

**Comment by endrebak** [comment]
For me personally, only displaying the alist in a nice way is necessary. However, I imagine that if you want to make a general purpose library you want to include most of these. I'm guessing you should just do the minimal thing that works and then grow the library organically afterwards.

It really is up to you and what you want to do. Perhaps we should also ask some of the hackers on `gitter/spacemacs` for advice and feedback.

**Comment by justbur** [comment]
@endrebak I looked into this but it's more work than I have time for at the moment. If you want to start on it I can answer questions.

**Comment by endrebak** [comment]
Thanks. Closing this then 🎉🎅🏿
