### ISSUE TITLE
Automatically determine prefix label

### ISSUE THREAD

**Issue by epitzer** [justbur/emacs-which-key#80]
Functions often share the same function name prefix when they share the same key chord prefix, e.g. functions starting with `org-babel-` are mostly bound to chords starting with `C-c C-v`.
![2015-11-03_090846](https://cloud.githubusercontent.com/assets/1774452/10903497/8ab5ac4a-820a-11e5-8aac-89caf7ecda44.jpg)

However, currently only `+prefix` is displayed after pressing `C-c`. Would it be possible to automatically discover these common function name prefixes as group name? Maybe even when only 90% of the function names share the same prefix. On top of that, the common prefix could then be removed from the display, so instead of having e.g.
`f → org-babel-tangle-file` in the list and
`C-c C-v-` in the bottom
we could remove all common prefix matches from the list (removing a lot of clutter) and add it to the bottom using ellipsis to suggest the omission like
`f → …-tangle-file` in the list and
`C-c C-v- (org-babel-…)` in the bottom
and no "`…`" for the functions not matching the common prefix.

What do you think?

**Comment by justbur** [comment]
I like the idea, but I'm not sure how consistently prefixes are used for commonly named commands. I suspect it might be less effort to declare the names of the prefixes as they come up rather than trying to get some automatic detection right, but I could be convinced otherwise. I like the idea of putting the removed namespace in the echo area, but again that only really makes sense where all commands are in the same namespace.

How common are these cases for you?

**Comment by epitzer** [comment]
As I am using Spacemacs, the key bindings are very consistent and well sorted out which means that many prefixes overlap to a large degree. It's hardly ever 100% but even if only slightly more than 50% of prefixes overlap that would already remove quite some clutter in the descriptions...

You could add a configurable threshold, after which common prefixes extracted and shortened. I, personally, imagine it being useful already at 51% overlap.

This could even be combined with automatic coloring of other common prefixes or even substrings, as has been done manually by @kaushalmodi in [another comment](https://github.com/justbur/emacs-which-key/issues/44#issuecomment-141536191). I am just dreaming on ...

**Comment by kaushalmodi** [comment]
@epitzer I have [this](https://github.com/kaushalmodi/.emacs.d/blob/726aced5440f2a512a014c5c772ee2eee4015c9f/setup-files/setup-which-key.el#L27-L52) in my config to have good looking prefixes. They seem to cover 99% of my use cases I believe. My OCD hasn't yet kicked in tweak my `which-key` setup in almost 2 months :)

**Comment by epitzer** [comment]
I have seen it and like it very much. My preemptive OCD just wants to have that for all future changes too ;-)

**Comment by justbur** [comment]
@epitzer I was thinking about this again. I don't think trying to automatically determine the label is worth the effort (unless you have a simple way to do it). I could collect suggestions for some default prefix labels to use, but I'm not sure how many useful ones there will be.

**Comment by justbur** [comment]
Reopen if you still have thoughts about this
