### ISSUE TITLE
top-level parsing not perfect yet

### ISSUE THREAD

**Issue by justbur** [justbur/emacs-which-key#82]
![bad-parse](https://cloud.githubusercontent.com/assets/2208382/11193082/a3c1f550-8c72-11e5-8180-975dc36983c8.png)

I also want to find a reasonable way to include more function keys like left, right, down, home, etc.

I'm going to rewrite the parsing function using https://github.com/emacs-helm/helm-descbinds/blob/master/helm-descbinds.el#L175-L214 for inspiration. I'm just putting this issue up to say that I'm aware of the issues. 

cc @iqbalansari

**Comment by iqbalansari** [comment]
Was about to report this. I will try out your [proposed](https://github.com/justbur/emacs-which-key/pull/83) solution and report back
