### ISSUE TITLE
Replacements from `which-key-key-replacement-alist` are done very aggressively 

### ISSUE THREAD

**Issue by iqbalansari** [justbur/emacs-which-key#84]
It seems it replaces substrings rather than full strings in the key names. For example, I have following entry in `which-key-key-replacement-alist`

```
("RET" . "⏎")
```

Which leads `<C-return>` to be rendered as `<C-⏎urn>`

**Comment by justbur** [comment]
Is it case-sensitivity you want? because you can certainly write a regexp that doesn't match "<C-return>"

**Comment by justbur** [comment]
I turned on case-sensitivity for replacements. I think this is natural for this use and should help avoid the need to write more complicated regexps

**Comment by iqbalansari** [comment]
Not really case-sensitivity. I was under the impression that the complete key must match the cons of an entry in `which-key-key-replacement-alist` to be replaced. So `C-RET` would be replaced with `C-⏎` but `C-RETURN` would not become `C-⏎URN`. 

Now I see that cons is actually a regexp. So basically `("\\WRET\\W" . "⏎")` would prevent `return` from being converted to `⏎urn`. 

One minor issue is that even tough the above regexp prevents `C-RETURN` from turning to `C-⏎URN`,  since `RET` is part of `which-key-special-keys` , which key renders `C-RETURN` as `C-rrun`. See the screenshot below

![screenshot from 2015-11-17 08 48 01](https://cloud.githubusercontent.com/assets/2726057/11201854/05aae584-8d08-11e5-8f3c-2006b0e62c7d.png)

**Comment by justbur** [comment]
> I was under the impression that the complete key must match the cons of an entry in which-key-key-replacement-alist to be replaced. So C-RET would be replaced

The thing is they are just strings coming from a buffer, so there is no concept of "complete key". I think the case-sensitivity will actually cover many of the cases without resorting to regexp. `RET` will be distinguished from `<return>`, `TAB` from `<tab>` and so on. I probably need to make the special keys case sensitive too

**Comment by justbur** [comment]
This should be fixed. More complicated situations can be handled with regexp

**Comment by iqbalansari** [comment]
Just tried it, it seems it is fixed. Awesome thanks :clap: . Closing this.
