### ISSUE TITLE
Better sorting of keys in the popup

### ISSUE THREAD

**Issue by iqbalansari** [justbur/emacs-which-key#85]
I think sorting can be improved especially with regards to the function keys. Right now function keys (which might have useful keybindings) appear at the last page along with other obscure keys. Similarly `0 .. 9` (`digit argument`) appears very late in the pages, with default configuration it appears on 6th page in `dired-mode`.

**Comment by justbur** [comment]
I'm thinking the function keys can be bumped up, especially because there's never that many of them.

**Comment by justbur** [comment]
See if 25bd62a helps.

**Comment by iqbalansari** [comment]
This looks good, if only the `0 .. 9` could be pushed up I think the ordering would be perfect (atleast for me).

**Comment by justbur** [comment]
How far up?

**Comment by iqbalansari** [comment]
I would prefer them to right at the start of the popup, not sure others might agree, in which case I might tweak my custom sorting function a bit.

**Comment by justbur** [comment]
I think that makes sense for just that one set of keys. I'm going to make ignored keys and commands configurable too, in case someone wants to ignore commands like this

**Comment by iqbalansari** [comment]
Yes I agree, it might not make sense in all modes. I think I will settle with the current sorting. Feel free to close this. Thanks

**Comment by justbur** [comment]
I decided that "properly" means using the first character of the range to sort. This puts `1 .. 9` right behind `0` for example.

**Comment by iqbalansari** [comment]
Just tried it and seems to work well, thank you!
