### ISSUE TITLE
Root displays submaps

### ISSUE THREAD

**Issue by syl20bnr** [justbur/emacs-which-key#89]
When `SPC h K` in spacemacs or undoing up to the root, in the last page we can see submaps entries.
They could be hidden or displayed with a distinct face although I'm not sure if this is useful to see them.

**Comment by justbur** [comment]
I'm not sure what you mean, or I'm not seeing the issue you are describing

**Comment by syl20bnr** [comment]
I'll do a screenshot when I can.

**Comment by justbur** [comment]
Not sure what you're referring to. Please reopen if you find something
