### ISSUE TITLE
Allow modification of prefix prefix

### ISSUE THREAD

**Issue by Amorymeltzer** [justbur/emacs-which-key#90]
AFAICT, [line 1243](https://github.com/justbur/emacs-which-key/blob/master/which-key.el#L1243) is responsible for appending the symbol `+` to all prefixes:
````emacs
(desc (if group (concat "+" desc) desc))
````
This seems like good candidate for a new customizable option given that it is a fairly visible thing tweak.  Some minor testing seems to indicate removing it does nothing?

**Comment by justbur** [comment]
Yes, that would be easy to do. Do you just want to change the first character? I could have you provide a format string if you want to get fancy.

**Comment by Amorymeltzer** [comment]
Thanks - don't need anything too fancy, I just want to change or remove it (and I imagine others would as well).  I can't even imagine what you;d put in there that isn't a string, although I suppose someone might want yet-another-color.

**Comment by justbur** [comment]
Ok, here you go 30bc0c224bac091fcf2759c8e8853e7237196090

thanks for the suggestion

**Comment by Amorymeltzer** [comment]
Awesome, works great - thanks for the speedy turnaround!
