### ISSUE TITLE
which-key-show-map

### ISSUE THREAD

**Issue by justmytwospence** [justbur/emacs-which-key#92]
I have found `which-key-show-top-level` pretty useful. I often find myself wondering though, what are the keybindings specially defined by this mode/buffer/etc that I am in right now. I can imagine a new function, `which-key-show-map`, that opens a completing-read of `current-minor-mode-maps`, `current-local-map`, or `current-active-maps` (probably the last one?), allows you to select one, and then shows you a which-key menu for just those keybindings. Would such a thing be possible (hopefully it is clear what I mean)?

**Comment by justbur** [comment]
Yes, it should be. There's a function called `describe-keymap` in help-fns+.el that I use a lot, so it would essentially be this but to have the display be in the which-key buffer. Not sure I can do this right away, but I'll put it on my list.

**Comment by justbur** [comment]
Just added a basic version of this function called `which-key-show-keymap`. It's interactive and uses a completing read to select a keymap from any symbol that appears to be a keymap. The `current-active-keymaps` function doesn't show you the symbol name of the keymap, so it's not clear how to use that to select a keymap.

If you play with this a bit and give me some feedback on what you want to add, I can investigate more. I've only implemented showing the top-level at the moment btw.

**Comment by justbur** [comment]
Ok, now you can traverse the keymaps and I added a function to search the `minor-mode-map-alist`. No commands will be executed though. If you type a key that corresponds to a submap the submap will be shown. If you type any other key the popup is hidden.

**Comment by justmytwospence** [comment]
This is super useful. You are one of my favorite emacs devs for sure :). I'll let you know if I have any feedback as I use it.

**Comment by justbur** [comment]
:blush: btw I made some more changes to this last night (mainly getting the undo behavior working better)
