### ISSUE TITLE
Paging through 'C-h'

### ISSUE THREAD

**Issue by igorepst** [justbur/emacs-which-key#93]
Hi,
Is it possible to page through bindings that start with `C-h`? E.g. make the Emacs frame rather small, press `C-h`, wait for `which-key` to open, ensure there are additional pages (counter), press `C-h` as a paging prefix => `*Metahelp*` buffer is opened, no paging.
Thanks

**Comment by justbur** [comment]
This should work
```elisp
(define-key help-map "\C-h" 'which-key-C-h-dispatch)
```
Since there is a binding for `C-h C-h` in emacs, you have to explicitly override it with the line above.

**Comment by igorepst** [comment]
Indeed, thanks :)
