### ISSUE TITLE
closing the popup

### ISSUE THREAD

**Issue by starenka** [justbur/emacs-which-key#95]
Hi, I'm might be terribly wrong, but I just can't find a way how to close the popup properly. `q` or `C-g` will just add to already pressed keys...

**Comment by justbur** [comment]
Are you in the middle of a key sequence? It should close as soon as you type a key sequence that points to a valid command or you enter a key sequence that doesn't have any valid commands. You can also use `C-h a` for "abort" if you like.

**Comment by starenka** [comment]
Yes, I use it a lot to discover new shortcuts I don't know... `C-h a` is the thing I was looking for. Sorry for the issue and cheers for this awesome package!

**Comment by justbur** [comment]
No problem and thanks!
