### ISSUE TITLE
doesn't display properly when emacs is run from a tmux session.

### ISSUE THREAD

**Issue by hhnr** [justbur/emacs-which-key#96]
Refer below screen shots

**Comment by hhnr** [comment]
![screenshot from 2016-01-09 18 00 44](https://cloud.githubusercontent.com/assets/3027568/12216063/6a04d2ac-b6fb-11e5-9dda-bf7a90a55802.png)

**Comment by hhnr** [comment]
On pressing C-x ... then C-g
![screenshot from 2016-01-09 18 00 49](https://cloud.githubusercontent.com/assets/3027568/12216071/c545c81a-b6fb-11e5-9d12-09bd8732136e.png)

**Comment by hhnr** [comment]
I'm using Linux Mint 17.3 32bit with $TERM as xterm-256color. Which key displays properly when run from terminal. This issue happens only when it is run from tmux session

**Comment by justbur** [comment]
I just tried to reproduce with tmux and wasn't able to. It doesn't seem like a unicode problem, but try with 
```elisp
(setq which-key-separator ":")
```
to eliminate the possibility that it's a unicode issue.

**Comment by hhnr** [comment]
@justbur : adding the above line in my emacs config solves the issue. Thanks. I didn't have the above line in my emacs config before, maybe that's why i had this issue.

**Comment by justbur** [comment]
@hhnr you can also try increasing `which-key-unicode-correction`. I tried to explain in the docstring what the problem is. See [here](https://github.com/justbur/emacs-which-key/blob/master/which-key.el#L78-L92). You can also try different fonts.

**Comment by hhnr** [comment]
@justbur Okay. Will look into it. Thanks for the help.

**Comment by justbur** [comment]
@hhnr is this fixed?
