### ISSUE TITLE
Take fringe or margin sizes into account

### ISSUE THREAD

**Issue by syl20bnr** [justbur/emacs-which-key#97]
Referenced issue: https://github.com/syl20bnr/spacemacs/issues/3934

Sorry for not having reported it sooner.

**Comment by justbur** [comment]
@bmag I guess `frame-width` excludes the margins and fringes in emacs25 but not in 24. What do you think about using `(window-body-width (minibuffer-window))` instead of `(frame-width)`?

**Comment by justbur** [comment]
@bmag Sorry that was vague. I'm referring to this line https://github.com/justbur/emacs-which-key/blob/master/which-key.el#L1022

**Comment by justbur** [comment]
@bmag Sorry to bother you. I figured out a better way.

**Comment by bmag** [comment]
@justbur no problem, I don't mind. FYI a frame can have no minibuffer. From [the manual](http://www.gnu.org/software/emacs/manual/html_node/elisp/Minibuffers-and-Frames.html):
> you can also create a frame with no minibuffer

But I see you went for another solution, so it doesn't matter.
