### ISSUE TITLE
Feature request: Idle delay for first keystroke vs others

### ISSUE THREAD

**Issue by sachdevaprash** [justbur/emacs-which-key#98]
I think one should be able to specify an idle delay for triggering which-key, vs continuing in which-key on pressing a second key leading into a prefix.

**Comment by justbur** [comment]
Can you be more specific about how you expect this to work?

**Comment by sachdevaprash** [comment]
For example, if I press C-x, which-key uses 5 seconds to trigger as per which-key-idle-delay. Next I press '4', "C-x 4" still being a prefix will lead to which key update only after 5 seconds.

A long idle delay initially is sensible, since I don't want which-key triggered every time I am using a shortcut. But when I have decided to invoke it, I probably need help all along, so a long delay at that point is worthless. So two different variables: which-key-initial-idle-delay and which-key-idle-delay seems like a good feature to have.

**Comment by justbur** [comment]
Is it fair to say that you want the subsequent popups to be almost
immediate?

**Comment by justbur** [comment]
Never mind I can do it the way you suggested.

**Comment by sachdevaprash** [comment]
I would probably not mind immediate popups either.
Thanks!

**Comment by justbur** [comment]
Try this https://github.com/justbur/emacs-which-key/commit/f1d3d1b5e5351e5f878643496d8523fd54a96ca3

Variable name is `which-key-idle-secondary-delay`. If it's non nil this should be the time in seconds you want the subsequent popups to be displayed after.

**Comment by sachdevaprash** [comment]
I think this works perfect. Thanks a ton!

**Comment by justbur** [comment]
Great. Please open an issue if you notice any problems.
